AI 챗봇 앱 [STEP2] 범, 도라
tasty-code/ios-chat-bot pull request #11
Opened 2024-01-05 12:06 UTC by snowy-summer

리뷰어 | @protocorn93

버드 | @KSK9820, @snowy-summer

안녕하세요. 콘!!

AI 챗봇 버드 범, 도라입니다.

[STEP2]에서 URL Session을 활용한 네트워크 타입을 구현해 보았습니다.

읽어보시고 코멘트 남겨주시면 감사하겠습니다!! 🙏🙏
<br/>

## 프로젝트 파일 구조

```
.
├── ChatBot
│   ├── ChatBot
│   │   ├── APIKeys.plist
│   │   ├── AppDelegate.swift
│   │   ├── DTO
│   │   │   ├── CommonModel.swift
│   │   │   ├── RequestModel.swift
│   │   │   └── ResponseModel.swift
│   │   ├── Error
│   │   │   ├── ConvertError.swift
│   │   │   └── NetworkError.swift
│   │   ├── Extension
│   │   │   └── Bundle+Extension.swift
│   │   ├── Info.plist
│   │   ├── Network
│   │   │   ├── NetworkManager.swift
│   │   │   └── NetworkManagerProtocol.swift
│   │   ├── SceneDelegate.swift
│   │   ├── URL
│   │   │   ├── APIBaseURLProtocol.swift
│   │   │   └── OpenAIURL.swift
│   │   ├── Utility
│   │   │   └── Converter.swift
│   │   └── ViewController.swift
```
<br/>

## 프로젝트 설명

### 구현 내용

- [x]  URL Session을 활용한 서버와의 통신
- [x]  `CodingKeys` 프로토콜의 활용

### 각 역할 설명

**URL**

- APIBaseURLProtocol
    - API와 통신을 위한 URL의 기본적인 구성 요소들을 명시한 Protocol
- OpenAIURL
    - APIBaseURLProtocol을 준수하는 struct, OpenAI API를 호출하기 위해 사용하는 URL을 정의

**Network**

- NetworkManagerProtocol
    - API 통신을 위한 메서드를 명시한 protocol
- NetworkManager
    - `URLRequest`를 생성 및 생성된 `URLRequest`를 기반으로 `URLSession` 통신을 하는 메서드 구현

**Utility**

- Converter
    - API에게 요청을 할 때 보내는 Data로 변환하는 `encode` 메서드 구현
    - API에게 받은 Data를  원하는 타입으로 받는 `decode` 메서드 구현

**Error**

- NetworkError
    - 네트워크 통신시 발생할 수 있는 `Error` 케이스 구분
- ConverError
    - Encoding, Decoding `Error` 케이스 구분
<br/>

## 실행 결과

![image](https://github.com/tasty-code/ios-chat-bot/assets/118453865/736d4f22-ba1a-4275-905c-1e5476652b95)

간단한 테스트를 진행해서 응답이 정상적으로 오는지 확인을 하였고, 테스트 하는 코드들은 STEP3에 응답 데이터를 이용하는 과정이 있기 때문에 설계가 달라질 것이라고 생각하여 commit은 하지 않았습니다.

<br/>

## 질문 드리고 싶은 부분

### enum의 값을 String으로 활용하고 싶습니다.

현재 프로젝트 스텝에서는 아래 3가지 방법을 모두 사용하고 있습니다. 통일을 하는편이 가독성, 사용성에 좋을 것 같아 하나로 통일을 하고자 하는데, 현업에서는 주로 어떤 방법을 사용하시나요?

- string value 사용하기 (switch case)

```swift
struct OpenAIURL: APIBaseURLProtocol {
    var scheme: String = "https"
    var host: String = "api.openai.com"
    var path: String
}

enum Path: String {
    case chat
    
    var value: String {
        switch self {
        case .chat:
            return "/v1/chat/completions"
        }
    }
}

//사용시
guard let url = OpenAIURL(path: Path.chat.value).makeURL() else { return }
```

- 문자열 보간법

```swift
enum HttpMethod: String {
    case get
    case post
}

//사용시
urlRequest.httpMethod = "\(httpMethod)".uppercased()
```

- rawValue(enum 내부에서만)

```swift
struct Message: Codable {
    let role: Role
    let content: String?
}

enum Role: String, Codable {
    case system = "system"
    case user = "user"
    case assistant = "assistant"
}

//사용시
let encodedData = converter.encode(data: RequestModel(messages: [Message(role: .user, content: "hi")]))
```

### Request header의 외부에서 변경에 대해서

```swift
struct NetworkManager: NetworkManagerProtocol {
    private let apiKey = Bundle.main.apiKey
    
    func makeURLRequest(url: URL, httpMethod: HttpMethod) -> URLRequest {
        var urlRequest = URLRequest(url: url)
        
        urlRequest.httpMethod = "\(httpMethod)".uppercased()
        urlRequest.setValue("Bearer \(apiKey)", forHTTPHeaderField: "Authorization")
        urlRequest.setValue("application/json", forHTTPHeaderField: "Content-Type")
        
        return urlRequest
    }
}
```

URL을 생성할 때 path에 따라서 header값이 달라지는 경우가 있었습니다. 현재 스텝에서 필요하지는 않은 것 같지만 확장성을 고려한다면 현재 코드 처럼 사용하지 않고 urlRequest를 생성하는 메소드에 header값을 parameter로 전달받는 방법이 더 좋을까요?

- 이러한 고민을 하는 이유는 아래 예시와 같이 path만 다른 URL도 같은 NetworkManager를 재사용하도록 구현하고 싶기 때문입니다.

![image](https://github.com/tasty-code/ios-chat-bot/assets/118453865/2e1f5c0d-5a2a-493c-beed-e4058dfa77dd)

2024-01-08 10:45 UTC, protocorn93 requested changes
두 분 수고하셨습니다. 코드가 전체적으로 깔끔하여 리뷰하기 어렵지 않았어요. 

## 질문거리

> enum의 값을 String으로 활용하고 싶습니다.
>
> 현재 프로젝트 스텝에서는 아래 3가지 방법을 모두 사용하고 있습니다. 통일을 하는편이 가독성, 사용성에 좋을 것 같아 하나로 통일을 하고자 하는데, 현업에서는 주로 어떤 방법을 사용하시나요?

세 가지 모두 용도가 같지는 않은 것 같아요. 그렇기 때문에 굳이 사용법을 통일할 필요는 없어보여요. 첫번째, 두번째는 용도에 맞게 잘 사용된 것 같아요. 제가 속한 회사에서도 API 선언시 switch-case로 두 분이 작성하신 것과 유사한 형태로 구현하고 있어요. 

그리고 두 번째의 문자열 보간법은 저는 최대한 raw string을 다루는 코드는 한곳에 위치시키는 것을 선호해요. 휴먼에러가 발생할 수 있는 여지가 많기 때문이에요. 

저라면 `HTTPMethod`의 get-only 프로퍼티로 switch-case로 값을 반환할 것 같아요.

> URL을 생성할 때 path에 따라서 header값이 달라지는 경우가 있었습니다. 현재 스텝에서 필요하지는 않은 것 같지만 확장성을 고려한다면 현재 코드 처럼 사용하지 않고 urlRequest를 생성하는 메소드에 header값을 parameter로 전달받는 방법이 더 좋을까요?

이는 코멘트로도 남겼지만 저는 이들도 `APIBaseURLProtocol`에 녹여내는 것이 좋을 것 같아요. `URL`이 아니라 `URLRequest`를 반환하도록 변경이 되구요. 그렇게 되면 다른 API가 생겨도 해당 프로토콜만 채택하고, 네트워크 매니저의 `getData`인자로 `APIBaseURLProtocol`를 채택한 API 객체를 전달해주면 되니까요

2024-01-08 10:45 UTC, protocorn93 commented on ChatBot/ChatBot/Network/NetworkManager.swift
> +struct NetworkManager {
네트워크 매니저를 구조체로 선언하신 이유가 있을까요?

2024-01-08 10:45 UTC, protocorn93 commented on ChatBot/ChatBot/Network/NetworkManagerProtocol.swift
> +    mutating func makeURLRequest(url: URL, httpMethod: HttpMethod, body: Data?)
`makeURLRequest` 인터페이스는 내부적으로만 사용되어도 무방한 메서드로 보이는데, 추가된 이유가 궁금해요.

2024-01-08 10:45 UTC, protocorn93 commented on ChatBot/ChatBot/Network/NetworkManagerProtocol.swift
> +    func getData (handler: @escaping (Result<Data, NetworkError>) -> Void)
`makeURLRequest`는 내부적으로 사용하고 `getData`의 인자로 네트워크에 필요한 정보들을 받는 것은 어떨까요?

2024-01-08 10:45 UTC, protocorn93 commented on ChatBot/ChatBot/Utility/Converter.swift
> +}
좋네요! 다만 Converter 보단 보다 명확한 역할을 담는 네이밍으로 변경해보시는게 좋을 것 같아요.

2024-01-08 10:45 UTC, protocorn93 commented on ChatBot/ChatBot/URL/APIBaseURLProtocol.swift
> +    var path: String { get }
좋은 접근 방법인 것 같아요. 여기에 http method나 parameter도 추가되면 좋을 것 같은데, 어떻게 생각하시나요?

2024-01-08 10:45 UTC, protocorn93 commented on ChatBot/ChatBot/URL/APIBaseURLProtocol.swift
> +    func makeURL() -> URL?
`URLRequest`를 반환한다면 네트워킹 통신에 대해 필요한 정보의 응집도를 높일 수 있지 않을까요?

2024-01-08 10:45 UTC, protocorn93 commented on ChatBot/ChatBot/URL/APIBaseURLProtocol.swift
> +protocol APIBaseURLProtocol {
좋은 접근 방법인 것 같아요 👍

2024-01-08 10:45 UTC, protocorn93 commented on ChatBot/ChatBot/Network/NetworkManager.swift
> +        urlRequest.httpMethod = "\(httpMethod)".uppercased()
`"\(httpMethod)".uppercased()` raw string은 `HTTPMethod` 타입에서 제공해주면 좋을 것 같네요.

2024-01-08 10:45 UTC, protocorn93 commented on ChatBot/ChatBot/Network/NetworkManager.swift
> +                return }
여기서도 .failure를 반환해야하지 않을까요?

2024-01-09 02:49 UTC, snowy-summer commented on ChatBot/ChatBot/Utility/Converter.swift
> +}
JSONConverter로 변경했습니다.

2024-01-09 04:37 UTC, KSK9820 commented on ChatBot/ChatBot/Network/NetworkManagerProtocol.swift
> +    mutating func makeURLRequest(url: URL, httpMethod: HttpMethod, body: Data?)
APIBaseURLProtocol이 URLRequest를 반환하도록 했고, NetworkManager는 request를 전역변수로 가지고 초기화시 외부에서 주입해주는 방식으로 변경하였습니다. 
makeURLRequest 함수는 삭제하였습니다.

2024-01-09 04:38 UTC, KSK9820 commented on ChatBot/ChatBot/Network/NetworkManagerProtocol.swift
> +    func getData (handler: @escaping (Result<Data, NetworkError>) -> Void)
getData로 네트워크에 필요한 httpBody를 옵셔널 타입의 인자로 받아와서 사용하고 있습니다. 옵셔널 타입인 이유는 get 메서드와 post 메서드를 모두 사용할 수 있게 하기 위해서이고, get 메서드는 body를 필요로 하지 않기 때문입니다.

2024-01-09 04:52 UTC, snowy-summer commented on ChatBot/ChatBot/URL/APIBaseURLProtocol.swift
> +    var path: String { get }
parameter는 사용하는 경우도 있고 아닌 경우도 있기 때문에 옵셔널 타입의 변수로 가지게 하였고
http method가 변수로 존재하면 변수의 내용을 변경 했을때 url Request의 http method를 변경하는 작업을 한번 더 진행해줘야 한다고 생각합니다.
 그렇기 때문에 http Method의 경우는 변수가 아닌 makeURLRequest 함수를 사용할 때 파라미터로 받아오게 했습니다.

2024-01-09 04:52 UTC, KSK9820 commented on ChatBot/ChatBot/Network/NetworkManager.swift
> +                return }
해당 부분의 실수를 인지하고, completion handler를 사용하는 방법 대신 async/await 방식으로 네트워크 통신을 하도록 변경하였습니다.

2024-01-09 04:52 UTC, KSK9820 commented on ChatBot/ChatBot/Network/NetworkManager.swift
> +        urlRequest.httpMethod = "\(httpMethod)".uppercased()
HTTPMethod의 get-only 프로퍼티로 switch-case를 사용해서 uppercased된 반환 값을 사용하는 방식으로 변경하였습니다.

2024-01-09 04:57 UTC, KSK9820 commented on ChatBot/ChatBot/URL/APIBaseURLProtocol.swift
> +    func makeURL() -> URL?
URL을 만드는 함수를 private으로 만들고, 해당 함수를 makeURLRequest 함수에서 호출해서 사용하는 방식으로 변경하였습니다. 현재 APIBaseURLProtocol이 request까지 포함한 url을 관리하고 있습니다.

2024-01-09 05:19 UTC, KSK9820 commented on ChatBot/ChatBot/Network/NetworkManager.swift
> +struct NetworkManager {
이전에는 프로퍼티를 많이 가지고 있지 않았고, 상속될 일도 없다고 생각했기 때문에 성능상으로 이점이 있는 구조체를 사용했습니다.
하지만 현재는 내부 프로퍼티의 수에는 변화가 없지만 네트워크 통신을 할 때마다 urlRequest라는 프로티의 body를 계속 변경해줘야 하기 때문에 mutating 키워드를 쓰기보다는 class로 변경을 하였습니다.

`mutating` 을 사용하면 새로운 인스턴스 프로퍼티를 생성하고, 해당 메서드가 종료될 때 원본 구조체 인스턴스를 인스턴스 프로퍼티가 변경된 구조체 인스턴스로 대체된다고 알고있습니다. 그렇기 때문에 너무 많은 값의 변경은 새로운 인스턴스를 생성하고 대체하는 오버헤드가 클 것이라 생각해서 struct는 적절하지 못 하다고 생각했습니다.

혹시 콘은 어떤 기준으로 class와 struct를 구분해서 사용하시는지 여쭤봐도 될까요?

2024-01-09 10:33 UTC, protocorn93 commented on ChatBot/ChatBot/Network/NetworkManager.swift
> +struct NetworkManager {
저는 주로 레퍼런스가 필요하냐, 카피가 필요하냐에 따라 선택해주곤해요. 데이터 모델류들은 구조체로 주로 선언하긴해요.

2024-01-10 01:20 UTC, merged