AI 챗봇 앱 [STEP2] Comdori, 요한
tasty-code/ios-chat-bot pull request #14
Opened 2024-01-08 09:29 UTC by comdori-wj

# AI 챗봇 앱 [STEP2] Comdori, 요한
리뷰어: @zdodev

안녕하세요 소대! 
STEP2 PR 보냅니다. 잘 부탁드립니다~

<br/> 

### 구현 사항
- [x] URL Session을 활용한 서버와의 통신
- [x] CodingKeys 프로토콜의 활용

<br/> 

### 테스트 성공 스크린샷
![image](https://hackmd.io/_uploads/rkNH_4tOa.png)

<br/> 

## 핵심 클래스 설명

| 이름 | 타입 | 구현내용 |
| --- | --- | --- |
| ChatAPI | Class | API 네트워크 통신에 필요한 request를 생성하는 클래스 |
| NetworkManager | Class | Swift Concurrency를 사용하여 responseModel 객체를 반환하는 클래스 |

<br/>

## 궁금한 점 
- request를 만드는 구문(ChatAPI)과 네트워크 통신하는 구문(NetworkManager)을 분리하여 구현하였습니다. "WWDC21 - Meet async/await in Swift" 에서는 두 구문을 한 클래스에서 구현하였는데, 저희가 생각하기엔 네트워크를 어떻게 정의(생각)하느냐에 따라 다르다고 생각하여 분리하여 구현하였는데 소대는 어떻게 생각하는지 궁금합니다!

2024-01-09 12:53 UTC, zdodev requested changes
안녕하세요. @comdori-wj , @dpwns1234 !

Step2 잘 진행해주셨습니다!
네트워크 요청도 잘 수행하고 있습니다~

간단한 코멘트를 남겨보았습니다.
확인해보고 넘어가면 좋을 것 같습니다!

2024-01-09 12:53 UTC, zdodev commented on ChatBot/ChatBot.xcodeproj/project.pbxproj
> +			path = Extenssions;
폴더명에 오타가 있는 것 같습니다!

2024-01-09 12:53 UTC, zdodev commented on ChatBot/ChatBot/Models/Errors.swift
> +enum NetworkError: Error {
네트워크 에러를 세분화해서 구현해보셨네요. 좋습니다!

2024-01-09 12:53 UTC, zdodev commented on ChatBot/ChatBot/Network/NetworkManager.swift
> +        let (data, response) = try await URLSession.shared.data(for: request)
`URLSession`에 있는 concurrency 메서드를 사용해보셨네요.👍

2024-01-09 12:53 UTC, zdodev commented on ChatBot/ChatBot/ChatAPI.swift
> +    func makeRequest(body: Data?) async throws -> URLRequest {
`makeRequest` 메서드를 `async`로 구현하신 이유가 궁금합니다!

2024-01-09 12:53 UTC, zdodev commented on ChatBot/ChatBot/Network/NetworkManager.swift
> +final class NetworkManager {
`URLRequest` 타입을 생성하는 부분과 네트워크 요청하는 부분을 분리하는 것도 좋은 방법이라고 생각합니다!
본문 내용중에 `네트워크를 어떻게 정의(생각)하느냐에 따라 다르다`라는 부분에서 어떤 식으로 생각하여 분리 하셨는지 궁금합니다!

2024-01-09 12:53 UTC, zdodev commented on ChatBot/ChatBot/ViewController.swift
> +                                toolCalls: nil)]
이런 구문에서는 개인적으로 다음과 같은 형식을 선호하고 있습니다. 참고만 해주세요!
```
let messages = [
    Message(
        role: "user",
        content: "안녕 넌 누구야?",
        toolCalls: nil
    )
]
```

2024-01-10 00:49 UTC, comdori-wj commented on ChatBot/ChatBot.xcodeproj/project.pbxproj
> +			path = Extenssions;
네 고치겠습니다.

2024-01-10 02:09 UTC, comdori-wj commented on ChatBot/ChatBot/Network/NetworkManager.swift
> +final class NetworkManager {
네트워크매니저에는 서버와 통신만 해야하는가에 대해서 고민을 많이 하였습니다. 고민을 해본 결과 일단은 `WWDC21 - Meet async/await in Swift`에 나온 방식대로 디코드까지 하여 응답모델을 만들어 주는거 까지가 맞다고 생각하여 네트워크매니저를 구성하게 되었습니다. 뷰컨트롤러에 있는 request도 네트워크모델에 들어가야한다고 생각하였으나 요청하는 부분과 응답하는 속성이 다르기 때문에 따로 분리하였습니다.

2024-01-10 02:11 UTC, comdori-wj commented on ChatBot/ChatBot/ViewController.swift
> +                                toolCalls: nil)]
가독성이 한결 좋아진 것 같아 반영하겠습니다. 😀

2024-01-10 02:39 UTC, comdori-wj commented on ChatBot/ChatBot/ChatAPI.swift
> +    func makeRequest(body: Data?) async throws -> URLRequest {
`makeRequest`에서는 `async`가 필요하지 않은 것 같아 수정하겠습니다. 😅

2024-01-10 02:49 UTC, dpwns1234 commented on ChatBot/ChatBot/Network/NetworkManager.swift
> +final class NetworkManager {
우선 저희는 네트워크를 오직 통신만 하는 곳이라 정의하였습니다. 네트워크에 필요한 request가 user의 입력에 따라 다양하게 만들어질 수 있다 생각되어 둘을 분리한 것 같습니다.
예를들어 request에는 user의 메세지가 혹은 다른 body값이 들어갈 수가 있는데, 그렇다면 이 request를 NetworkManager 한 곳에서 관리하는 것보다 따로 분리하여 관리하는 것이 용이하다고 생각하였습니다.

2024-01-10 14:28 UTC, zdodev commented on ChatBot/ChatBot/Network/NetworkManager.swift
> +final class NetworkManager {
메시지를 생성하는 부분과 네트워크 통신하는 부분을 각각 다른 역할로 생각해보셨네요!
분리에 대한 근거와 이유를 가지고 작성하신 부분이 좋습니다!👍

2024-01-10 14:32 UTC, zdodev approved these changes
안녕하세요. @comdori-wj , @dpwns1234 !

Step2 진행하시느라 고생하셨습니다!
소소한 부분도 잘 개선해보셨네요.
Step2는 여기서 마무리하도록 하겠습니다.🎉

2024-01-10 14:33 UTC, merged