AI 챗봇 앱 [STEP2] 하워드, 록스
tasty-code/ios-chat-bot pull request #15
Opened 2024-01-09 01:05 UTC by KimRoks

리뷰어: @jryoun1

버드: @JEON-Sungsu, @KimRoks

안녕하세요, 제이크!!

[STEP 2]에서는 URLSession을 이용한 NetworkManager를 구현하였습니다.

잘 부탁드립니다!
## 코드 실행 결과
<img width="1355" alt="스크린샷 2024-01-08 오후 3 45 29" src="https://github.com/tasty-code/ios-chat-bot/assets/113083860/2200ed5b-f4b4-470f-940e-33c4279e1d06">

### 코드설명

- NetworkingManager

```swift
final class NetworkingManager {
    static let shared = NetworkingManager()
    private let decoder = JSONDecoder()
    
    private init() { }
    
    func downloadData<T: Decodable>(request: URLRequest,to type: T.Type, completion: @escaping (Result<T, Error>) -> Void) {
        
        URLSession.shared.dataTask(with: request) { data, response, error in
            guard error == nil else {
                return completion(.failure(NetworkingError.taskingError))
            }
            
            guard let response = response as? HTTPURLResponse else {
                return completion(.failure(NetworkingError.unknown))
            }
            
            guard (200..<300).contains(response.statusCode) else {
                return completion(.failure(NetworkingError.networkError(statusCode: response.statusCode)))
            }
            
            guard let data = data else {
                return completion(.failure(NetworkingError.corruptedData))
            }
            
            do {
                let model = try self.decoder.decode(type.self, from: data)
                completion(.success(model))
            } catch {
                print(error)
            }
            
        }.resume()
    }
}
```

> Networking을 담당하는 NetworkManager를 만들었습니다. 이 객체를 통해서만 통신이 가능하게 하기 위해서 Singlton 패턴으로 만들었습니다. 또한 범용성을 높이기 위해 `Generic` 타입을 받아서, 추후에 어떤 DTO에도 디코딩이 가능하도록 만들어 보았습니다.
> 

- RequestGenerator

```swift
struct RequestGenerator {
    private let urlString = "https://api.openai.com/v1/chat/completions"
    
    func generateRequest(_ httpBody: Data) -> URLRequest? {
        guard let url = URL(string: urlString) else {
            return nil
        }
        
        guard let APIKey = Bundle.getAPIKey(for: "openAI_APIKey") else {
            return nil
        }

        var request = URLRequest(url: url)
        request.httpMethod = "POST"
        request.setValue("application/json", forHTTPHeaderField: "Content-Type")
        request.setValue("Bearer \(APIKey)", forHTTPHeaderField: "Authorization")
        request.httpBody = httpBody
        
        return request
    }
}
```

> 사용자의 응답값을 받아서 Request를 만들어야 하기 때문에, Request를 만드는 객체를 따로 만들어 보았습니다.
> 

- QuestionEncoder

```swift
struct QuestionEncoder {
    enum Constant {
        static let model = "gpt-3.5-turbo"
        static let stream = false
        static let AIRole = "assistant"
        static let AIContent = "You are a helpful assistant."
        static let UserRole = "user"
    }

    func transformData(_ question: String) -> Data? {
        let userMessages: [UserMessage] = [UserMessage(role: Constant.AIRole, content: Constant.AIContent),
                                           UserMessage(role: Constant.UserRole, content: question)]
        let userQuestion = UserQuestionModel(model: Constant.model, stream: Constant.stream, userMessage: userMessages)

        guard let encodedData = try? JSONEncoder().encode(userQuestion) else {
            print("유저 입력값 인코딩 에러")
            return nil
        }

        return encodedData
    }
}
```

> 유저의 입력값을 받아서, Encoding을 해주는 객체를 분리하였습니다. STEP1에 문의드렸던 대로, 고정값들은 init 시점에서 넣어주고, 열거형타입에 상수값을 만들어서 집어 넣도록 해보았습니다.
> 

결과적으로 각 객체는 서로를 모른채 뷰컨을 통해서 값만주고 받는 형태로 만들어 보려고 하였습니다. 

### 궁금한점

1. 저희가 이번 스텝을 진행하며 크게 고민했던 부분은 “범용성이 높은 코드”였는데요, `RequestGenerator` 타입에서 특정된 url을 통째로 입력받는 등 개선하고 싶은 부분들이 보이지만 어떤 방식이 좋을지 잘 모르겠습니다.
해당 부분들을 Enum으로 작성하고 generateRequest()의 구성 요소를 모두 매개변수로 받도록 하는 방법을 생각 해보았지만 너무 많은 매개변수를 갖게 되고 코드의 가독성이 떨어진다고 생각이 됩니다. 다른 어떠한 방법이 있을까요?

2024-01-09 13:07 UTC, jryoun1 requested changes
고생하셨습니다! step2 잘 진행해주셨네요 👏 💯 
질문에 대한 답변은 코멘트에 같이 남겨드렸습니다. 확인부탁드려요 🙏 

다만 테스트에 대해서 print 정도 찍는식으로 테스트가 되었는데, UnitTest를 작성하지 않으신 이유가 궁금합니다 🙋‍♂️

2024-01-09 13:07 UTC, jryoun1 commented on ChatBot/ChatBot/Enums/Error/NetworkingError.swift
> +enum NetworkingError: Error, CustomDebugStringConvertible {
에러 종류들을 잘 정의해주셨네요 👏 
CustomDebugStringConvertible도 사용해보셨군요 💯

2024-01-09 13:07 UTC, jryoun1 commented on ChatBot/ChatBot/Utility/DataTransfer/QuestionEncoder.swift
> +    func transformData(_ question: String) -> Data? {
질문뿐만 아니라 대화가 될 수도 있으니 question보다는 content가 더 적절해보입니다 🙏 
QuestionEncoder 타입명도 동일합니다!

2024-01-09 13:07 UTC, jryoun1 commented on ChatBot/ChatBot/Utility/Network/NetworkingManager.swift
> +    private init() { }
싱글톤 패턴을 사용하셨군요! 👏 
싱글톤으로 구현하신 이유가 궁금합니다 🙋‍♂️

2024-01-09 13:07 UTC, jryoun1 commented on ChatBot/ChatBot/Utility/Network/NetworkingManager.swift
> +                return completion(.failure(NetworkingError.taskingError))
여기서 NetworkingError.taskingError를 넘기면 정의하신 에러로 처리는 되겠지만 실제로 어떤 error인지는 알 수 없을 것 같은데 괜찮을까요? 🤔

2024-01-09 13:07 UTC, jryoun1 commented on ChatBot/ChatBot/Utility/Network/NetworkingManager.swift
> +                print(error)
decode에 실패한 경우는 처리하지 않아도 되나요?

2024-01-09 13:07 UTC, jryoun1 commented on ChatBot/ChatBot/Utility/Network/NetworkingManager.swift
> +    func downloadData<T: Decodable>(request: URLRequest,to type: T.Type, completion: @escaping (Result<T, Error>) -> Void) {
`URLRequest` 타입을 매개변수로 전달 받는 것으로 구현하셔서, 다른 앱에서도 충분히 이 NetworkingManager를 사용할 수 있을 것 같네요 👍

2024-01-09 13:07 UTC, jryoun1 commented on ChatBot/ChatBot/Utility/Network/RequestGenerator.swift
> +}
여기가 질문주신 부분이군요. 

우선 지금 구현해주신 부분은 사실 특정 값들이 이미 다 설정되어있기에 재사용성이나 범용성 측면에서는 좋지 않은 것 같습니다. 
예를 들어 endpoint가 바뀐다던가, httpMethod 타입이 POST가 아니라 PUT으로 변경된다던가 등의 다른 요구사항이 생긴다면 또 다른 RequestGenerator2()가 생성되어야할 것 같네요. 

Request를 하기위해서 필수적으로 필요한 값들은 어떤 것들이 있을까요? 
지금 보여지는 코드에서는 url(endpoint), apiKey, httpBody, httpMethod, content형태 등이 필수적으로 보여지네요.

그렇다면 해당 값들을 아래와 같은 프로토콜로 정의하고 해당 프로토콜을 채택하는 타입을 받아서 generator가 처리하는 방향으로 구현해볼수도 있을 것 같네요. 
```Swift
protocol Endpoint {
   var url: String { get } 
   var apiKey: String { get } 
   var httpMethod: HTTPMethod { get } 
   var contentType: String? { get }
   var httpBody: Data { get } 
}

// concrete Endpoint
struct ChatBotEndpoint: Endpoint {
      // 각각의 프로토콜 값들에 대한 값 지정
}

// Generator
func generateRequest(_ endpoint: Endpoint) -> URLRequest? { 
      // endpoint.url, endpoint.apiKey, endpoint.httpMethod 등을 사용할 수 있겠죠? 
}
```
이렇게 되면 다른 url, apiKey 등을 사용하는 endpoint가 생성되어도 generator 자체는 변경이 필요 없을 것 같네요!

2024-01-09 13:07 UTC, jryoun1 commented on ChatBot/ChatBot/Utility/DataTransfer/QuestionEncoder.swift
> +    }
encoder 부분도 decoder쪽에서 말씀드린것 처럼 추상화 객체를 받아서 처리하는 식으로 구현하면 좀 더 범용성이 있겠네요! 

그리고 저 값들이 고정이라면 protocol extension을 통해서 기본값을 설정해주는 방향으로 처리해도 될 것 같네요. 한 번 고민해보시죠! 🙏

2024-01-10 01:05 UTC, JEON-Sungsu commented on ChatBot/ChatBot/Utility/Network/NetworkingManager.swift
> +                print(error)
디코딩 실패 케이스 에러 추가해서 `completion(.failure)` 로 넘겨서 처리할 수 있도록 변경하였습니다!

2024-01-10 01:07 UTC, JEON-Sungsu commented on ChatBot/ChatBot/Utility/Network/NetworkingManager.swift
> +    private init() { }
채팅앱의 특성상 지속적이거나 빈번한 네트워킹 통신이 필요한데, 그때마다 NetworkingManager를 메모리에 올렸다 내렸다 하는것 보다, 싱글톤을 사용해서 앱 시작부터 종료까지 메모리에 상주하는게 성능상으로 더 좋을것 같다 라는 생각에 싱글톤으로 사용하게 되었습니다.

2024-01-10 08:14 UTC, KimRoks commented on ChatBot/ChatBot/Utility/DataTransfer/QuestionEncoder.swift
> +    func transformData(_ question: String) -> Data? {
수정하였습니다!

2024-01-10 08:20 UTC, KimRoks commented on ChatBot/ChatBot/Utility/Network/RequestGenerator.swift
> +}
말씀해주신 대로 Endpointable이란 프로토콜을 채택하는 방식으로 수정하였습니다.
프로토콜 내의 httpHeader는 사용처에서 입력받아 좀 더 범용성있게 사용할 수 있도록 해보았습니다.

2024-01-10 08:36 UTC, JEON-Sungsu commented on ChatBot/ChatBot/Utility/Network/NetworkingManager.swift
> +                return completion(.failure(NetworkingError.taskingError))
해당 부분을 guard let 에서 if let으로 변경하여, 에러가 있을 경우 localizedDescription 으로 어떤 에러인지 확인을 하고, 에러에 대한 처리는 뒤에서 하도록 변경해보았습니다! 

```
 if let error = error {
      print(error.localizedDescription)
      return completion(.failure(NetworkingError.taskingError))
  }
```

2024-01-11 04:40 UTC, JEON-Sungsu commented on ChatBot/ChatBot/Utility/DataTransfer/QuestionEncoder.swift
> +    }
안녕하세요 제이크! encoder쪽도 마찬가지로 추상화를 해보려고 했는데, DTO 에 Extenstion을 통한 기본값을 설정해서, encoding 할 때 Encodable을 따르는 DTO를 파라미터로 받아서 진행해보려고 했으나, 이렇게 하니깐 기본값으로 설정한 프로퍼티들은 인식이 되지 않아서 자꾸 오류가 발생하더라구요!

그래서 그냥 encoding이 필요한 DTO의 고정값인 model 과 stream은 타입 구현부에 바로 정의하도록 하고, 나머지 messages에 들어갈 내용들은 DTO 인스턴스를 초기화 할때 주입하는것으로 변경하였습니다.

2024-01-11 04:41 UTC, JEON-Sungsu commented
> 고생하셨습니다! step2 잘 진행해주셨네요 👏 💯 질문에 대한 답변은 코멘트에 같이 남겨드렸습니다. 확인부탁드려요 🙏
> 
> 다만 테스트에 대해서 print 정도 찍는식으로 테스트가 되었는데, UnitTest를 작성하지 않으신 이유가 궁금합니다 🙋‍♂️

> 저희가.. 구현에 정신이 팔리고 시간에 쫒겨서 사실 UnitTest를 진행할 생각을 못했던것 같습니다...... 다음번에는 유닛테스트를 적용시켜볼 수 있도록 노력해보겠습니다..!!!

2024-01-11 04:45 UTC, JEON-Sungsu commented on ChatBot/ChatBot/Utility/Network/RequestGenerator.swift
> +}
한 차례 더 개선을 통해서, RequestGenerator객체는 지우고, Endpoint 프로토콜의 extenstion으로 request를 만들 수 있도록 메서드를 추가하는 방향으로 개선해보았습니다.

기존의 방식대로 가게 된다면, 각각의 역할을 하는 객체들이 너무 많아져서, 나중에 ViewController에서 알고 있어야 되는 객체가 너무 많아질 것 같아서 이부분을 고려하다 보니, 어차피 Endpoint들은 Request생성을 위한 모든 요소들을 가지고 있으니, 프로토콜을 통해서 얘가 Request를 생성도 하게끔 하면 되지 않을까? 라는 생각으로 출발하게 되었고, 이런 결과물이 나오게 되었습니다. 덕분에 저희 생각은 훨씬 범용성이 좋아졌다고 생각한게, 다른 API를 사용하더라도 Endpoint를 채택하는 객체만 만들어주면 언제든 request를 생성할 수 있게 되었다고 생각했습니다.

확인해주시면 감사하겠습니다.

2024-01-11 12:57 UTC, jryoun1 reviewed
수정해주신 부분 확인했습니다! 👍 
추가로 코멘트 몇가지 더 남겨두었습니다.

2024-01-11 12:57 UTC, jryoun1 commented on ChatBot/ChatBot/Utility/DataTransfer/ContentEncoder.swift
> +struct ContentEncoder {
content뿐만 아니라 다른 Encodable을 채택하는 모든 타입의 encode된 데이터를 반환하는 것 같아서 그냥 Encoder라고 네이밍 해도 괜찮을 것 같네요.

2024-01-11 12:57 UTC, jryoun1 commented on ChatBot/ChatBot/Utility/DataTransfer/ContentEncoder.swift
> +    var encoder = JSONEncoder()
외부에서 접근될 일이 있을까요?

2024-01-11 12:57 UTC, jryoun1 commented on ChatBot/ChatBot/Models/Endpoint/Protocol/Endpointable.swift
> +}
여기가 말씀주신 부분이군요. 👏 
기존에는 Endpoint는 API에 관련된 정보들을 가진 추상화된 객체였다면 지금은 거기에 + encoder도 가지고 있고, request도 생성해야하니 개인적으로는 오히려 Endpoint 객체의 역할이 더 많이졌다고 느껴지긴 합니다만 이 부분은 두 분께서 Endpoint객체의 역할을 어느 정도까지 부여하느냐에 따라서 충분히 다를 수 있기에 편하신대로 진행하시면 될 것 같습니다. 👍

2024-01-11 12:57 UTC, jryoun1 commented on ChatBot/ChatBot/Models/Endpoint/ChatBotEndpoint.swift
> +}
해당 객체를 생성하는 시점에 값들을 초기화 하게 될까요? 
기본값을 주지 않는 이유도 궁금합니다. 🙋‍♂️

2024-01-11 12:57 UTC, jryoun1 commented on ChatBot/ChatBot/Enums/Network/HTTPMethods.swift
> +enum HTTPMethods{
HTTPMethod라고 네이밍하는게 더 자연스러운 것 같습니다!

2024-01-11 12:57 UTC, jryoun1 commented on ChatBot/ChatBot/Enums/Network/ContentTypes.swift
> +        case.json: "application/json"
case 뒤에 space가 빠진것 같네요

2024-01-11 12:57 UTC, jryoun1 commented on ChatBot/ChatBot/Enums/Network/ChatbotHeaderField.swift
> +enum ChatbotHeaderFieldName {
headerFieldName은 과연 chatbot에서만 Content-Type, Authorization일까요? 
아니면 다른앱에서도 동일할까요?

2024-01-11 12:57 UTC, jryoun1 commented on ChatBot/ChatBot/Enums/Network/BaseURL.swift
> +        case.openAI: "https://api.openai.com/v1/chat/completions"
여기도 space요!

2024-01-11 12:57 UTC, jryoun1 commented on ChatBot/ChatBot/Enums/Network/APIName.swift
> +enum APIName {
description을 보면 APIKey 네이밍인것 같은데 타입명이 APIName로 불명확해보이네요.

2024-01-11 13:16 UTC, merged

2024-01-12 00:53 UTC, KimRoks commented on ChatBot/ChatBot/Utility/DataTransfer/ContentEncoder.swift
> +struct ContentEncoder {
수정하였습니다!

2024-01-12 00:54 UTC, KimRoks commented on ChatBot/ChatBot/Utility/DataTransfer/ContentEncoder.swift
> +    var encoder = JSONEncoder()
외부에서 사용 될 일 없는 프로퍼티의 은닉화를 진행하였습니다!

2024-01-12 00:55 UTC, KimRoks commented on ChatBot/ChatBot/Enums/Network/HTTPMethods.swift
> +enum HTTPMethods{
수정하였습니다!

2024-01-12 00:55 UTC, KimRoks commented on ChatBot/ChatBot/Enums/Network/ContentTypes.swift
> +        case.json: "application/json"
수정하였습니다

2024-01-12 00:56 UTC, KimRoks commented on ChatBot/ChatBot/Enums/Network/BaseURL.swift
> +        case.openAI: "https://api.openai.com/v1/chat/completions"
수정 완료했습니다!

2024-01-12 00:58 UTC, KimRoks commented on ChatBot/ChatBot/Enums/Network/APIName.swift
> +enum APIName {
APIKeyName 으로 네이밍 변경하였습니다!

2024-01-12 01:14 UTC, KimRoks commented on ChatBot/ChatBot/Enums/Network/ChatbotHeaderField.swift
> +enum ChatbotHeaderFieldName {
여러 예시를 찾아보고 범용적으로 쓰일 수 있을거같다고 판단이 되어서 HeaderFieldName으로 수정하였습니다!

2024-01-12 01:19 UTC, JEON-Sungsu commented on ChatBot/ChatBot/Models/Endpoint/ChatBotEndpoint.swift
> +}
넵 해당 객체는 인스턴스화 시점에서 초기화를 하게 됩니다. 기본값을 주지 않은 이유는,
현재 저희 프로젝트의 명세대로라면 프로퍼티들의 값이 바뀔 여지가 없기에, 고정값을 써도 무방하다고 생각되지만,
기왕 범용성을 고려해서 만들었으니, 혹시 모를 다른 endpoint가 필요한 상황이 오게 된다면(audio,file,image...등등), 이 부분을 고려해서 생성시점에 프로퍼티의 값들을 초기화 해주는 방향으로 만들어보았습니다.