AI 챗봇 앱 [STEP 2] 뉴준성
tasty-code/ios-chat-bot pull request #17
Opened 2024-01-09 07:56 UTC by newJunsung

안녕하세요👋 린생(@jungseungyeo)! STEP2을 다 해서 PR을 올립니다. 확인해주시면 감사하겠습니다!

### To-do List
- 네트워킹 타입 구현
- 유닛 테스트 작성

# STEP2 진행 중 경험 사항

## 네트워킹 타입 구현

### 네트워킹 타입의 전반적인 구조
> `HTTPRequest` -> `HTTPPublisher` -> `HTTPService`

`HTTPRequest`에서 `URLRequest`를 만들면, 그 `URLReqeust`를 `HTTPPublisher`가 `AnyPublisher<Data, Error>`타입으로 만듭니다. 해당 `AnyPublisher`를 이용하여 `HTTPService`가 `Data`를 `Decodable`한 타입으로 매핑하여 `AnyPublisher<T, Error>`타입으로 반환합니다.

각 타입들이 유연하게 대체할 수 있고 테스트 가능하게 만들기 위해서, 프로토콜화 하였습니다.

- **HTTPServicable.swift**
```swift
protocol HTTPServicable {
    func request<D: Decodable>(request: HTTPRequestable, type: D.Type) -> AnyPublisher<D, Error>
    func request<E: Encodable, D: Decodable>(request: HTTPRequestable, object: E, type: D.Type) -> AnyPublisher<D, Error>
}
```

- **HTTPPublishable.swift**
```swift
protocol HTTPPublishable {
    func publish(urlRequest: URLRequest) -> AnyPublisher<Data, GPTError.HTTPError>
}
```

- **HTTPRequestable.swift**
```swift
protocol HTTPRequestable: AnyObject {
    var urlString: String? { get }
    var paths: [String]? { get }
    var queryStrings: [String: CustomStringConvertible]? { get }
    
    var headerFields: [String: String]? { get }
    var httpMethod: Network.HTTPMethod { get }
    
    func configureURL() -> URL?
    func asURLRequest() throws -> URLRequest
}
```

### HTTPRequestable? HTTPDecoratable?
`HTTPRequestable`은 아래의 코드와 같이 기본적인 URL에 관련한 주소를 담고 있습니다.

- **GPTBaseReqeust.swift**
```swift
extension Network {
    final class GPTBaseReqeust: HTTPRequestable {
        let urlString: String? = "https://api.openai.com"
        let paths: [String]? = ["v1", "chat", "completions"]
        let headerFields: [String : String]? = nil
        let httpMethod: Network.HTTPMethod = .get
    }
}
```

데코레이터 패턴을 적용하여 기본 리퀘스트 바탕에 다양한 정보들(ex. 헤더 필드)을 덧붙일수 있도록 했습니다.
- **HTTPDecoratable.swift**
```swift
protocol HTTPDecoratable: HTTPRequestable {
    var httpRequest: HTTPRequestable { get }
}

extension HTTPDecoratable {
    var urlString: String? { nil }
}
```

- **ContentDecorator**
```swift
extension Network {
    final class ContentDecorator: HTTPDecoratable {
        let httpRequest: HTTPRequestable
        let httpMethod: Network.HTTPMethod = .post
        let headerFields: [String : String]?
        
        init(httpRequest: HTTPRequestable, contentType: Network.HTTPContentType) {
            self.httpRequest = httpRequest
            self.headerFields = ["Content-Type": "\(contentType)"]
        }
        
        func asURLRequest() throws -> URLRequest {
            guard let headerFields = headerFields else {
                throw GPTError.HTTPError.invalidURL
            }
            
            var request = try httpRequest.asURLRequest()
            request.httpMethod = "\(httpMethod)"
            for (key, value) in headerFields {
                request.setValue(value, forHTTPHeaderField: key)
            }
            return request
        }
    }
}
```

두 프로토콜을 활용하여 아래와 같이 사용할 수 있습니다.
```swift
let httpRequest: HTTPRequestable = Network.ContentDecorator(httpRequest: Network.GPTBaseReqeust(), contentType: .json)
```

## 유닛 테스트 작성

### DummyData
아래와 같이 더미 응답을 만들고, `Bundle`을 활용하여 데이터를 추출했습니다.
<img width="410" alt="image" src="https://github.com/tasty-code/ios-chat-bot/assets/107932188/00f84ade-4ea7-42bf-8a7e-8586b1fbf26b">

### MockType
유닛 테스트의 경우 NetworkService를 테스트 하기 위해서, `MockHTTPPublisher`와 `MockHTTPRequest`를 만들었습니다.
`URLSession`으로 물론 테스트를 해볼 수 있지만, 네트워크 통신이 안되는 환경에서 유닛테스트를 하기 위해서 입니다.

- **MockHTTPPublisher.swift**
```swift
import Combine
import Foundation

@testable import ChatBot

final class MockHTTPPublisher: HTTPPublishable {
    func publish(urlRequest: URLRequest) -> AnyPublisher<Data, ChatBot.GPTError.HTTPError> {
        guard let data = try? JSONFetcher.fileData(of: urlRequest.url!.absoluteURL) else {
            return Fail(error: .unknownError(description: "Data를 찾을 수 없음."))
                .eraseToAnyPublisher()
        }
        
        return Just(data)
            .setFailureType(to: ChatBot.GPTError.HTTPError.self)
            .eraseToAnyPublisher()
    }
}
```

- MockHTTPRequest.swift
```swift
import Foundation

@testable import ChatBot

final class MockHTTPRequest: HTTPRequestable {
    let urlString: String? = "GPTReplyMock"
    let httpMethod: ChatBot.Network.HTTPMethod = .get
    
    func configureURL() -> URL? {
        try? JSONFetcher.fileURL(of: urlString!)
    }
}
```

2024-01-09 11:00 UTC, jungseungyeo requested changes
뉴준성 고생하셨습니다.

코드를 보면서 사실 크게 문제가 되는 부분이 보이지 않았습니다.
그래도 더욱을 드리고자 제 개발경험에서 해당 부분을 어떻게 수정을 하면 유지보수가 더욱 좋아지더라 
왜 수정이 필요한지 코멘트를 남겼습니다.

pr을 보내주신 부분에서도 의문점이 있는 부분이 아닌 구현 방법을 대해서 작성을 해주셔서 코드를 읽는데 크게 어렵지도 않았습니다.

혹시나 질문이 있다면 남겨주시고 코멘트 보시고 질문이 생기면 알려주세요 ㅎㅎ 고생하셨습니다.

2024-01-09 11:00 UTC, jungseungyeo commented on ChatBot/ChatBot/DataDecoder/Implements/JSONDecoder+DataDecoderable.swift
> +extension JSONDecoder: DataDecoderable {
DataDecoderable를 채택하여 기능을 구현하셨네요 ㅎㅎ 너무좋아요.
이러한 코드는 POP 구조라고하는데요. 위와 같은 코드를 작성하여 기능을 구현하는 스타일을 협업에서 많이 사용하고 있습니다. 

너무 좋습니다.

2024-01-09 11:00 UTC, jungseungyeo commented on ChatBot/ChatBot/DataDecoder/Protocols/DataDecoderable.swift
> +    func decodeData<T: Decodable>(_ data: Data, to type: T.Type) throws -> T
저도 이러한 스타일로 네트워크 객체를 구현하고 있습니다 ㅎㅎ 너무 좋네요 
위의 코드에서 하나를 수정하면 좋을거같은데요.

```suggestion
    func decodeData<T: Decodable>(_ data: Data) throws -> T
```

위와 같이 함수를 작성하는 것은 어떤가요? 어차피 return 타입에서 T를 추상화하고 있기 때문에 의도적으로 T.Type을 넣어주지 않아도 사용 할 수 있을거같아요.

2024-01-09 11:00 UTC, jungseungyeo commented on ChatBot/ChatBot/Errors/Implements/HTTPError.swift
> +extension GPTError {
제가 좋아하는 스타일이네요 ㅎㅎ 해당 스타일을 원래 잘 사용하나요? 아니면 제가 저번 pr에서 요청을 드려서 사용을 하셨나요?
이러한 형태로 사용해보니 어떠신가요?

2024-01-09 11:00 UTC, jungseungyeo commented on ChatBot/ChatBot/Networks/HTTPPublisher/Implements/URLSession+HTTPPublishable.swift
> +    func publish(urlRequest: URLRequest) -> AnyPublisher<Data, GPTError.HTTPError> {
함수의 기능이 너무 좋아요. 그래도 함수명은 동사형이면 좋아요.
publisher라는 네이밍에서 어떤 return 타임이 될지 알겠지만. 네이밍이 `responsePublisher()` 한다면 확장을 할 때 더 용이 할 거같아요.

예를 들어 async/await로 구현을 한다면 `responseAsync()` 와 같이 네이밍을 하면 네트워크 응답이 async구한 위의 같은 경우 Publisher구나 하고 명확히 알수있어서 휴먼 리소스가 줄어들수있을거같아요.

2024-01-09 11:00 UTC, jungseungyeo commented on ChatBot/ChatBot/Networks/HTTPPublisher/Implements/URLSession+HTTPPublishable.swift
> +                    return HTTPError.unknownError(description: error.localizedDescription)
제 개발 경험상 Error를 넘겨주고 View 단에서 error.localizedDescription를 처리하는게 추후에 에러처리를 하는데 있어서 용이 한 경우를 많이 경험을 하였습니다. 

View에서 errorHandler 함수를 만들고 (error: Error)를 받게하여 서버에서 추후에 어떤 변겨으로 메시지를 내려주던지 네트워크 단의 코드 수정없이 에러 핸드럴부분만 수정이 하는 코드가 작성하게 되게 하는게 좋더라구요. 
Error를 넘겨주게 수정을 한번 부탁드립니다.

2024-01-09 11:00 UTC, jungseungyeo commented on ChatBot/ChatBot/Networks/HTTPRequest/Implements/GPTBaseReqeust.swift
> +    final class GPTBaseReqeust: HTTPRequestable {
HTTPRequestable를 채택하는것이 class가 아닌 enum으로 변경하면 어떤가요?
enum으로 요청하는 이유는 도메인 단위 혹은 서비스 단위로 api를 하나의 뭉치기 위합니다.

예를 들어 class로 혜택하거나 struct로 채택을 하는 경우 Request당 하나의 객체가 생성되게 됩니다.
하지만 enum을 사용하게 된다면 case 별로 Request를 생성하여 서비스 단위로 api를 하나로 모아서 관리하기 용이하게 될 거같습니다.

2024-01-09 11:00 UTC, jungseungyeo commented on ChatBot/ChatBot/Networks/HTTPRequest/Protocols/HTTPRequestable.swift
> +    var headerFields: [String : String]? { nil }
너무 좋아요 꼭 필요하지 않는 부분이 아닐수있는것을 extension으로 nil 처리를 하여 채택을 하여도 매번 필요하지 않는 부분의 대해서 중복코드를 제거하였네요 ㅎㅎ 좋습니다.

2024-01-09 11:00 UTC, jungseungyeo commented on ChatBot/ChatBotTests/ChatBotTests.swift
> +    func test_코멘트_요청에_대한_인코딩이_제대로_되는지() throws {
네이밍이 한글이라 파악하게 편하네요 ㅎㅎ 저도 한글로 테스트코드 함수를 작성하는 편인데요. 인코딩이 되는지와 같은 의문형이 아닌 제대로 인코딩이 되면 무슨값이 나온다. 와 같이 명확하게 문장을 완성해주시면 좋아요. 

인코딩이 제대로 되는 경우 무슨 값이 나와야 하는지 추후에 유지보수하다보면 파악하기 어려워 지는 경우가 있더라구요. 명확히 파악할 수 있는 값을 명시하는게 유지보수 측면에서 좋은거같아 수정을 요청합니다.

2024-01-09 11:00 UTC, jungseungyeo commented on ChatBot/ChatBotTests/ChatBotTests.swift
> +                    //then
then을 잘 표현하여 좋습니다. 

위의 give when then을 지켜주고 있는데요. 명확히 //give // when //then 영역마다 주석을 달아주시면 더 좋을거같아요.

2024-01-09 11:00 UTC, jungseungyeo commented on ChatBot/ChatBotTests/Resources/GPTReplyMock.json
> +}
더미 json으로 구현하셨네요 ㅎㅎ 
좋습니다. ㅎㅎ

2024-01-10 06:50 UTC, newJunsung commented on ChatBot/ChatBot/Errors/Implements/HTTPError.swift
> +extension GPTError {
린생이 저번에 요청해주셔서 사용하고 있습니다!
네트워크 에러 뿐만이 아니라, 추후에 다양한 에러 타입을 한 곳에 모아둘 수 있어서 더 편할 것 같습니다.

2024-01-10 06:53 UTC, newJunsung commented on ChatBot/ChatBot/Networks/HTTPPublisher/Implements/URLSession+HTTPPublishable.swift
> +                    return HTTPError.unknownError(description: error.localizedDescription)
열거형 케이스의 매개변수(?)로 에러를 넣을 생각을 미처 하지 못했습니다.
좋은 팁 알려주셔서 감사합니다!

2024-01-10 06:57 UTC, newJunsung commented on ChatBot/ChatBotTests/ChatBotTests.swift
> +                    //then
수정 했습니다!

2024-01-10 07:01 UTC, newJunsung commented on ChatBot/ChatBot/Networks/HTTPPublisher/Implements/URLSession+HTTPPublishable.swift
> +    func publish(urlRequest: URLRequest) -> AnyPublisher<Data, GPTError.HTTPError> {
항상 변수 또는 함수의 네이밍이 어려운 것 같습니다...
좋은 네이밍 팁 정말 감사합니다!!!

2024-01-10 07:07 UTC, newJunsung commented on ChatBot/ChatBotTests/ChatBotTests.swift
> +    func test_코멘트_요청에_대한_인코딩이_제대로_되는지() throws {
수정했습니다!

2024-01-10 07:11 UTC, newJunsung commented on ChatBot/ChatBot/DataDecoder/Protocols/DataDecoderable.swift
> +    func decodeData<T: Decodable>(_ data: Data, to type: T.Type) throws -> T
만약 `NetworkService` 내부가 아닌 제네릭이 없는 다른 곳에서 사용해야할 경우,
```swift
decodeData<Model.UserMessage>(data)
```
이런 식으로 사용해야 합니다. 이는 오히려 `NetworkService`만 사용하다가 `DataDecodable` 프로토콜을 채택한 타입을 사용할 때 혼란을 줄 수 있으므로, 지금의 방식이 더 좋다고 생각합니다!

2024-01-10 12:23 UTC, jungseungyeo approved these changes
@newJunsung 님

고생하셨습니다. 피드백을 잘 적용해주신거같습니다. 오늘 디스코드에서 이야기 한 내용등을 
앞으로도 잘 고려하여 진행하면 좋을거같습니다.

감사합니다.

2024-01-10 12:23 UTC, merged

2024-01-10 12:24 UTC, newJunsung commented on ChatBot/ChatBot/Networks/HTTPRequest/Implements/GPTRequest.swift
열거형으로 수정했습니다. 
열거형으로 수정하니, 기존 Decoratorable을 차라리 빼는 게 나을 것 같다는 생각이 들어 해당 프로토콜 및 구현체를 삭제했습니다.