AI 챗봇 앱 [STEP 3] 뉴준성
tasty-code/ios-chat-bot pull request #19
Opened 2024-01-15 11:17 UTC by newJunsung

안녕하세요👋 린생(@jungseungyeo)! STEP3을 다 해서 PR을 올립니다. 확인해주시면 감사하겠습니다!

### To-do List
- 채팅방 UI 구현
- 채팅 풍선 Custom UI 구현 및 Animation 적용
- 채팅과 네트워크 서비스 연결

# STEP3 진행 중 경험 사항

## MVVM 시도

### ViewModel 프로토콜 및 구조체 구현
GPTChatRoom에 대한 뷰 모델의 프로토콜을 만들어 진행했습니다.
- GPTChatRoomVMProtocol.swift
```swift
import Combine

protocol GPTChatRoomVMProtocol {
    var chattings: [Model.GPTMessage] { get }
    var chattingsPublisher: Published<[Model.GPTMessage]>.Publisher { get }
    
    func sendComment(_ comment: GPTMessagable)
}
```
- GPTChatRoomViewModel.swift
```swift
final class GPTChatRoomViewModel: GPTChatRoomVMProtocol {
    private let httpService: HTTPServicable
    private let httpRequest: HTTPRequestable

    private var cancellables = Set<AnyCancellable>()

    @Published var chattings: [Model.GPTMessage]
    var chattingsPublisher: Published<[Model.GPTMessage]>.Publisher { $chattings }

    init(httpService: HTTPServicable, httpRequest: HTTPRequestable, chattings: [Model.GPTMessage]) {
        self.httpService = httpService
        self.httpRequest = httpRequest
        self.chattings = chattings
    }
    
    func sendComment(_ comment: GPTMessagable) {
        chattings.append(comment.asRequestMessage())
        let index = chattings.count
        chattings.append(Model.WaitingMessage().asRequestMessage())
        
        httpService.request(
            request: httpRequest,
            object: Model.GPTCommentDTO(messages: chattings.filter { $0.role != .waiting }),
            type: Model.GPTReplyDTO.self
        )
        .map { $0.choices.first?.message }
        .replaceNil(with: Model.AssistantMessage(content: "내용이 없습니다...", name: nil, toolCalls: nil).asRequestMessage())
        .sink { [weak self] completion in
            if case .failure(let error) = completion {
                self?.chattings[index] = Model.AssistantMessage(content: "\(error)", name: nil, toolCalls: nil).asRequestMessage()
            }
        } receiveValue: { [weak self] reply in
            self?.chattings[index] = Model.AssistantMessage(content: reply.content, name: nil, toolCalls: nil).asRequestMessage()
        }
        .store(in: &cancellables)
    }
}
```

### ViewController에서 바인딩
뷰모델의 chattings에 변경사항이 있으면, 뷰에서도 업데이트할 수 있도록
뷰모델의 퍼블리셔를 바인딩하게끔 만들었습니다.
- GPTChatRoomViewController.swift
```swift
final class GPTChatRoomViewController: UIViewController {
    // ...
    private func bind() {
        viewModel.chattingsPublisher
            .receive(on: DispatchQueue.main)
            .sink { [weak self] messages in
                guard let self else { return }
                
                var snapshot = NSDiffableDataSourceSnapshot<Section, Model.GPTMessage>()
                snapshot.appendSections([.main])
                snapshot.appendItems(messages)
                self.chattingDataSource.apply(snapshot)
                
                if !messages.isEmpty {
                    let indexPath = IndexPath(item: messages.count - 1, section: 0)
                    chatCollectionView.scrollToItem(at: indexPath, at: .top, animated: true)
                }
            }
            .store(in: &cancellables)
    }
}
```

2024-01-16 10:51 UTC, jungseungyeo requested changes
안녕하세요 뉴준성님
step3 하느라 고생하셨습니다.

해당 코드를 보면서 잘 적용이 된 거같습니다. 특히 Viewmodel을 적용하여 코드를 작업한 부분이 좋았습니다.

코드 리뷰에서 ViewModel에서 해야하는 역할을 View에서 하는 부분이 보여서 리뷰를 드렸습니다. view의 역할은 이벤트를 주고 이벤트를 받으면 처리하는 단순한 방식으로 구현이 되고 ViewModel을 이벤트가 오면 계산을 처리하고 이벤트를 방출하는 역할로 하면서 View를 모르는 구조가 되어야합니다.

ViewModel에서는 이벤트를 내부에서 처리를 하여 응집도를 높이고 private으로 내부 상태를 감추어 은닉화를 하여 결합도는 낮추는 코드로 작업이 진행이 되어야하여 이런 부분 또한 수정 요청을 드렸습니다.
리뷰 보시고 궁금한 점이 있으면 알려주세요 :)

2024-01-16 10:51 UTC, jungseungyeo commented on ChatBot/ChatBot/Application/SceneDelegate.swift
> +        window?.rootViewController = GPTChatRoomViewController(viewModel: viewModel)
ViewModel을 주입해주고 있네요!, 좋습니다. 

ViewModel을 생성할때 default값을 넣어주면 어떤가요? ViewModel을 init 할 때 많은 값을 넣어주고 있어서 호출하는 곳에서 코드가 길어지는거같아요.

2024-01-16 10:51 UTC, jungseungyeo commented on ChatBot/ChatBot/Application/SceneDelegate.swift
> +    func sceneDidEnterBackground(_ scene: UIScene) { }
코드 정리가 잘 되어 있네요 ㅎㅎ 좋습니다. 대부분 이렇게 정리하는 것을 챙기지 않는데요. 대부분 이런 부분까지 챙기는 분들이 코드도 잘 만드시는거같아요 ㅎㅎ

2024-01-16 10:51 UTC, jungseungyeo commented on ChatBot/ChatBot/Design/CustomUI/ChatBubble/UIChatBubbleView.swift
> +//    }
사용하지 않는 코드는 삭제해주세요

2024-01-16 10:51 UTC, jungseungyeo commented on ChatBot/ChatBot/Design/CustomUI/ChatBubble/UIChatBubbleView.swift
> +    var text: String? {
해당 기능은 오브젝트에서 말하는 데이터 은닉화를 위반하는 코드입니다.
하지만 이러한 형태는 UIKit 내부에서도 많이 사용하고 있죠? 이것은 그래도 은닉화를 하는것이 오브젝트 개념에서는 더 맞는거 같아, 데이터 은닉화를 하는 방식으로 변경을 요청드려요. 
현재 구조도 큰 이슈가 있어 보이지는 않지만 은닉화를 먼저 잘 적용 후 위와 같은 방식으로 적용해보시죠 ㅎㅎ

2024-01-16 10:51 UTC, jungseungyeo commented on ChatBot/ChatBot/Design/CustomUI/ChatBubble/UIChatBubbleView.swift
> +    var startDirection: StartDirection {
위의 text와 리뷰가 같아요. 이 부분도 데이터 은닉화를 적용해주세요

2024-01-16 10:51 UTC, jungseungyeo commented on ChatBot/ChatBot/Design/CustomUI/ChatBubble/UIChatBubbleView.swift
> +        bezierPath.close()
bezierPath로 그려서 적용하고 있어요 이부분들은 나중에 무엇을 그리는지 파악하기 힘들어지는 이슈가 있는데요 해당 코드마다 무엇을 그리는지 주석으로 기록을 하면 좋아요. 또 해당 영역마다 함수로 분리해도 좋습니다.
코드의 가독성을 위해서 주석을 달아주세요 :)

2024-01-16 10:51 UTC, jungseungyeo commented on ChatBot/ChatBot/Design/CustomUI/ChatBubble/UIChatBubbleView.swift
> +        bezierPath.close()
물론 역할한거겠지만.. 그 안에서 어떻게 그리는지 표현하면 좋습니다.

2024-01-16 10:51 UTC, jungseungyeo commented on ChatBot/ChatBot/Design/CustomUI/ChatBubble/UIChatBubbleView.swift
> +        bezierPath.close()
아니면 extension으로 내부를 감추어는 것도 좋습니다. 

``` swift
extesnion UIBezierPath {
  func drawLeftChatBubble(width: Double, height: Double)
}
```

위와 같이 작성을 된다면 외부에서 접근시 `bezierPath.drawLeftChatBubble()`로 구현이 되겁니다. 더욱 코드의 가독성이 좋아질거같아요.

2024-01-16 10:51 UTC, jungseungyeo commented on ChatBot/ChatBot/Presentation/GPTChatRoom/ViewController/GPTChatRoomViewController.swift
> +                }
위의 코드는 뷰모델에서 시점을 보내줘야 가독서잉 높아질거같아요.

여기서 apply가 끝나면 이벤트를 ViewModel로 전달을 하고 다시 scroll 이벤트를 받는 viewModle publisher로 구현을 해주면
View에서는 요청이 오면 동작이 되는 코드가 완성이 되어 비지니스 로직과 view의 코드가 분리 될거같아요.

2024-01-16 10:51 UTC, jungseungyeo commented on ChatBot/ChatBot/Presentation/GPTChatRoom/ViewController/GPTChatRoomViewController.swift
> +    private func setViews() {
네이밍을 주로 setViews라기 보다는 configureUI()라는 네이밍을 주로 사용하는 편입니다. 이건 개인취향이긴하지만 주로 회사를 다니면서 코드를 보면 configure()로 많이 사용하는거같아요. ( 꼭 수정을 안하셔도 됩니다.)

2024-01-16 10:51 UTC, jungseungyeo commented on ChatBot/ChatBot/Presentation/GPTChatRoom/ViewController/GPTChatRoomViewController.swift
> +        commentTextView.text = nil
이벤트를 줄지 말지 view에서 계산을 하고 있어요 이러면 안됩니다 ViewModel이 존재를 하면 이벤트를 일단 VIewModel로 넘겨서 역할을 확실하게 가져가는 편이 좋습니다. 너는 곳은 View에서 시점을 잡아서 이벤트를 주고 안주고 이러면 안되고 이벤트가 오면 view주고 게산은 viewModel한 다음 넘기는 방식으로 처리를 하면 좋습니다.

2024-01-16 10:51 UTC, jungseungyeo commented on ChatBot/ChatBot/Presentation/GPTChatRoom/ViewModel/Implements/GPTChatRoomViewModel.swift
> +    @Published var chattings: [Model.GPTMessage]
데이터를 외부에서도 set을 하룻 있어요 이렇게 코드가 작성이 된다면 어디서 이벤트를 주는지 몰라 결합도가 높아지게 됩니다.
결합도를 낮추기 위해서는 데이터를 은닉화를 하여 처리하면 좋습니다. private(set)을 적용해주세요.

2024-01-17 02:25 UTC, newJunsung commented on ChatBot/ChatBot/Design/CustomUI/ChatBubble/UIChatBubbleView.swift
> +
`private`를 통해서 은닉화를 하고, 함수를 통해 값을 할당하게끔 바꿨습니다.
그리고 은닉화를 하면 내부 프로퍼티 `text`의 쓸 이유가 굳이 있다고 생각하지 않아서,
해당 프로퍼티 또한 삭제했습니다.

2024-01-17 02:43 UTC, newJunsung commented on ChatBot/ChatBot/Design/CustomUI/ChatBubble/Extension/BezierPath+extension.swift
> +    func drawRightChatBubble(width: Double, height: Double) {
https://github.com/tasty-code/ios-chat-bot/pull/19#discussion_r1453240014
`extension`을 통해서 내부에 말풍선을 그리는 함수를 구현했습니다.

2024-01-17 02:44 UTC, newJunsung commented on ChatBot/ChatBot/Presentation/GPTChatRoom/ViewModel/Implements/GPTChatRoomViewModel.swift
> +    @Published var chattings: [Model.GPTMessage]
적용했습니다.

2024-01-17 02:47 UTC, newJunsung commented on ChatBot/ChatBot/Application/AppEnviroment.swift
> +}
AppEnviroment 라는 구조체를 만들어서,
자주 쓰일 것으로 예상되는 타입들을 기본 구현했습니다.
보통 JSON 디코딩 인코딩의 경우 자주 쓰이기에,
JSON을 인코딩 디코딩을 하는 `HTTPService`를  정적 타입으로 구현했습니다.

2024-01-17 02:47 UTC, newJunsung commented on ChatBot/ChatBot/Presentation/GPTChatRoom/ViewModel/Implements/GPTChatRoomViewModel.swift
> +    init(httpService: HTTPServicable = AppEnviroment.defaultHTTPSecvice, httpRequest: HTTPRequestable, chattings: [Model.GPTMessage] = []) {
`AppEnviroment`의 `defaultHTTPSecvice`를 기본값으로 설정했습니다.

2024-01-17 03:41 UTC, newJunsung commented on ChatBot/ChatBot/Presentation/GPTChatRoom/ViewController/GPTChatRoomViewController.swift
> +                }
ViewModel에 `PassThroughSubject`를 추가해서 비지니스 로직을 분리했습니다.

2024-01-17 03:43 UTC, newJunsung commented on ChatBot/ChatBot/Presentation/GPTChatRoom/ViewController/GPTChatRoomViewController.swift
> +    }
인덱스로 이동하는 로직을 뷰 모델로 옮기고 바인딩을 통해 옮겨가도록 변경했습니다.

또한 에러에 대해서 Alert를 띄우는 기능을 추가해보았습니다.

2024-01-17 03:45 UTC, newJunsung commented on ChatBot/ChatBot/Presentation/GPTChatRoom/ViewController/GPTChatRoomViewController.swift
> +        commentTextView.text = nil
리뷰를 보고 수정하면서,
해당 로직을 뷰에 두었을 때 기능이 추가될수록 뷰 컨트롤러가 비대해질 수도 있다는 사실을 알게 되었습니다.

2024-01-17 12:48 UTC, jungseungyeo commented on ChatBot/ChatBot/Presentation/GPTChatRoom/ViewController/GPTChatRoomViewController.swift
> +                }
PassThroughSubject로 구성을 하기 보다는 Anypublihser로 이벤트를 전달하면 좋습니다.
PassThroughSubject로 하는 경우 viewcontroller에서 send를 보낼수있기 때문에 이벤트는 받을수만 있는 구조하면좋습니다.

``` swift
private let subject = PassThroughSubject<Value, Error>()
var publisher: AnyPublisher<Value, Error> {
   return subject.eraserpublisher
}
```

2024-01-17 12:50 UTC, jungseungyeo commented on ChatBot/ChatBot/Presentation/GPTChatRoom/ViewController/GPTChatRoomViewController.swift
> +    }
너무 좋아요 ㅎㅎ

2024-01-17 12:51 UTC, jungseungyeo approved these changes
고생했습니다. 뉴준성 다음 스텝으로 진행부탁드려요

2024-01-17 12:51 UTC, merged