AI 챗봇 앱 [Step 3] 쫑, Swain
tasty-code/ios-chat-bot pull request #21
Opened 2024-01-19 13:21 UTC by shlim0

# AI 챗봇 앱 [Step 3] 쫑, Swain

* 리뷰어: @corykim0829

## 팀원 :busts_in_silhouette: 
| 프로필 사진 | <a href="https://github.com/shlim0"><img src="https://avatars.githubusercontent.com/u/46235301?v=4" width=90></a> | <a href="https://github.com/shlim0"><img src="https://avatars.githubusercontent.com/u/99116619?v=4" width=90></a> |
| ---- | ---------- | --------- | 
| in Github | [@JJong](https://github.com/shlim0) | [@Remaked-Swain](https://github.com/Remaked-Swain)
| in SeSAC | 쫑 | 스웨인

-------------
## 사용 경험
- [x] `UICollectionView`
- [x] `DiffableDataSource`
- [x] `UICollectionViewCompositionalLayout`
- [x] Modern Cell Configuration - `defaultContentConfiguration()` 대신 CustomConfiguration으로 구현
- [x] `CALayer`, `CAReplicatorLayer` - 말풍선, 로딩표시

-------------
## 구현 사항
* 네트워킹 기능을 활용한 대화 화면을 구현하기
    * 말풍선 그리기
        * 채팅 크기만큼 동적으로 나타나도록 구현
    * 메세지 응답 수신 대기
        * 로딩중을 알리는 애니메이션 구현
        * 메시지를 수신하기 전까지 사용자 입력 방지
    * 대화창 스크롤 시 키보드 숨기기
        * 채팅 입력시 마지막 말풍선이 오도록 키보드를 배치
    * 응답 수신 간 문제 발생 시 적절히 알리기
        * 에러 유형별로 알림

## 실행 화면 스크린샷
- 아이폰 15 Pro

| 채팅 화면 | 긴 채팅 | 동적 입력창 |
|:-------:|:-------:|:-------:|
| <img src="https://github.com/tasty-code/ios-chat-bot/assets/46235301/2cdae929-1ea2-4746-908b-4d86f2fb5da9" alt="chat" width="240px"> |  ![2  long story](https://github.com/tasty-code/ios-chat-bot/assets/46235301/bd68cc95-0d2f-45db-8c2c-e4a9dcd83967) |  ![3  keyboard and dynamic text view](https://github.com/tasty-code/ios-chat-bot/assets/46235301/8307a587-0b50-4d40-87ad-8f7a87d9c57d) |

| 사용자 입력시 화면이 이동 | 에러 발생 후 채팅 재요청 |
|:-------:|:-------:|
|  ![4  push blue message](https://github.com/tasty-code/ios-chat-bot/assets/46235301/12c1b3b9-f12d-47e8-9bbf-b221dad68b42) |  ![5  error but still execution](https://github.com/tasty-code/ios-chat-bot/assets/46235301/cf4b6ade-ecd6-40e4-9230-7048b3b46b9c) |

| Network Error | Server-side Error | Unknown Error |
|:-------:|:-------:|:-------:|
|  ![network error](https://github.com/tasty-code/ios-chat-bot/assets/46235301/e42c9e71-4554-4958-a697-2c0c8b941311) |  ![server error](https://github.com/tasty-code/ios-chat-bot/assets/46235301/619de5d8-d905-4332-92f4-95c6e2bcd33d) |  ![unknown error](https://github.com/tasty-code/ios-chat-bot/assets/46235301/f8d1d12e-ca4d-4ce8-85ea-fd9efcb55178) |

- 아이패드 6세대 Pro (12.9)
![아이패두](https://github.com/tasty-code/ios-chat-bot/assets/46235301/36839f27-d72e-4f8a-b119-5e29f59333af)

-------------

### Cell Configure
- `ChattingRoomView: UICollectionView`의 Cell은 `MessageCellContentConfiguration: UIContentConfiguration`구조체를 사용해 정의 및 표현했습니다.
- Cell을 표현하기 위해 필요한 정보는 `BubbleLabel`로 나타낼 문자열과 메세지의 종류를 분간할 수 있는 `Role`타입이 필요했기에 커스텀 구현하게 되었습니다.
- 덕분에 Cell이 구성되는 방법을 외부에서는 모르게, 내부에서 자연스레 이루어지도록 연결하는 것에 집중하면서 [Modern Cell Configuration](https://developer.apple.com/documentation/uikit/views_and_controls/collection_views/implementing_modern_collection_views)의 의미를 이해해보려 노력했습니다.

- 전반적인 hierarchy는 다음과 같습니다.
- `ChattingRoomViewController: UIViewController`
    - `chattingRoomView: UICollectionView`
        - `MessageCell: UICollectionViewCell`
            - `MessageCellConfiguration: UIContentConfiguration, Hashable` 
              `MessageCell`에 대한 설정을 합니다.
            - `MessageCellContentView: UIView, UIContentView`
              `MessageCell`에 대한 실질적인 뷰입니다.
                - `MessageView: UIView`
                    - `bubbleLayer: CAShapeLayer`
                       말풍선을 그리는 layer입니다.
                    - `MessageViewConfiguration: UIContentConfiguration, Hashable`
                      `MessageView`에 대한 설정을 합니다.
                    - `MessageContentView: UIView, UIContentView`
                      `MessageView`에 대한 실질적인 뷰입니다.
                      - `bubbleLabel: UILabel`
                      - `dotLayer: CAReplicatorLayer`
                         Loading Indicator(로딩중)을 나타내는 애니메이션을 구현하는 layer입니다.
                      
            
![image](https://hackmd.io/_uploads/BJmzCkuFT.png)

-------------
## 궁금한 점

### 뷰 구조 개선
1. `UICompositionalLayout`으로 대화 화면을 구성해보았는데 메세지 종류에 따라 정렬하는 방향을 다르게 하는 것이 굉장히 어려웠습니다.
2. 말풍선레이어와 Loading Indicator(로딩중)를 그릴 때 적절한 위치를 찾기가 힘들었습니다. 자체적으로 복잡하게 계산한 위치를 주지 않고 간편하게 Background에 그릴 수 있도록 `UIContentConfiguration`과 `ContentView`, 그리고 `UIBackgroundConfiguration`을 활용한 방식을 최대한 시도해보려고 노력했습니다.
3. 애매하게 맞지 않는 말풍선과 인디케이터, 그리고 문자열의 위치를 최대한 간편하게 맞추기 위해 `UIContentConfiguration`을 활용, 내부 ContentView를 구성해 Autolayout을 자동으로 맞춰주는 것으로 문제 해결을 시도했습니다.

결과적으로, 상위 뷰의 `Configuration`변화로 하위 뷰들의 Data-driven을 연쇄적으로 촉발시킬 수 있게 되었습니다. 하지만 파일과 코드들이 매우 조잡해보이는 느낌을 지울 수 없었습니다.

### Autolayout Performance
WWDC 세션(WWDC 18 - High Performance Auto Layout)에서는 Auto Layout Constraints에 대해 엔진이 같은 연산을 계속 수행하며 성능을 저하시키지 않도록 제약사항을 부수고 다시 짓는 로직을 피해야 한다고 말하고 있습니다.

위와 관련해 저희는 최대한 Auto Layout를 active 및 deactivate 하기 보다, 비용 측면에서 유리한 방식으로 진행해보자는 의견으로 모아졌고 여러 방법을 시도해보았으나, 결국 한계에 부딪혀 개선하지 못했습니다.

저희가 시도한 내용은 다음과 같습니다.
1. `UIEdgeMargin`을 주어 메세지 Role에 따라 좌, 우로 밀어 정렬하기.
> 좌측 정렬에는 문제가 없었으나 우측 정렬 및 짧은 메세지일 경우, 글자가 가운데 동떨어져 나오는 문제 때문에 기각.
2. `setNeedsLayout()` 메서드 오버라이딩으로 Margin 주기
> 위와 같은 문제로 기각.
3. `semanticAttribute` 속성을 메세지 Role에 따라 `.forceLeftToRight`, `.forceRightToLeft`로 바꾸어 주기
> 해결은 됐으나 결국 Autolayout도 잡아줘야 하므로 Best Solution은 아니었음.
4. `CellRegistration`을 2개 등록해서 Reusing하기
> 구현은 성공했으나 Registration Provider의 코드가 `cell.message = item`으로 동일한데, 동일한 등록을 2개 해주어야 한다는게 우리는 마음에 들지 않았음.

코리는 어떻게 생각하시나요?

-------------

### 회고
* `ChattingRoomViewController`의 Data-driven 관련 로직을 일부 가져ㄱ줄 ViewModel이 있어도 괜찮을 것 같다.
    * ViewController로써 역할이 많아 무거워졌기 때문이다.
    * 예시. `ChattingRoomViewModel`(NetworkManager 포함...)

2024-01-23 13:09 UTC, corykim0829 requested changes
수고 많으셨습니다!

UICollectionView를 UICollectionViewDiffableDataSource를 사용해서 잘 구현해주셨고,
말풍선이나 로딩 같은 것도 모두 직접 구현하신게 멋집니다! 👍👍👍

> 뷰 구조 개선

UIContentConfiguration을 활용해서 어쩔 수 없이 코드가 조금 많아지는 부분이 있는데요.
개인적으로는 MessageCellContentView에서 또 MessageView를 따로 처리하지 않고 한번에 구현해보면 조금 덜 복잡해보일 것 같습니다.

> Autolayout Performance

현재 구현하신 방법이 Auto layout을 제거하고 다시 생성하지 않고 active, deactive하고 있기 때문에 성능적으로 큰 문제가 없어보입니다!

그런데 4번에 CellRegistration을 2개 등록해서 Reusing하기 현재 구현하신 방법은 아니고, 시도해보신 방법을 뜻하시는건가요?

4번 방법도 모델은 같지만 뷰가 다른 부분이 있어서 두개의 Cell 나누는 것도 좋은 방법이라고 생각합니다!

커멘트에서 한번 언급했지만, guard 문을 사용할 때 return 부분이 잘 보이도록 개행 해주는게 좋을 것 같습니다.

또한 다른 부분에서도 너무 한줄로 구현하려는 부분들이 보이는데 한 줄로 구현하면 다른 사람이 보기에는 복잡해 보이기 때문에 개행을 많이해서 가독성을 높여주면 좋을 것 같습니다!

2024-01-23 13:09 UTC, corykim0829 commented on ChatBot/ChatBot/ChattingRoomListView/ViewController/ChattingRoomListViewController.swift
> +    private lazy var chattingRoomListView: UICollectionView! = {
여기에서 `!`를 사용한 이유가 있을까요?

2024-01-23 13:09 UTC, corykim0829 commented on ChatBot/ChatBot/ChattingRoomListView/ViewController/ChattingRoomListViewController.swift
> +    private let networkManager: NetworkRequestable!
여기에도 모두 `!` 사용하셨는데, 이유가 궁금합니다!

2024-01-23 13:09 UTC, corykim0829 commented on ChatBot/ChatBot/ChattingRoomView/ViewController/ChattingRoomViewController.swift
> +    private lazy var chattingRoomView: UICollectionView! = {
type에 !를 붙이지 않아도 될 것 같아요. 아래 다른 뷰 클래스들도 마찬가지로요

2024-01-23 13:09 UTC, corykim0829 commented on ChatBot/ChatBot/ChattingRoomView/ViewController/ChattingRoomViewController.swift
> +    private var snapshot: Snapshot! = Snapshot()
여기도 타입을 정리해주면 좋을 것 같아요!

2024-01-23 13:09 UTC, corykim0829 commented on ChatBot/ChatBot/ChattingRoomView/ViewController/ChattingRoomViewController.swift
> +    private func hasWhitespacesAndNewlines(_ content: String) {
잘 구현하셨는데, 함수명을 보면 Bool 값을 리턴할 것 같아서 수정하면 좋을 것 같습니다.

2024-01-23 13:09 UTC, corykim0829 commented on ChatBot/ChatBot/ChattingRoomView/ViewController/ChattingRoomViewController.swift
> +    private func prepareToSend(_ messages: [Message], to gptModel: GPTModel) -> NetworkRequestBuilderProtocol {
함수명이 반환값이 없을 것 같이 읽히네요! 수정하면 좋을 것 같아요

2024-01-23 13:09 UTC, corykim0829 commented on ChatBot/ChatBot/ChattingRoomView/ViewController/ChattingRoomViewController.swift
> +        snapshot.deleteItems([lastItem])
이 부분은 로딩 말풍선을 지우는 코드인가요?

2024-01-23 13:09 UTC, corykim0829 commented on ChatBot/ChatBot/ChattingRoomView/ViewController/ChattingRoomViewController.swift
> +    private func reloadCurrentDataSource(with message: Message) {
위 updateDataSource와 여기 함수가 하는 일이 비슷해서, 합쳐서 처리할 수 있을 것 같아요.
또한 이 함수에서도 scrollToBottom 함수를 호출해야하지 않을까요?

2024-01-23 13:09 UTC, corykim0829 commented on ChatBot/ChatBot/ChattingRoomView/ViewController/ChattingRoomViewController.swift
> +        else { return }
guard ~ else 까지 한줄로 처리하고 return 을 확실하게 볼 수 있게 다음과 같이 개행 처리해주는게 좋은 것 같아요.
예외 처리가 되는 부분을 잘 볼 수 있어서요!
```suggestion
        guard itemsCount > 0, sectionCount > 0 else {
            return
        }

2024-01-23 13:09 UTC, corykim0829 commented on ChatBot/ChatBot/ChattingRoomListView/ViewController/ChattingRoomListViewController.swift
> +    private typealias Snapshot = NSDiffableDataSourceSnapshot<Section, Item>
여기 ViewController에서는 UICollectionViewDiffableDataSource를 사용하지 않아서 필요한 것 같지 않아보이는데, 선언하신 이유가 있을까요?

2024-01-23 13:09 UTC, corykim0829 commented on ChatBot/ChatBot/ChattingRoomListView/ViewController/ChattingRoomListViewController.swift
> +extension ChattingRoomListViewController {
여기도 필요한 부분인지 의문이 듭니다!

2024-01-23 13:09 UTC, corykim0829 commented on ChatBot/ChatBot/ChattingRoomView/Model/MessageCellConfiguration.swift
> +    var role: Role? = nil
타입을 옵셔널로 선언하면 nil을 굳이 사용하지 않아도 자동으로 초기값이 nil로 지정됩니다. 참고하세요!

2024-01-23 13:09 UTC, corykim0829 commented on ChatBot/ChatBot/ChattingRoomView/View/MessageView.swift
> +        let bezierPath = UIBezierPath()
bezierPath로 말풍선을 정말 훌륭하게 잘 구현하셨습니다! 👏👏👏👏

2024-01-23 13:09 UTC, corykim0829 commented on ChatBot/ChatBot/ChattingRoomView/ViewController/ChattingRoomViewController.swift
> +        let _ = textView.layoutManager.usedRect(for: textView.textContainer)
이 부분은 현재 어떻게 사용되고 있나요?

2024-01-23 13:09 UTC, corykim0829 commented on ChatBot/ChatBot/ChattingRoomView/ViewController/ChattingRoomViewController.swift
> +    func textViewDidChange(_ textView: UITextView) {
textView의 text가 변경될 때 UI 업데이트 처리를 깔끔하게 잘 구현하셨습니다! 👍

2024-01-23 13:09 UTC, corykim0829 commented on ChatBot/ChatBot/ChattingRoomView/View/MessageCellContentView.swift
> +    private var trailing: NSLayoutConstraint? = nil
두 프로퍼티명 뒤에 Constraint라고 붙여주면 확실하게 어떤 객체인지 알 수 있을 것 같아요.
또한 nil은 처음에 선언하지 않아도 되니 참고해주세요!

2024-01-24 01:55 UTC, Remaked-Swain commented on ChatBot/ChatBot/ChattingRoomView/ViewController/ChattingRoomViewController.swift
> +    private func hasWhitespacesAndNewlines(_ content: String) {
Bool 타입 반환이 예상되는 네이밍 대신, String을 조건에 맞게 Trimming(재단)한다는 함수의 동작 목적에 맞춰
`trimContentInWhitespaceAndNewLines(_:)` 라는 네이밍으로 변경하였습니다.

네이밍만으로도 알아보기 좋은 메서드가 되었습니다!

2024-01-24 02:03 UTC, shlim0 commented on ChatBot/ChatBot/ChattingRoomListView/ViewController/ChattingRoomListViewController.swift
> +    private lazy var chattingRoomListView: UICollectionView! = {
`@IBOutlet view: UIView!` 처럼 무조건 사용될 것이라 확신하는 경우 `!`를 사용하는 것이 성능 상 더 좋다고 알고 있었습니다.
그러나, [Implicitly Unwrapped Optional](https://docs.swift.org/swift-book/documentation/the-swift-programming-language/thebasics/#Implicitly-Unwrapped-Optionals)와 [Unowned References and Implicitly Unwrapped Optional Properties](https://docs.swift.org/swift-book/LanguageGuide/AutomaticReferenceCounting.html#ID55)를 확인해 봤을 때, 상속하는 경우 two-phase initialization 시 편리 하다는 것을 제외하고, 큰 성능상 이점이 없다고 판단했습니다.

물론, `if-let`이나 `guard-let`으로 optional binding을 하지 않아도 되는 편리함은 있으나, `unowned`처럼 잘못 관리하면 App이 run-time시 crash 발생할 수 있기 때문에 지양하는 것이 낫다고 생각해 수정하겠습니다!


추가로, 아래 달아주신 코멘트를 보면 `private var dataSource: DataSource! = nil`와 같이 `nil`로 초기화한 구문이 있는데, 굳이 값을 할당하지 않아도 기본값으로 `nil`이 할당되는 만큼 다소 불필요한 코드가 있는 것도 확인했습니다.

2024-01-24 02:03 UTC, shlim0 commented on ChatBot/ChatBot/ChattingRoomListView/ViewController/ChattingRoomListViewController.swift
> +    private let networkManager: NetworkRequestable!
https://github.com/tasty-code/ios-chat-bot/pull/21#discussion_r1464209603 와 같습니다!

2024-01-24 02:04 UTC, shlim0 commented on ChatBot/ChatBot/ChattingRoomView/ViewController/ChattingRoomViewController.swift
> +    private lazy var chattingRoomView: UICollectionView! = {
https://github.com/tasty-code/ios-chat-bot/pull/21#discussion_r1464209603 와 같습니다!

2024-01-24 02:07 UTC, Remaked-Swain commented on ChatBot/ChatBot/ChattingRoomView/ViewController/ChattingRoomViewController.swift
> +    private var snapshot: Snapshot! = Snapshot()
snapshot의 경우는 최초 초기화 시점부터 사용하는 도중에 nil이 될 일이 없으므로 Implicit optional Unwrapping을 제거했습니다.
dataSource의 경우는 최초 초기화 시점에는 nil 값이며 `viewDidLoad()` 과정에서 초기화가 이루어지므로 Optional 처리했습니다.

2024-01-24 02:18 UTC, Remaked-Swain commented on ChatBot/ChatBot/ChattingRoomView/ViewController/ChattingRoomViewController.swift
> +    private func prepareToSend(_ messages: [Message], to gptModel: GPTModel) -> NetworkRequestBuilderProtocol {
메세지 전송 전 준비 단계라는 점을 생각하여 `prepareToSend()` 라는 네이밍을 사용했으나, 반환값이 있다는 점을 표현하지는 못했습니다.
빌더를 갖춘다는 의미에서, `initiializeBuilder()` 로 수정하였습니다. 또한 Parameter label로 자연스레 읽히는 방안까지 고민해볼 수 있었습니다.

2024-01-24 08:13 UTC, Remaked-Swain commented on ChatBot/ChatBot/ChattingRoomView/ViewController/ChattingRoomViewController.swift
> +    private func reloadCurrentDataSource(with message: Message) {
함수의 동작이 비슷해진 원인은 역할을 모호하게 인지하고 있었기 떄문이라고 생각합니다.
다음과 같이 재정비하였습니다.
```swift
private func initializeDataSource(with messages: [Message?]) {
    let items: [Item] = messages.compactMap { message in
        guard let message = message else { return nil }
        return Item(message: message)
    }
    
    self.snapshot = Snapshot()
    snapshot.appendSections(Section.allCases)
    snapshot.appendItems(items)
    dataSource?.apply(snapshot, animatingDifferences: true)
    
    scrollToBottom(itemsCount: snapshot.numberOfItems, sectionsCount: snapshot.numberOfSections)
}

private func appendItemToDataSource(with message: Message) {
    let item = Item(message: message)
    
    snapshot.appendItems([item])
    dataSource?.apply(snapshot, animatingDifferences: true)
    
    scrollToBottom(itemsCount: snapshot.numberOfItems, sectionsCount: snapshot.numberOfSections)
}

private func reconfigureCurrentDataSource(with message: Message) {
    guard let lastItem = snapshot.itemIdentifiers.last else { return }
    let newItem = lastItem.changeData(with: message)
    snapshot.reconfigureItems([newItem])
    dataSource?.apply(snapshot, animatingDifferences: true)
    messageTextView.isEditable = true
}
```

* `initializeDataSource()` - snapshot과 dataSource를 한번에 설정합니다. 이 컨트롤러 및 뷰가 최초로 등장할 때 이 메서드를 사용합니다.
* `appendItemToDataSource()` - 메세지 하나가 추가되었을 때 그것을 snapshot, dataSource로 반영합니다.
* `reconfigureCurrentDataSource()`  - ChatGPT로부터 메세지를 비동기적으로 수신하였을 때 dataSource에 이 변경사항을 반영합니다.

2024-01-24 08:33 UTC, shlim0 commented on ChatBot/ChatBot/ChattingRoomView/ViewController/ChattingRoomViewController.swift
> +        snapshot.deleteItems([lastItem])
지금 구조는 `deleteItems()` 호출 후, `appendItems()`를 실행하는 코드입니다.

기존에 생각했던 코드는 기존 아이템의 message를 바꾸고 dataSource를 갱신하는 방식을 생각했었는데요. 
```swift
// ChattingRoomViewController.swift
lastItem.message = message
snapshot.reloadItems([lastItem])

dataSource.apply(snapshot, animatingDifferences: true)
```

configuration 내부에서 로딩을 띄어주는 여부를 message가 있는지 없는지에 따라 toggle 해주고 있습니다.
```swift
// MessageContentView.swift
dotLayer.isHidden = configuration.role == .user || (configuration.text?.isEmpty == false)
```

다만,  `dataSource.apply()`는 `item`의 `id`(uuid)이 변경되어야 toggle 되어 말풍선이 사라지게 됩니다. 

따라서, `struct Item`의 `id`와 `message`가 `let` -> `var`로 변경해야 하고 다음과 같은 코드가 수반되어야 합니다.

```swift
lastItem.id = UUID().uuidString
lastItem.message = message

snapshot.reloadItems([lastItem])
```

다만, 이렇게 되면 기존 `id`가 변경되어 런타임 에러가 발생하기 때문에 (ttempted to reload item identifier that does not exist in the snapshot) 불가피하게 `deleteItems()` 후 `appendItems()`을 호출하여 로딩시의 메시지를 삭제하고 GPT의 메시지를 불러오도록 하고 있습니다.

2024-01-24 08:35 UTC, shlim0 commented on ChatBot/ChatBot/ChattingRoomView/ViewController/ChattingRoomViewController.swift
> +        else { return }
다음 step에 반영하겠습니다!

2024-01-24 08:40 UTC, Remaked-Swain commented on ChatBot/ChatBot/ChattingRoomView/ViewController/ChattingRoomViewController.swift
> +    private func prepareToSend(_ messages: [Message], to gptModel: GPTModel) -> NetworkRequestBuilderProtocol {
"?", "!" 로 표시된 타입은 우선 nil로 간주됩니다. nil로 초기화한다는 것을 눈에 띄게 작성해두려 했는데 이는 struct 멤버와이즈를 사용할 수 있으니까 의미가 없는 것 같기도 합니다. 해당 부분은 코드량을 줄인다는 생각으로 모두 정리해두었습니다~!

2024-01-24 08:55 UTC, Remaked-Swain commented on ChatBot/ChatBot/ChattingRoomView/Model/MessageCellConfiguration.swift
> +    var role: Role? = nil
"?", "!" 로 표시된 타입은 우선 nil로 간주됩니다. nil로 초기화한다는 것을 눈에 띄게 작성해두려 했는데 이는 struct 멤버와이즈를 사용할 수 있으니까 의미가 없는 것 같기도 합니다. 해당 부분은 코드량을 줄인다는 생각으로 모두 정리해두었습니다~!

2024-01-24 08:58 UTC, Remaked-Swain commented on ChatBot/ChatBot/ChattingRoomView/View/MessageCellContentView.swift
> +    private var trailing: NSLayoutConstraint? = nil
네이밍 자체에 NSLayoutConstraint 타입이라는 점이 드러나도록 "Constraint" 라고 붙여두었습니다.
또한 위와 같은 이유로 nil을 대입해주는 코드를 정리하였습니다!

2024-01-24 09:00 UTC, Remaked-Swain commented on ChatBot/ChatBot/ChattingRoomListView/ViewController/ChattingRoomListViewController.swift
> +    private typealias Snapshot = NSDiffableDataSourceSnapshot<Section, Item>
Step4 구현 단계에서 다시 UICollectionView로 구현할 예정이어서 동일한 구조로 스케치 해둔다는 것이 이번 PR 커밋으로 섞여들어간 것 같습니다.
이외에 특이사항은 없습니다!

2024-01-24 09:01 UTC, Remaked-Swain commented on ChatBot/ChatBot/ChattingRoomListView/ViewController/ChattingRoomListViewController.swift
> +extension ChattingRoomListViewController {
https://github.com/tasty-code/ios-chat-bot/pull/21#discussion_r1464548392
이것 역시 위와 같은 사유입니다.

2024-01-24 09:05 UTC, shlim0 commented on ChatBot/ChatBot/ChattingRoomView/ViewController/ChattingRoomViewController.swift
> +        let _ = textView.layoutManager.usedRect(for: textView.textContainer)
`textView`의 높이를 제한해두지 않고 계속 늘어날 수 있게 하여 계속 입력받을 수 있게 하였습니다. 다만, 화면에서 textView가 차지하는 영역을 무한정 늘릴 수는 없기 때문에, 크기를 고정해두고 계속 스크롤 할 수 있게끔 하였습니다. 

`textView.layoutManager.usedRect(for: textView.textContainer)`는 return value을 따로 쓰지 않았는데 작성한 이유는 사용자가 텍스트를 입력하다 지우는 상황(PR 내용 중, 실행화면 스크린 샷 - 동적 입력창에서 지우는 상황을 참고해주세요)에 `textView`의 높이가 동적으로 줄어들게끔 하기 위한 코드입니다. `layoutmanager`가 `textView`의 크기가 바뀔 때 마다 변화를 감지하고 레이아웃을 다시 계산하는 것으로 알고 있습니다.

요약하면, `textView`의 layout을 동적으로 조절하기 위한 코드입니다. 혹시 틀린 내용이 있다면 코멘트 부탁드립니다.

_(cf. WWDC13 - Advanced Text Layouts and Effects with Text Kit)_

2024-01-25 07:47 UTC, corykim0829 approved these changes
수고 많으셨습니다!!

다음 스텝 진행하시면서 제가 커멘트 남긴 부분 같이 이야기 하면 좋을 것 같습니다!

2024-01-25 07:47 UTC, corykim0829 commented on ChatBot/ChatBot/ChattingRoomView/ViewController/ChattingRoomViewController.swift
> +        let _ = textView.layoutManager.usedRect(for: textView.textContainer)
입력창에서 지우는 경우에는 이 함수 하단에 textView constraints를 처리하는 곳에서 처리가 되지 않는건가요?

2024-01-25 07:47 UTC, merged