AI 챗봇 앱 [STEP 4] 뉴준성
tasty-code/ios-chat-bot pull request #24
Opened 2024-01-22 10:24 UTC by newJunsung

안녕하세요👋 린생(@jungseungyeo)! STEP4을 다 해서 PR을 올립니다. 확인해주시면 감사하겠습니다!

### To-do List
- CoreData 모델 구현
- 타입 별(Chat Room, Chatting) CoreData Repository 구현
- 채팅 방 목록 구현
- 채팅 방 목록 CRUD
- 채팅 내역 목록 fetch

# 시현 영상
| 채팅 방 생성, 수정, 삭제하기 | 에러 시 알림 띄우기 | 채팅 내역 불러오기, 저장하기 |
| ---- | ---- | ---- |
| ![Simulator Screen Recording - iPhone 15 Pro - 2024-01-22 at 18 40 27](https://github.com/tasty-code/ios-chat-bot/assets/107932188/92e14c27-d62b-4359-bf53-330e0eacf2f8) | ![Simulator Screen Recording - iPhone 15 Pro - 2024-01-22 at 18 54 49](https://github.com/tasty-code/ios-chat-bot/assets/107932188/eeec240c-3b08-409a-a9e6-c8decd1d43f1) | ![Simulator Screen Recording - iPhone 15 Pro - 2024-01-22 at 18 44 19](https://github.com/tasty-code/ios-chat-bot/assets/107932188/de06ee86-3b3f-4c52-9a63-53f13e093564) |

# STEP4 진행 중 경험 사항

## MVVM 개선

### `ViewModelable` 프로토콜 생성
뷰 컨트롤러의 입력을 받아 처리하고,
그것을 처리하고 난 뒤의 출력을 UI적으로 처리하기 위한 AnyPublisher를 반환하는 함수를 만들었습니다.

- ViewModelable.swift
```swift
protocol ViewModelable {
    associatedtype Input
    associatedtype Output
    
    func transform(from input: Input) -> AnyPublisher<Output, Never>
}
```

### 각 기능의 ViewModel 프로토콜, `{기능명}VMProtrocol`에서 `ViewModelable` 채택
`{기능명}VMProtrocol`에 `ViewModelable`을 채택했습니다.
그리고 Input과 Output에 대한 `associatedtype`을 구체화했습니다.

- GPTChattingVMProtocol.swift
```swift
protocol GPTChattingVMProtocol: ViewModelable
where Input == GPTChatRoomInput, Output == GPTChatRoomOutput { }

struct GPTChatRoomInput {
    let fetchChattings: AnyPublisher<Void, Never>?
    let sendComment: AnyPublisher<String?, Never>?
    let storeChattings: AnyPublisher<Void, Never>?
}

enum GPTChatRoomOutput {
    case success(messages: [Model.GPTMessage], indexToUpdate: Int)
    case failure(Error)
}
```

### `{기능명}VMProtrocol`의 실체화
프로토콜에서 요구하는 함수를 구현했습니다.
- GPTChattingViewModel.swift
```swift
final class GPTChattingViewModel: GPTChattingVMProtocol {
// ...
    private let output = PassthroughSubject<Output, Never>()
    private var cancellables = Set<AnyCancellable>()
// ...
    func transform(from input: GPTChatRoomInput) -> AnyPublisher<GPTChatRoomOutput, Never> {
        bindFetchChattings(from: input.fetchChattings)
        bindSendCommnet(from: input.sendComment)
        bindStoreChattings(from: input.storeChattings)
        
        return output.eraseToAnyPublisher()
    }
// ...
    private func bindFetchChattings(from publisher: AnyPublisher<Void, Never>?) {
        publisher?
            .sink { [weak self] in
                guard let self else { return }
                do {
                    messages = try chattingRepository.fetchChattings(for: chatRoomDTO)
                    if messages.count - 1 < 0 {
                        return
                    }
                    output.send(Output.success(messages: messages, indexToUpdate: messages.count - 1))
                } catch {
                    output.send(Output.failure(error))
                }
            }
            .store(in: &cancellables)
    }
}
```

## {기능명}Repository 구현

### 프로토콜 구현
기능과 관련한 `Repositable` 프로토콜을 만들었습니다.
왜냐하면 추후에 CoreData가 아닌 다른 방식으로 데이터를 가져올 수도 있기 때문입니다.
아래의 프로토콜을 채택한 타입이면 내부가 어떻게 되든 원하는 결과를 불러올 수 있어야 한다고 생각했습니다.
예를 들어, `let a: ChatRoomRepositable`가 `fetchChatRoomList ()`를 호출한다면, 
CoreData가 됐든 UserDefault가 됐든 서버가 됐든 결과를 가져올 수 있습니다.
- ChatRoomRepositable.swift
```swift
protocol ChatRoomRepositable {
    func fetchChatRoomList() throws -> [Model.GPTChatRoomDTO]
    func storeChatRoom(_ chatRoom: Model.GPTChatRoomDTO) throws
    func modifyChatRoom(_ chatRoom: Model.GPTChatRoomDTO) throws
    func removeChatRoom(_ chatRoom: Model.GPTChatRoomDTO) throws
}
```

### 구현체 구현
- CoreDataChatRoomRepository.swift
``` swift
extension Repository {
    final class CoreDataChatRoomRepository {
        let coreDataRepository: Repository.CoreDataRepository
        
        init(coreDataRepository: Repository.CoreDataRepository = AppEnviroment.defaultCDRepository) {
            self.coreDataRepository = coreDataRepository
        }
    }
}

extension Repository.CoreDataChatRoomRepository: ChatRoomRepositable {
    func fetchChatRoomList() throws -> [Model.GPTChatRoomDTO] {
        let request = ChatRoom.fetchRequest()
        let chatRoomList = try coreDataRepository.context.fetch(request)
        
        return chatRoomList.map { chatRoom in
            return Model.GPTChatRoomDTO(id: chatRoom.id!, title: chatRoom.title!, recentChatDate: chatRoom.recentChatDate!)
        }
    }
    
    func storeChatRoom(_ chatRoom: Model.GPTChatRoomDTO) throws {
        guard let chatRoomCD = NSManagedObject(entity: ChatRoom.entity(), insertInto: coreDataRepository.context) as? ChatRoom else {
            throw GPTError.RepositoryError.contextNotFound
        }
        
        chatRoomCD.id = chatRoom.id
        chatRoomCD.title = chatRoom.title
        chatRoomCD.recentChatDate = chatRoom.recentChatDate
        
        try coreDataRepository.saveContext()
    }
    
    func modifyChatRoom(_ chatRoom: Model.GPTChatRoomDTO) throws {
        let request = ChatRoom.fetchRequest()
        let predicate = NSPredicate(format: "id == %@", chatRoom.id.uuidString)
        request.predicate = predicate
        
        guard let result = try? coreDataRepository.context.fetch(request).first else {
            throw GPTError.RepositoryError.dataNotFound
        }
        
        result.title = chatRoom.title
        try coreDataRepository.saveContext()
    }
    
    func removeChatRoom(_ chatRoom: Model.GPTChatRoomDTO) throws {
        let request = ChatRoom.fetchRequest()
        let predicate = NSPredicate(format: "id == %@", chatRoom.id.uuidString)
        request.predicate = predicate
        
        guard let result = try? coreDataRepository.context.fetch(request).first else {
            throw GPTError.RepositoryError.dataNotFound
        }
        
        coreDataRepository.context.delete(result)
        try coreDataRepository.saveContext()
    }
}
```

## `convenience init` 사용
### UIAlertController의 `convenience init`
프로젝트 진행 중, AlertController의 생성 코드가 유사한 패턴을 보여서,
`convenience init`을 통해서 중복되는 코드를 없앴습니다.
- UIAlertController+Extension.swift
```swift
extension UIAlertController {
    /// 에러를 보여주기 위해 사용합니다.
    convenience init(error: Error) {
        self.init(title: "\(type(of: error))", message: error.localizedDescription, preferredStyle: .alert)
        addAction(UIAlertAction(title: "닫기", style: .cancel))
    }
    
    /// 방의 제목을 입력받아 생성 또는 삭제하기 위해 사용합니다.
    convenience init(title: String, message: String?, completionHandler: @escaping (String?) -> Void) {
        self.init(title: title, message: message, preferredStyle: .alert)
        addTextField()
        addAction(UIAlertAction(title: "닫기", style: .destructive))
        addAction(UIAlertAction(title: "확인", style: .default, handler: { [weak self] _ in
            completionHandler(self?.textFields?.first?.text)
        }))
    }
}
```

2024-01-22 13:27 UTC, jungseungyeo requested changes
안녕하세요 뉴준성

코드를 보면서 잘 작성 된 형태의 코드라는 생각이 들었습니다.

코드 리뷰는 크게 3가지 정도 드렸습니다. 
1. tableview 사용방법 -> enum Section, enum Row를 사용하여 Model로 세션과 row를 만들어서 스냅샷을 하는 형태로 작성하고 row를 통해서 해당 값을 전달받는 형태로 구성

2. viewModel의 형태변경
- input, output구조는 너무 좋으나 subject가 view에 있어 이벤트 전다르 흐림이 뷰로 전달하여 input의 들어가는 형태라 바로 viewModel로 전달하는 형태로 변경을 요청

3. 테스트코드 Mock객체 사용
- 테스트를 하는 부분에서 실제로 저장을 사용하고 있습니다. 함수가 불렸다 정도의 이벤트를 받아서 처리하는 형태로 작성부탁드립니다.

위의 3가지 요청사항을 코멘트에 남겨두었습니다. 확인해보시고 궁금한점 질문해주세요.

2024-01-22 13:27 UTC, jungseungyeo commented on ChatBot/ChatBot/Presentation/GPTChatRooms/ViewController/GPTChatRoomsViewController.swift
> +        UIAlertController(title: "방 생성", message: "생성할 방 제목을 입력해주세요.") { [unowned self] roomName in
unowned는 잘 사용하지 않는데요 
크래시가 발생 할 수 있기 때문에 안전한 코드를 사용하기 위해서는 weak self를 사용하는 편이 좋습니다. 
weak self로 변환 부탁드려요

2024-01-22 13:27 UTC, jungseungyeo commented on ChatBot/ChatBot/Design/Extension/UIAlertController+Extension.swift
> +extension UIAlertController {
이건 꼭 안해도 됩니다.
도전) 전반적인 코드가 combine 기반으로 작성이 되었습니다 .combine 기반으로 작성 되었기에 UIAlertController도 publisher인터페이스로 변환해주면 더욱 좋은데요.

예를 들어 
``` swift
UIAlertController.presentPublisehr(on: UIViewController, error)
 .sink { action in
 }.store(in: &cancellables)
```

위 처럼 사용을 하게 인터페이스를 만들어서 사용해도 좋고

``` swift

        viewModel.transform(from: input)
            .flatMap { [weak self] ouptut in
                guard case .failure(let error) = output else {
                    return Empty().eraseToAnyPublisher()
                }
                return UIAlertController(on: self, error: error).presentPublisehr.eraseToAnyPublisher()
            }.sink { action in
                // .. 에러 팝업 클릭시 오는 이벤트 
            }.store(in: &cancellables)

```

위 처럼 활용도 할 수 있겠죠?

rx를 사용하던 시절에 많이 사용하는 형태라 combine도 동일 할거라고 생각이 드네요. 해당 부분은 rx를 사용하는 회사나 combine 기반으로 사용하는 회사에도 많이 사용하는 형태입니다.

2024-01-22 13:27 UTC, jungseungyeo commented on ChatBot/ChatBot/Presentation/GPTChatRooms/ViewController/GPTChatRoomsViewController.swift
> +                    self?.present(UIAlertController(error: error), animated: true)
success와 failure를 하나의 result 타입으로 묶으면 더욱 정리가 될거같아요. 이건 코드 스타일 리뷰라 꼭 지키지않아도 되지만,
아래의 moveToChatRoom case 도 있어 결과 case 와 다른 case 이런게 가는게 더 정리가 되는 느낌이라. 의견드립니다.

2024-01-22 13:27 UTC, jungseungyeo commented on ChatBot/ChatBot/Presentation/GPTChatRooms/ViewController/GPTChatRoomsViewController.swift
> +            return cell
이 부분도 좋습니다. 좋은데.. 자주 사용하는 형태는 아니예요.
자주 사용을 안한다는것은 코드상 문제가 있는 부분이 아니라 type을 지정해서 사용하는 형태를 많이 사용합니다.

예를 들어 

``` swift
enum Section: Hashable {
  case main
}

enum Row: Hashable {
   case forMain(title: String, localeString: String)
}

```
형태로 가져간다면  func applySnapshot() 에서 section, row를 [Model.GPTChatRoomDTO]로 생성을 한다면 더 관리 하기 좋은 형태로 변환이 될거같아요.

2024-01-22 13:27 UTC, jungseungyeo commented on ChatBot/ChatBot/Presentation/GPTChatRooms/ViewController/GPTChatRoomsViewController.swift
> +        var snapshot = NSDiffableDataSourceSnapshot<Section, Model.GPTChatRoomDTO>()
위의 코멘트랑도 이여지는데요.

`NSDiffableDataSourceSnapshot<Section, Row>()`의 형태가 되면 더욱 좋은 코드가 될거같아요.

Row는 section처럼 enum으로 생성하면 될거같아요.

2024-01-22 13:27 UTC, jungseungyeo commented on ChatBot/ChatBot/Presentation/GPTChatRooms/ViewController/GPTChatRoomsViewController.swift
> +        UIAlertController(title: "방 수정", message: "수정할 방 제목을 입력해주세요.") { [unowned self] roomName in
```suggestion
        UIAlertController(title: "방 수정", message: "수정할 방 제목을 입력해주세요.") { [weak self] roomName in
```

가능하다면 publisher 인터페이스 제공을 희망함

2024-01-22 13:27 UTC, jungseungyeo commented on ChatBot/ChatBot/Presentation/GPTChatRooms/ViewController/GPTChatRoomsViewController.swift
> +    private let selectRoomSubject = PassthroughSubject<IndexPath, Never>()
input과 output 구조를 가져가는 것은 좋은데 input, output을 전달하는 방식 떄문에 이벤트를 view에서 받아서 넘겨주는 형태가 되는거같아요.
input, output 구조를 조금 변경하여 `viewmodel.input.fetch()`와 같은 형태로 변환이 필요해보여요. 
input을 꼭 Subject로 될 필요는 없는거같아요.

input은 함수형태 output이 AnyPublisher로 되면 더 깔끔해질거같아요. 지금의 형태와 반대일거같아요. ViewModelable 프로토콜의 형태가 변경 될수있어서 너무 큰 작업이라면 안해도괜찮을거같아요.

2024-01-22 13:27 UTC, jungseungyeo commented on ChatBot/ChatBot/Presentation/GPTChatRooms/ViewController/GPTChatRoomsViewController.swift
> +    private let selectRoomSubject = PassthroughSubject<IndexPath, Never>()
원하는 형태는 

``` swift

override func viewDidLoad() {
   super.viewDidLoad()

  bind()
  
  // 이벤트 전달
  viewModel.input.onViewDidLoad()
}

private func bind() {
  viewModel.output.publisher
    .sink {}
  ...// 생략

   //or
  viewModel.output 
    .filter { $0 == .fetch }
    .sink  { }
  ...// 생략

}

```

위의 형태면 더 괜찮을거같아요.

2024-01-22 13:27 UTC, jungseungyeo commented on ChatBot/ChatBot/Presentation/GPTChatRooms/ViewModel/Implements/GPTChatRoomsViewModel.swift
> +    init(chatRoomRepository: ChatRoomRepositable = Repository.CoreDataChatRoomRepository()) {
Repository를 주입해주는 코드군요 너무 좋아요 :)

2024-01-22 13:27 UTC, jungseungyeo commented on ChatBot/ChatBotTests/Tests/ChatBotRepositoryTests.swift
> +        chatRoomRepository = Repository.CoreDataChatRoomRepository()
이렇게 넣어주면 mock이 아니라 실제 객체가 들어가게 되지 않나요?

2024-01-22 13:27 UTC, jungseungyeo commented on ChatBot/ChatBotTests/Tests/ChatBotRepositoryTests.swift
> +        chatRoomRepository = Repository.CoreDataChatRoomRepository()
Mock을 넣어주게 테스트를 작성하고 Mock에서는 storeChatRoom함수 통해서 save까지 잘 호출되면 success아니면 failure의 형태로 테스트를 진행하셔야합니다. 

현재는 MockChatRoom.mockChatRoom이라는 가짜 모델을 실제로 저장하고 있어요. 테스트는 실제로 저장하거나 삭제를 해서는 안되요. 해당 함수가 잘 호출되었다 정도까지만 해도 충분합니다.

2024-01-22 13:27 UTC, jungseungyeo commented on ChatBot/ChatBotTests/Tests/ChatBotRepositoryTests.swift
> +        XCTAssertNotNil(chatRoomList)
테스트를 할 때 //give //when // then 영역을 꼭 주석으로 남겨주세요. 
대부분 사전과젱서 위의 형태의 테스트를 작성하면 좋아하고 이해하기가 쉽습니다.

2024-01-23 06:12 UTC, newJunsung commented on ChatBot/ChatBot/Presentation/GPTChatRooms/ViewController/GPTChatRoomsViewController.swift
> +        UIAlertController(title: "방 생성", message: "생성할 방 제목을 입력해주세요.") { [unowned self] roomName in
수정했습니다.

2024-01-23 06:18 UTC, newJunsung commented
https://github.com/tasty-code/ios-chat-bot/pull/24#discussion_r1461807604
--
UIAlertController가 Publisher를 반환하도록 시도해보았습니다.
아래의 코드를 사용할 경우, AlertController를 띄울 때마다, cancellables의 count가 증가하게 됩니다.
count가 늘어나는 것이 좋은 방법이 아니라고 생각하기에, 이 방법이 과연 맞는지에 대한 확신이 없어서 조언을 구하고 싶습니다.


- UIAlertController+Extension.swift
```swift
extension UIAlertController {
    static func presentErrorPublisher(on viewController: UIViewController, with error: Error) -> AnyPublisher<Void, Never> {
        Future<Void, Never> { promise in
            let alertController = UIAlertController(title: "Error", message: error.localizedDescription, preferredStyle: .alert)

            let okayAction = UIAlertAction(title: "Okay", style: .default) { _ in
                promise(.success(()))
            }
            
            alertController.addAction(okayAction)

            viewController.present(alertController, animated: true, completion: nil)
        }
        .eraseToAnyPublisher()
    }
// ...
}
```

- GPTChatRoomsViewController.swift
```swift
final class GPTChatRoomsViewController: UIViewController {
// ...
    private func handleUpdateChatRooms(_ result: Result<[Model.GPTChatRoomDTO], Error>) {
        switch result {
        case .success(let chatRooms):
            applySnapshot(sectionRows: chatRooms.map { Row.forMain(title: $0.title, localeDateString: $0.recentChatDate.toLocaleString(.koKR)) })
        case .failure(let error):
            UIAlertController.presentErrorPublisher(on: self, with: error)
                .receive(on: DispatchQueue.main)
                .sink { _ in
                    print(self.cancellables.count)
                }
                .store(in: &cancellables)

        }
    }
}
```

2024-01-23 06:19 UTC, newJunsung commented on ChatBot/ChatBot/Presentation/GPTChatRooms/ViewController/GPTChatRoomsViewController.swift
> +            return cell
좋은 팁 알려주셔서 감사합니다!
위의 방법으로 수정했습니다!

2024-01-23 06:29 UTC, newJunsung commented
https://github.com/tasty-code/ios-chat-bot/pull/24#discussion_r1461836945
--
Input과 Output의 구조를 수정했습니다.
Input을 구현해야 할 함수들을 담은 Protocol로 만들고, Output은 AnyPublisher를 담은 Protocol로 만들었습니다.
위의 타입으로 코드를 변경하는 과정에서 ViewModelable을 사용할 필요가 없어져서 삭제했습니다.
또한 변경하는 과정에서 ViewModel이 Set<AnyCancellable> 타입을 지닌 프로퍼티를 가질 필요가 없어져서 좋았습니다.
좋은 팁 알려주셔서 감사합니다!
- GPTChattingVMProtocol.swift
```swift
typealias GPTChattingVMProtocol = GPTChattingsInputProtocol & GPTChattingOutputProtocol

protocol GPTChattingsInputProtocol {
    func onViewDidLoad()
    func onViewWillAppear()
    func onViewWillDisappear()
    func sendChat(_ content: String?)
}

protocol GPTChattingOutputProtocol {
    var output: AnyPublisher<GPTChattingOutput, Never> { get }
}

enum GPTChattingOutput {
    case networkChatting(Result<(messages: [Model.GPTMessage], indexToUpdate: Int), Error>)
    case fetchChattings(Result<(messages: [Model.GPTMessage], indexToUpdate: Int), Error>)
}
```

- GPTChattingViewModel.swift
```swift
final class GPTChattingViewModel: GPTChattingOutputProtocol {
    typealias Output = GPTChattingOutput
// ...
    private let outputSubject = PassthroughSubject<Output, Never>()
    var output: AnyPublisher<GPTChattingOutput, Never> { outputSubject.eraseToAnyPublisher() }
// ...
}

extension GPTChattingViewModel: GPTChattingsInputProtocol {
    func onViewDidLoad() { }
    
    func onViewWillAppear() {
        do {
            messages = try chattingRepository.fetchChattings(for: chatRoomDTO)
            if messages.isEmpty { return }
            outputSubject.send(Output.networkChatting(.success((messages, messages.count - 1))))
        } catch {
            outputSubject.send(.fetchChattings(.failure(error)))
        }
    }
    
    func onViewWillDisappear() {
        try? chattingRepository.storeChattings(messages, for: chatRoomDTO)
    }
    
    func sendChat(_ content: String?) {
        guard let content = content, !content.isEmpty else {
            outputSubject.send(.networkChatting(.failure(GPTError.ChatRoomError.emptyUserComment)))
            return
        }
        messages.append(Model.UserMessage(content: content).asRequestMessage())
        messages.append(Model.WaitingMessage().asRequestMessage())
        outputSubject.send(.networkChatting(.success((messages: messages, indexToUpdate: messages.count - 1))))
        
        getReplyFromServer(messages.count - 1)
    }
}
```
- GPTChattingViewController.swift
```swift
final class GPTChattingViewController: UIViewController {
// ...
    private func bind(to viewModel: any GPTChattingVMProtocol) {
        viewModel.output
            .receive(on: DispatchQueue.main)
            .sink { [weak self] output in
                switch output {
                case .fetchChattings(let result):
                    self?.handleChattings(result)
                case .networkChatting(let result):
                    self?.handleChattings(result)
                }
            }
            .store(in: &cancellables)
    }
    
    private func handleChattings(_ result: Result<(messages: [Model.GPTMessage], indexToUpdate: Int), Error>) {
        switch result {
        case .success((let messages, let indexToUpdate)):
            updateCollectionView(messages.map { Row.forMain(message: $0) }, indexToUpdate: indexToUpdate)
        case .failure(let error):
            present(UIAlertController(error: error), animated: true)
        }
    }
}
```

2024-01-23 06:42 UTC, newJunsung commented on ChatBot/ChatBotTests/Tests/ChatBotRepositoryTests.swift
> +        chatRoomRepository = Repository.CoreDataChatRoomRepository()
현재 코드 구조상으로 채팅방 리포지토리를 테스트 할 수 없어서 테스트를 삭제했습니다.
ChatRoomRepositable을 채택한 Mock Type을 만드는 것은 채팅방 타입의 정당성을 체크하는 것에는 도움이 되지만,
채팅방이 저장이 되거나 수정이 되는지에 대한 것을 테스트하지는 않다고 판단했습니다.

채팅방이 저장되거나 수정되는지에 대한 것을 확인하기 위해서는 
진짜 쓰고 읽는 타입(ex. coredata)의 Mock Type을 만들고, 의존성 주입을 해야한다고 생각하는데,
해당 Mock Type을 구현하기 위한 프로토콜을 만드는 것에 시간이 많이 소요될 것 같아서, 
이후에 시간이 남는다면 진행해보도록 하겠습니다.

2024-01-23 13:27 UTC, jungseungyeo approved these changes
안녕하세요 뉴준성!

제가 남긴 코멘트 리뷰보고 잘 적용이 된거같아요. 
alert의 경우 store에 sink 콜백을 저장하고 있어 증복으로 쌓이고 있는거같은데요. 

이런경우는 complete를 꼭 보장해줘야됩니다. 지금  complete가 보장이 안되고 있어서 이슈가 되는거같아요. 어디를 수정해야 complete가 보장되는체크해보시고 적용해주세요 :) 

수고하셨습니다. 다음 스텝 진행하셔도 될거같아요.

2024-01-23 13:27 UTC, jungseungyeo commented on ChatBot/ChatBot/Presentation/GPTChatRooms/ViewController/GPTChatRoomsViewController.swift
> +        return cell
좋습니다 :)

2024-01-23 13:27 UTC, jungseungyeo commented on ChatBot/ChatBotTests/Tests/ChatBotRepositoryTests.swift
> +        chatRoomRepository = Repository.CoreDataChatRoomRepository()
좋은 의견입니다. ㅎㅎ

구조상 문제점을 잘 이해하였고, 수정 범위도 잘 인지하고 있는거같네요 ㅎㅎ 
추후에 시간이 괜찮아지면 수정 부탁드립니다.

2024-01-23 13:27 UTC, jungseungyeo commented on ChatBot/ChatBot/Presentation/GPTChatRooms/ViewController/GPTChatRoomsViewController.swift
> +                .store(in: &cancellables)
complete가 잘 호출되나요? feature를 사용하여 잘 동작 될거같긴한데요. 여러번 호출되는경우 sink 블럭이 여러번 호출 될거같은데요. 한번 다음 스텝에서 체크 해봐주세요. 문제 없을거같긴한데 디버깅을 해봐야 정확할거같네요.

2024-01-23 13:27 UTC, jungseungyeo commented on ChatBot/ChatBot/Design/Extension/UIAlertController+Extension.swift
> +extension UIAlertController {
[코멘트 ](https://github.com/tasty-code/ios-chat-bot/pull/24#issuecomment-1905361274) 의 답변입니다.

현재 중복으로 쌓이는 이유는 코드적으로 보면 쌓이게 되어있습니다. 쌓이는 이유는 alert같은 경우 1회성 타입이라 호출 되면 되면 complete를 보장해줘야하는데 코드적으로 보면 보장이 되어 있지 않습니다.

store를 sink 콜백을 저장하게 되어있죠. 제 코멘트를 보면 flatmap 에서 사용을 하는 형태입니다. 

``` swift

UIAlertController.presentPublisehr(on: UIViewController, error)
 .sink { action in
 }.store(in: &cancellables) 
```
위 처럼 할려면 action이 오는 시점에서는 alert을 dismiss하고 promiss(success())가 되어야 할거같아요. 그래야 레퍼런스 카운트를 올리지 않고 compelete를 보장이 되거같아요.

2024-01-23 13:27 UTC, merged