챗봇 앱 [STEP3] 하워드,록스
tasty-code/ios-chat-bot pull request #25
Opened 2024-01-23 04:54 UTC by JEON-Sungsu

리뷰어: @jryoun1

버드: @JEON-Sungsu, @KimRoks

안녕하세요, 제이크!!

[STEP 3]에서는 이전 구현한 네트워킹 기능을 통해 실제 대화 화면을 구현하였습니다. AI가 이전 대화를 기억하게끔 하고 코어 그래픽, 코어 애니메이션을 통해 자연스러운 대화 화면을 구현하였습니다. 이번 스텝도 잘 부탁드립니다!

### 코드 실행 결과
| 이름 학습 | 키보드 레이아웃 | 애니메이션 | 
| --- | --- | --- | 
|![rememberName](https://github.com/tasty-code/ios-chat-bot/assets/63297236/e7d8da20-3497-46cf-8187-825df7772c64)| ![keyboardLayout](https://github.com/tasty-code/ios-chat-bot/assets/63297236/e316ec75-9deb-473c-8a8e-0ceedf7c22cc)|![reuseableAnimationETC](https://github.com/tasty-code/ios-chat-bot/assets/63297236/b1b9da8a-6e8a-44ae-a6a5-6150b286c1bd)|

### 코드설명

- ChatBotEndpoin & NetworkManager

```swift
//ChatbotEndpoint.swift
struct ChatBotEndpoint: Endpointable {
    var url: URL? = URL(string: BaseURL.openAI.description)
    var accessKey: String? = Bundle.getAPIKey(for: APIKeyName.openAI.description)
    var httpMethod: String = HTTPMethod.post.description
    var httpHeader: [String : String] = ["Content-Type": "application/json"]
    var httpBodyContent: UserContentModel = UserContentModel(messages: [])
    var useAuthorization: Bool = true
}

//NetworkManager.swift
final class NetworkingManager {
    static let shared = NetworkingManager()
    private let decoder = JSONDecoder()
    private let encoder = Encoder()
    
    private init() {}
    
    private func request(_ endpoint: Endpointable) throws -> URLRequest {
        guard let url = endpoint.url else {
            throw NetworkingError.unknownURL
        }
        
        var request = URLRequest(url: url)
        request.httpMethod = endpoint.httpMethod
        
        for (headerField, value) in endpoint.httpHeader {
            request.setValue(value, forHTTPHeaderField: headerField)
        }
        
        if endpoint.useAuthorization {
            guard let accessKey = endpoint.accessKey else {
                throw NetworkingError.accessKey
            }
            request.setValue("Bearer \(accessKey)", forHTTPHeaderField: "Authorization")
        }
        
        request.httpBody = try encoder.transformData(endpoint.httpBodyContent)
        
        return request
    }
    ///생략...
}
```

> 기존에, ChatbotEndpoint에 기본값을 할당하지 않고, 인스턴스 생성시 주입받아서 쓸 수 있도록 만들어서 범용성을 높이려고 하였으나, 주입해야하는 값들이 너무 많아 생성하는 위치에서의 코드가 복잡해져, 기본값을 할당해서, 하나의 endpoint로만 사용하는 방향으로 변경하였습니다. 가지고있던 request 생성하는 메서드를 NetworkingManager로 옮겨서 리퀘스트를 생성할 수 있도록 변경해보았습니다.
> 

- Message.swift

```swift
import Foundation

// MARK: - Message
struct Message: Codable, Hashable, Identifiable {
    var id: UUID = UUID()
    let role: String
    var content: String
    
    enum CodingKeys: CodingKey {
        case role
        case content
    }
}

extension Message {
    func hash(into hasher: inout Hasher) {
        hasher.combine(id)
    }

    static func == (lhs: Message, rhs: Message) -> Bool {
        return lhs.id == rhs.id
    }
}
```

> 유저의 질문을 담는 DTO와 AI의 답변을 담는 DTO에서 공용으로 사용되는 Message 타입을 분리하여, 공용으로 사용할 수 있도록 만들었고, UUID 프로퍼티를 넣고, Hashable 프로토콜을 채택함으로써, diffableDataSource와 cellRegistration의 Item으로 사용할 수 있도록 만들었습니다.
> 

- ViewController.swift

```swift
extension ViewController: ChatViewDelegate {
    func submitUserMessage(chatView: ChatView, animationData: Message, userMessage: String) {
        let newMessage = Message(role: UserContentConstant.userRole, content: userMessage)
        historyMessages.append(newMessage)
        
        endPoint.httpBodyContent.messages = historyMessages
        
        let snapShotItems = [newMessage, animationData]
        
        chatView.updateSnapshot(items: snapShotItems, isFetched: false)
        chatView.scrollToBottom()
        
        NetworkingManager.shared.downloadData(endpoint: endPoint,
                                              to: AIContentModel.self) { result in
            switch result {
            case .success(let data):
                DispatchQueue.main.async { [weak self] in
                    self?.chatView.updateSnapshot(items: [data.choices[0].message], isFetched: true)
                    chatView.toggleSendButton()
                    chatView.scrollToBottom()
                }
            case .failure(let error):
                print(error)
            }
        }
    }
}
```

> AI가 기존의 대화를 기억하도록 하기 위해 histortyMessage 배열을 생성 후 신규 대화를 append 해주고 해당 배열을 대화에 사용하였습니다
> 

### 궁금한 점

- 이번 프로젝트는 MVC 패턴을 기반으로 작성하였습니다. ViewController 내부에서 View와 관련된 전체 코드를 작성하는 것과 Custom UIView를 만들어 Controller에서 전체 뷰를 교체하는 방식 중 고민했는데, 결국 후자를 선택했습니다. 이 과정에서 몇 가지 의문점이 생겨서 질문드립니다**.**
    
    ```swift
    override func loadView() {
            self.view = chatView
        }
    ```
    
    우선, 뷰는 뷰의 형태와 관련된 메서드만을 갖고 있도록 설계하였습니다. 그런데, ViewController에서 ChatView의 메서드를 사용할 때, 예를 들어, `chatView.setTextViewDelegate()`와 같이 사용하게 되는데, 이런 방식은 캡슐화가 부족한 것 같아 고민이 됩니다.
    
    현재는 단순한 뷰를 다루고 있어 크게 문제가 되지 않지만, 뷰의 구성이 복잡해지거나 여러 개의 뷰를 다루게 된다면, 모든 뷰 컴포넌트를 분리하여 `userTextView.setDelegate()`와 같이 사용하는 것이 나을지, 아니면 지금처럼 하나의 뷰 (예시에서는 ChatView)가 모든 컴포넌트를 갖고 있어도 괜찮을지 고민입니다.
    
    아니면 오히려 이런 방식을 채택하다 보니 ViewController가 하는 일이 너무 적어지고 오히려 복잡성만을 키우게 되나 라는 생각이 들어 차라리 ViewController 내부에 관련 코드를 전부 작성하는 것이 차라리 더 적합한 방식일지에 대한 의견도 듣고 싶습니다.
    

- diffableDataSource를 사용함에 따라, snapShot을 통해서 데이터를 추가 & 삭제하는 방식으로 Cell을 생성할 수 있도록 하였습니다. 그래서, 유저가 메세지를 보내고, 답변을 대기하는 중의 애니메이션을 나타내기 위해서, DataSource.swift에 **`let** animationData = Message(role: "indicator", content: "")` 라는 애니메이션 전용 데이터를 만들어서, 유저가 질문을 하는 시점에 snapShot을 통해 데이터를 넣고, AI의 답변이 오면 데이터를 삭제하는 방식을 사용하였는데, 정삭적으로 동작은 하지만.. 이 기능을 구현하기 위해 너무 많은 폼이 드는것 같아서 (animationData라는 프로퍼티를 항상 가지고 있어야하고, 동일한 메서드를 한곳에서 여러번 호출하고 하는 등) 이렇게 사용하는게 맞는건가?? 라는 의문이 들었습니다. 더 좋은 방법이 있으면 알려주시면 감사하겠습니다.

- Animation과 관련하여, 저희는, Animation을 실행시킬 UIView를 별도로 만들고, animateKeyframes 을 통해서 사용하여 만들고, 커스텀 Cell에서 말풍선에 삽입해주는 방식을 사용하였습니다. 근데, 이 방식으로 하다보니 Cell이 생성이 되기도 전에 animation을 실행시키는 함수인 `runSpinner()` 가 호출이 되어서, 말풍선이 나오는 시점에는 애니메이션이 동작하지 않다가, Cell이 재사용될때만 애니메이션이 동작을 하는 버그가 생겼습니다.
    
    시점의 문제인것 같아서, UICollectionViewDelegate를 통한 willDisplay메서드를 써보기도 하고, 다양한 위치에서 `runSpinner()` 메서드를 호출해보았지만 방법을 찾지 못 하다가, 커스텀 Cell 안에서, `layoutSubviews()` 메서드를 override 하여 함수를 호출하니 이번엔 제대로 동작을 하였습니다. 하지만 이것 역시 제대로된 방법인지에 대한 의문이 생겨서 어떤 방법을 쓰는게 좋을지 의견을 여쭙고 싶습니다. 
    

- 현재 저희 코드에서, ViewController, ChatCollectionViewCell, ChatView 등에서 보면, 다양한 저장프로퍼티와 인스턴스들을 가지게 되는데 여기서 꼭 필요하다고 생각되어 만들긴 하였지만, Controller나 View에서 저장프로퍼티나, 인스턴스들을 이렇게 많이 가지고 있어도 되는것인지가 궁금합니다.

2024-01-23 16:36 UTC, jryoun1 requested changes
step3 고생하셨습니다! 
두 분이 많은 고민을 하고 작성하신 것이 느껴지는 코드였던 것 같습니다 👏 👍 💯 
코멘트 남겨두었으니 확인부탁드려요! 

### 궁금한 점

> 질문1

지금 두 분이서 작성하신 방법들은 MVC 패턴의 문제 중에 하나인 ViewController가 무거워지는 문제를 해결하는 방법이 될 수 있을 것 같네요. 
지금 chatView를 ViewController가 아닌 다른 view, viewcontroller에도 충분히 붙여서 사용할 수 있도록 잘 분리를 해주신 것 같습니다. 다만 만약 하나의 vc에서만 사용하는 view라면 따로 분리까지 해야할까 싶긴합니다. 만약 여러 vc에서 사용해야한다면 지금처럼 분리해서 재사용성을 높이는 방법이 좋을 것 같습니다. 

다만 이 부분은 convention이나 vc자체를 최대한 깔끔하게(=코드가 적은 형태로) 가져가는 것이 좋다면 충분히 이런 방식으로 작성해도 될 것 같네요. 

> 질문 2

animationData = Message(role: "indicator", content: "") 로딩용 메시지를 생성해서 지웠다가 넣었다가 하는 방법보다는 기존에 응답을 받을 message 타입에 loadingView를 붙이고 hidden, show 처리하면서 응답이 오기전에는 show+animation을 동작시키고 응답이 오는 시기에는 hidden+ stop animation을 하는 방법도 있을 것 같네요. 

> 질문 3

우선 layoutSubviews()에서 해당 함수를 실행시키는 것이 바람직해보이지는 않습니다. 
이 부분 관련해서는 저도 좀 더 코드를 확인하고 추가로 코멘트 남겨드릴게요~ 
우선 다른 부분들부터 확인부탁드려요! 🙏 

> 질문 4

넵 필요하다면 가지고 있는게 맞습니다! ㅎㅎ 지금 정도면 그렇게 많은 것 같지는 않네요. 대부분 view정도라서 충분히 괜찮은 것 같습니다.

2024-01-23 16:36 UTC, jryoun1 commented on ChatBot/ChatBot/Controller/ViewController.swift
> +final class ViewController: UIViewController {
final 키워드를 사용해주셨군요 👏 
다만 네이밍이 명확하지 않은것 같습니다. 명확한 네이밍으로 변경하면 좋을 것 같네요!

2024-01-23 16:36 UTC, jryoun1 commented on ChatBot/ChatBot/Models/DTO/Message.swift
> +    func hash(into hasher: inout Hasher) {
hash의 역할은 무엇일까요? 🙋‍♂️

2024-01-23 16:36 UTC, jryoun1 commented on ChatBot/ChatBot/Utility/Endpoint/Implementation/ChatBotEndpoint.swift
> +    var httpHeader: [String : String] = ["Content-Type": "application/json"]
타입을 명시할 때 [String: String]이 되어야할 것 같은데 space가 하나 더 들어갔네요!

2024-01-23 16:36 UTC, jryoun1 commented on ChatBot/ChatBot/Utility/Endpoint/Interface/Endpointable.swift
> +    var accessKey: String? { get }
이 두 property가 optional 타입인 이유가 궁금합니다!

2024-01-23 16:36 UTC, jryoun1 commented on ChatBot/ChatBot/Utility/Network/NetworkingManager.swift
> +            let request = try request(endpoint)
사용하는 부분에서 request(endpoint)도 좋지만 request(of: endpoint)로 하는게 좀 더 가독성이 좋은 것 같은데 두 분의 생각은 어떠신가요?

2024-01-23 16:36 UTC, jryoun1 commented on ChatBot/ChatBot/Utility/Network/NetworkingManager.swift
> +        request.httpBody = try encoder.transformData(endpoint.httpBodyContent)
encoding에 실패했을 때는 어디서 처리하게 되는걸까요?

2024-01-23 16:36 UTC, jryoun1 commented on ChatBot/ChatBot/Extensions/UITextView++Extension.swift
> +    }
필요하신 부분을 extension으로 잘 구현해주셨네요 👍 💯

2024-01-23 16:36 UTC, jryoun1 commented on ChatBot/ChatBot/Controller/ViewController.swift
> +            }
guard 문을 통과한 이후 동작이 없는것으로 보여서 이 부분은 if 로 작성하는것이 좀 더 가독성이 좋을 것 같은데 어떻게 생각하시나요? 

두 분은 어떤 상황에 guard를 사용하고 어떤 상황에 if를 사용하실까요? 🙋‍♂️

2024-01-23 16:36 UTC, jryoun1 commented on ChatBot/ChatBot/Models/DTO/Message.swift
> +    var id: UUID = UUID()
id가 var로 선언된 이유가 있을까요?

2024-01-23 16:36 UTC, jryoun1 commented on ChatBot/ChatBot/View/ChatView/ChatView.swift
> +            contentTextView,contentSendButton
, 뒤에 space가 빠졌네요

2024-01-23 16:36 UTC, jryoun1 commented on ChatBot/ChatBot/View/ChatView/ChatView.swift
> +    private lazy var contentTextView: UITextView = {
user가 타이핑하는(input) textView인 것 같은데 좀 더 명확하게 개선해볼까요 🙏🏻

2024-01-23 16:36 UTC, jryoun1 commented on ChatBot/ChatBot/View/ChatView/ChatView.swift
> +    private lazy var contentSendButton: UIButton = {
여기도 sendButton만 해도 충분히 명확한 것 같습니다!

2024-01-23 16:36 UTC, jryoun1 commented on ChatBot/ChatBot/View/ChatView/ChatView.swift
> +        addSubview(chatCollectionView)
line 30번째와 동일한 코드인 것 같네요!

2024-01-23 16:36 UTC, jryoun1 commented on ChatBot/ChatBot/View/ChatView/ChatView.swift
> +        self.backgroundColor = .white
두 분은 self를 사용하는 기준이 있을까요?

2024-01-23 16:36 UTC, jryoun1 commented on ChatBot/ChatBot/View/ChatView/ChatView.swift
> +        guard let userMessage = contentTextView.text else {
비어있는 경우는 검사하지 않아도 될까요? 🤔

2024-01-23 16:36 UTC, jryoun1 commented on ChatBot/ChatBot/View/ChatView/ChatView.swift
> +    private func configureTextView() {
내부 동작은 textView를 원래대로 reset하는 것 같은데 configure는 어색해보입니다!

2024-01-23 16:36 UTC, jryoun1 commented on ChatBot/ChatBot/View/ChatView/ChatView.swift
> +    // MARK: - public Methods
public 메소드가 맞을까요?
Swift의 access control의 default는 internal입니다!

2024-01-23 16:36 UTC, jryoun1 commented on ChatBot/ChatBot/View/ChatView/ChatView.swift
> +        }
여기는 if보다는 guard가 더 가독성 있어보입니다! 
위에 코멘트와 한 번 비교해보시면 좋을 것 같아요 🙏

2024-01-23 16:36 UTC, jryoun1 commented on ChatBot/ChatBot/View/ChatView/ChatView.swift
> +}
delegate pattern을 사용해보셨군요 👏

2024-01-23 16:36 UTC, jryoun1 commented on ChatBot/ChatBot/View/ChatView/ChatView.swift
> +    weak var delegate: ChatViewDelegate?
왜 weak var로 선언해야할까요? 🙋‍♂️

2024-01-23 16:36 UTC, jryoun1 commented on ChatBot/ChatBot/View/ChatView/CollectionView/Cell/ChatBubbleTail.swift
> +            setNeedsDisplay()
이 함수를 호출하면 어떤 일이 일어날까요? 🙋‍♂️

2024-01-23 16:36 UTC, jryoun1 commented on ChatBot/ChatBot/View/ChatView/CollectionView/Cell/ChatCollectionViewCell.swift
> +
프로젝트 전반적으로 불필요한 줄바꿈은 지워도 될 것 같네요!

2024-01-23 16:36 UTC, jryoun1 commented on ChatBot/ChatBot/Enums/Constant/UserContentConstant.swift
>  enum UserContentConstant {
이 타입의 네이밍이 명확하지 않은 것 같은데 혹시 어떤 의미인걸까요? 🙋‍♂️

2024-01-23 16:36 UTC, jryoun1 commented on ChatBot/ChatBot/View/ChatView/CollectionView/Cell/ChatCollectionViewCell.swift
> +    func configureBubbles(identifier: Message) {
message를 message라고 하지 않고 identifier로 명명하신 이유가 궁금합니다!

2024-01-23 16:36 UTC, jryoun1 commented on ChatBot/ChatBot/View/ChatView/CollectionView/Cell/LoadingAnimationView.swift
> +    }()
동일한 코드가 반복되고 있네요. 중복을 없앨수 있도록 개선하면 좋을 것 같습니다.

2024-01-23 16:36 UTC, jryoun1 commented on ChatBot/ChatBot/View/ChatView/CollectionView/Cell/LoadingAnimationView.swift
> +    }
animateKeyframes를 사용해서 animation까지 잘 적용해주셨네요 👏 💯

2024-01-23 16:36 UTC, jryoun1 commented on ChatBot/ChatBot/View/ChatView/CollectionView/Cell/LoadingAnimationView.swift
> +// MARK: - public methods
여기도 public 확인부탁드려요~ 🚨

2024-01-23 16:36 UTC, jryoun1 commented on ChatBot/ChatBot/Controller/ViewController.swift
> +        chatView.delegate = self
비슷한 것들끼리 모아서 함수로 뺄 수 있을 것 같습니다!

2024-01-23 16:36 UTC, jryoun1 commented on ChatBot/ChatBot/Controller/ViewController.swift
> +                }
여기는 self?가 없어도 될까요?

2024-01-23 16:36 UTC, jryoun1 commented on ChatBot/ChatBot/Controller/ViewController.swift
> +                    self?.chatView.updateSnapshot(items: [data.choices[0].message], isFetched: true)
혹시라면 choices가 비어있다면 어떻게 될까요? 🤔

2024-01-24 01:01 UTC, KimRoks commented on ChatBot/ChatBot/Models/DTO/Message.swift
> +    func hash(into hasher: inout Hasher) {
이번 프로젝트에선 DiffableDataSource를 위해 사용되었습니다.
긱 아이템에 대해 유일한 해시값을 제공하고 그것을 통해 데이터 변화를 감지하여 UI를 업데이트 하였습니다.
추가로 hashable를 채택하는 타입이 모두 스위프트 기본타입이라 hash(into:) 함수를 작성하지 않아도 되지만, UUID만을 비교하여 좀 더 명시적으로 사용할 수 있을것이라 기대했습니다.

2024-01-24 01:03 UTC, JEON-Sungsu commented on ChatBot/ChatBot/Controller/ViewController.swift
> +final class ViewController: UIViewController {
넵 ChatRoomViewController로 이름 변경하였습니다.

2024-01-24 01:03 UTC, JEON-Sungsu commented on ChatBot/ChatBot/Utility/Endpoint/Implementation/ChatBotEndpoint.swift
> +    var httpHeader: [String : String] = ["Content-Type": "application/json"]
수정하겠습니다!

2024-01-24 01:06 UTC, JEON-Sungsu commented on ChatBot/ChatBot/Utility/Endpoint/Interface/Endpointable.swift
> +    var accessKey: String? { get }
일단 url 쪽은, URL() 생성자가 옵셔널값으로 반환하기 때문에 옵셔널타입으로 해두었습니다.
이 부분과 관련하여 궁금한게 있는데, 다양한 사례들을 조금 보다보니, URL을 생성할때는 ! 를 통하여 강제 언래핑을 통해서
바로 값을 지정하는 경우가 종종 보이던데, URL을 만들때는 강제언래핑을 사용해도 무방할까요? 

accessKey의 경우에는, 일단 Endpointable이라는 프로토콜은, 향후 또다른 Endpoint 객체들이 모두 채택할것이라는 가정하에, 어떤 Endpoint는 accessKey가 필요없는 경우도 있을것이다 라는 생각에 옵셔널로 두게 되었습니다.

2024-01-24 01:06 UTC, JEON-Sungsu commented on ChatBot/ChatBot/Utility/Network/NetworkingManager.swift
> +            let request = try request(endpoint)
그게 더 좋은거 같아요! 반영하도록 하겠습니다.

2024-01-24 01:13 UTC, KimRoks commented on ChatBot/ChatBot/Controller/ViewController.swift
> +            }
보통 early exit의 개념이 필요하여 필수 조건을 앞서 보여줄 때 guard 문을 많이 사용하려고 하고 있습니다.
해당 경우는 해당하지 않아 if 문으로 수정하였습니다.

2024-01-24 01:14 UTC, KimRoks commented on ChatBot/ChatBot/View/ChatView/ChatView.swift
> +            contentTextView,contentSendButton
수정하였습니다!

2024-01-24 01:19 UTC, KimRoks commented on ChatBot/ChatBot/View/ChatView/ChatView.swift
> +    private lazy var contentSendButton: UIButton = {
현재 화면에서 버튼은 하나 존재하고, 하나의 뷰를 다루고 있기 때문에 제이크 말씀에 동의하여 sendButton으로 수정하였습니다!

2024-01-24 01:25 UTC, JEON-Sungsu commented on ChatBot/ChatBot/Utility/Network/NetworkingManager.swift
> +        request.httpBody = try encoder.transformData(endpoint.httpBodyContent)
다시 돌아보니 적절히 처리가 되지 않게 되어있었네요!!
encoder에서 encoding 실패시 nil을 리턴하게 되고, request 메서드에서 guard let을 통해 인코딩 실패시 throw로 처리하여
downloadData에서 한꺼번에 에러처리가 되도록 변경하였습니다!

2024-01-24 01:27 UTC, KimRoks commented on ChatBot/ChatBot/View/ChatView/ChatView.swift
> +        addSubview(chatCollectionView)
확인하고 수정하였습니다!
다른 컴포넌트처럼 UI 클로저 내에서 처리를 하도록 컨벤션을 잡아서 이와 같은 실수를 방지하도록 하겠습니다!

2024-01-24 01:50 UTC, JEON-Sungsu commented on ChatBot/ChatBot/Models/DTO/Message.swift
> +    var id: UUID = UUID()
아.. 이 부분은 이전에 메세지 수신상태 애니메이션 표현을 위해, 데이터를 이리저리 가공해보고 테스트해보는 과정에서 실수가 있었던것 같습니다..!  id와 messages까지 let으로 변경해두었습니다.

2024-01-24 01:58 UTC, JEON-Sungsu commented on ChatBot/ChatBot/View/ChatView/ChatView.swift
> +    weak var delegate: ChatViewDelegate?
delegate 패턴을 사용할 때, 객체간 순환 참조가 발생할 수 있기 때문에, 메모리 누수를 방지하기 위해서 weak var를 사용하는것으로 알고 있습니다. 또한, weak 키워드는 class 에서만 사용이 가능하기에, delegate에 Anyobject을 채택함으로써 class에서만 델리게이트 패턴이 가능하도록 만들었습니다.

2024-01-24 02:06 UTC, JEON-Sungsu commented on ChatBot/ChatBot/View/ChatView/CollectionView/Cell/ChatBubbleTail.swift
> +            setNeedsDisplay()
다음번 View drawing cycle 때 draw 메서드를 호출시켜 뷰를 다시 그리는 것으로 알고있습니다. 
user의 채팅 UI의 컬러와 AI의 컬러가 달라서, 공용으로 쓰기위해 호출시점에 색상이 정해지면, 정해진 색상대로
뷰를 그리기 위해 사용하였습니다.

2024-01-24 06:43 UTC, JEON-Sungsu commented on ChatBot/ChatBot/View/ChatView/CollectionView/Cell/ChatCollectionViewCell.swift
> +    func configureBubbles(identifier: Message) {
금번 스탭에서 modern collectionView에 대해서 학습을하고 적용을 해보는게 스텝의 목표였는데,
공식문서를 많이 보다보니.. 아래처럼 DataSource나 cellRegstration 등에서 identifier라는 말을 많이써서
자연스럽게 identifier라는 네이밍을 사용하게 된 것 같습니다. 
확실히 이제 보니 해당 메서드의 파라미터명으로는 적절하지 않은것 같아요. 
적절한 네이밍을 고려해서 수정해보도록 하겠습니다! 
```swift
class UICollectionViewDiffableDataSource<SectionIdentifierType, ItemIdentifierType> 
```

2024-01-24 06:45 UTC, KimRoks commented on ChatBot/ChatBot/View/ChatView/ChatView.swift
> +    // MARK: - public Methods
접근제어에 대해서 복습하였고 internal로 변경하였습니다!

2024-01-24 10:32 UTC, KimRoks commented on ChatBot/ChatBot/View/ChatView/ChatView.swift
> +        guard let userMessage = contentTextView.text else {
텍스트 뷰가 비어있는 경우 사용자에게 재입력을 요구하는 Alert을 띄우도록 수정하였습니다!

2024-01-24 10:35 UTC, KimRoks commented on ChatBot/ChatBot/View/ChatView/ChatView.swift
> +        }
수정하였습니다!

2024-01-24 10:36 UTC, KimRoks commented on ChatBot/ChatBot/View/ChatView/CollectionView/Cell/ChatCollectionViewCell.swift
> +
전체적으로 코딩컨벤션과 불필요한 부분에 대해서 한번 더 검토하겠습니다 🥲

2024-01-24 10:38 UTC, KimRoks commented on ChatBot/ChatBot/View/ChatView/ChatView.swift
> +    private func configureTextView() {
resetTextView로 수정하였습니다!

2024-01-24 10:46 UTC, KimRoks commented on ChatBot/ChatBot/View/ChatView/ChatView.swift
> +    private lazy var contentTextView: UITextView = {
확실한 의미전달을 위해 userInputChatTextView 로 변경 해보았습니다!

2024-01-24 10:57 UTC, KimRoks commented on ChatBot/ChatBot/Controller/ViewController.swift
> +                }
chatView의 경우 self 를 클로저내에서 직접적으로 참조하는 형식이 아닌
이미 ChatRoomViewControlelr내에서 참조가 된 속성을 사용하는 경우이기 때문에 self?를 사용하지 않아도 괜찮을것으로 생각합니다.
수정했습니다!

2024-01-24 11:01 UTC, KimRoks commented on ChatBot/ChatBot/Controller/ViewController.swift
> +        chatView.delegate = self
델리게이트를 설정해주는 부분과 키보드를 숨기기 위한 메서들을 분류하여 수정하였습니다!

2024-01-25 01:48 UTC, JEON-Sungsu commented on ChatBot/ChatBot/Controller/ViewController.swift
> +                    self?.chatView.updateSnapshot(items: [data.choices[0].message], isFetched: true)
만약에 choices가 nil로 들어오게 된다면, decoding error가 발생하여 에러핸들링이 가능할 것 같은데,
말씀해주신 의도가 매직넘버를 통한 인덱스로 메세지를 가져오는 부분에 대한 우려사항이신것 같아서
first와 guard let을 사용해서 예외처리를 할 수 있도록 수정하였습니다.
혹시 의도하신바와 다르다면 말씀해주세요! 

```swift
guard let message = data.choices.first?.message else {
    self.showAlert(title: "에러가 발생하였습니다", message: "잠시 후 다시 시도해주세요.", needErrorHandle: true)
    return
}
```

2024-01-25 01:49 UTC, JEON-Sungsu commented on ChatBot/ChatBot/View/ChatView/CollectionView/Cell/LoadingAnimationView.swift
> +    }()
UIView의 extension을 통해서 convenience init을 사용하여 중복 코드를 줄일 수 있도록 만들었습니다.

2024-01-25 01:57 UTC, JEON-Sungsu commented on ChatBot/ChatBot/Enums/Constant/UserContentConstant.swift
>  enum UserContentConstant {
원래는 httpBody에 들어갈, 고정값들을 enum으로 지정해두었는데, 확실히 의미가 명확하지 않은것 같네요.
그래서 RequestBodyConstant로 변경해보았습니다.

2024-01-25 01:58 UTC, JEON-Sungsu commented on ChatBot/ChatBot/View/ChatView/ChatView.swift
> +        self.backgroundColor = .white
사실 각자의 기준이 있었던것 같은데, 이에 대해서 얘기를 해보진 않았던것 같습니다.
말씀해주신 덕분에 록스와 얘기해서 컨벤션을 맞추었습니다.

2024-01-25 13:36 UTC, jryoun1 commented on ChatBot/ChatBot/Utility/Endpoint/Interface/Endpointable.swift
> +    var accessKey: String? { get }
넵 좋네요. 다만 강제 언레핑은 크래시를 발생시킬 수 있는 위험이 있기에 사용을 지양하는게 좋을 것 같습니다.
개인적으로 크래시는 앱을 사용하는 고객 입장에서는 매우 크리티컬한 이슈이기에 크래시가 발생하지 않도록 하는게 중요한 것 같아요!

2024-01-25 13:40 UTC, jryoun1 commented on ChatBot/ChatBot/View/ChatView/ChatView.swift
> +        guard let userMessage = contentTextView.text else {
개인적으로 해당 UX는 조금은 어색한 것 같습니다! 
대부분의 채팅 앱의 경우에 비어있다면 전송 버튼 자체가 비활성화 되어있는게 조금 더 일반적인 UX인 것 같습니다.

2024-01-25 13:43 UTC, jryoun1 commented on ChatBot/ChatBot/Controller/ViewController.swift
> +                    self?.chatView.updateSnapshot(items: [data.choices[0].message], isFetched: true)
배열에 직접적으로 접근하는 코드도 크래시를 유발할 수 있습니다! 
위에서도 말씀드렸듯이 크래시는 크리티컬하기에 주의가 필요할 것 같네요. 
관련해서 물론 first를 통한 방법도 있지만 만약 2번째 혹은 3번째 index에 접근해야하는 경우가 생길수도 있는데 이때 배열에 **안전하게 접근**할 수 있는 subscript에 대해서도 학습해보시면 좋을 것 같습니다 🙏

2024-01-25 13:54 UTC, jryoun1 reviewed
고생하셨습니다! 수정사항 확인했습니다 👍 💯 

몇 가지 개선되면 좋을만한 부분들과 코멘트 주신 부분들에서 질문주신 부분들에 대해서 답변 남겨드렸습니다. 확인부탁드려요 🙏

2024-01-25 13:54 UTC, jryoun1 commented on ChatBot/ChatBot/View/ChatView/CollectionView/Cell/ChatCollectionViewCell.swift
> +    }
이 부분에 대해서는 위에서 코멘트 드린 것 처럼 layouSubviews에서 해당 함수를 호출하는 것이 아닌 collectionViewCell이 노출되고 난 이후 실제로 api를 호출하기 전에 loadingAnimation을 수행하고, 응답을 받아온 이후에 loadingAnimation을 stop하는 방향으로 개선되면 좋을 것 같네요!

2024-01-25 13:54 UTC, jryoun1 commented on ChatBot/ChatBot/Extensions/UIView++Extension.swift
> +    }
extension으로 구현하는 것과 UIView를 상속받는 CircleView 클래스를 만들어서 인스턴스를 생성하는 것의 차이는 어떤걸까요? 🙋‍♂️

2024-01-25 13:54 UTC, jryoun1 commented on ChatBot/ChatBot/Enums/Constant/RequestBodyConstant.swift
> +enum RequestBodyConstant {
훨씬 명확해졌네요 👏

2024-01-25 13:54 UTC, jryoun1 commented on ChatBot/ChatBot/Controller/ChatRoomViewController.swift
> +    }
이 부분 위에 코멘트에 남겨드린것처럼 개선되면 좋을 것 같네요 🙏

2024-01-26 01:11 UTC, JEON-Sungsu commented on ChatBot/ChatBot/Extensions/UIView++Extension.swift
> +    }
음.. 아무래도 클래스를 만들어서 사용하게 된다면, 용도의 명확성?? 을 특정할 수 있지 않을까 생각됩니다. 
extension을 쓰면 어디서든 쉽게 사용할 수 있지만, 용도 외의 상황에도 쓸 수 있기 때문에 책임이나 역할이 불분명해질 수 도 있다는 생각이 듭니다.

2024-01-26 02:10 UTC, KimRoks commented on ChatBot/ChatBot/Controller/ChatRoomViewController.swift
> +    }
텍스트 뷰가 비어있을때 버튼을 비활성화 하고, 상황에 맞게 활성화 되도록 개선하였습니다!

2024-01-26 02:29 UTC, JEON-Sungsu commented on ChatBot/ChatBot/View/ChatView/CollectionView/Cell/ChatCollectionViewCell.swift
> +    }
해당 문제를 해결하려고 이런저런 방법을 많이 써봤는데.. 도저히 어떻게 해야 될 지 잘 모르겠습니다. 
diffableDatasource를 사용하다보니 어느 시점에 cell이 화면에 노출되는지를 캐치할 수 있는 방법이 없어서 
말씀해주신 방법으로 어떻게 처리해야될지 모르겠습니다. 

그래서 생각해낸 방법이 UICollectionViewDelegate를 통해서 willDisplay함수나 didEndDisplaying함수등을 사용해서, cell이 노출된 이후에 애니메이션을 수행하려고 했지만 이것도 시점이 맞지않아서, willDisplay 메서드 내에서 Timer를 통해 0.1초 뒤에 실행토록 하니 제대로 동작함을 확인할 수 있었습니다.

근데 아무리 생각해봐도 해당 방식은 좀 많이 아닌것 같아요..근데 도저히 방법을 모르겠습니다!! 
뭔가 설계가 잘못된거 같기도 하구요.. 아에 근본부터 뜯어고치는게 맞을까요??

2024-01-26 14:38 UTC, jryoun1 commented on ChatBot/ChatBot/Extensions/UIView++Extension.swift
> +    }
넵 좋습니다! 말씀주신 부분들도 포함이될 것 같네요. 
다만 extension의 경우에는 명확하지 않을 수 있다는 점과 예를 들어 override를 해야하는 경우에는 하지 못하게 되는 경우들도 있을 것 같네요!

2024-01-26 14:42 UTC, jryoun1 commented on ChatBot/ChatBot/View/ChatView/CollectionView/Cell/ChatCollectionViewCell.swift
> +    }
말씀주신 것처럼 1초 딜레이해서 처리하는 방식보다는 ChatViewDelegate의 submitUserMessage 메소드를 구현하는 곳에서 현재 해당 cell이 노출되어있는지(cell의 role이 indicator인지 확인) + 노출되었다면 animation을 처리하도록 하는 방식도 가능할 것 같긴하네요. 

그리고 해당 메소드 내에서 비동기로 request이후에는 stop animation을 처리하는 방식이 될 수 있을 것 같습니다.

2024-01-26 14:43 UTC, jryoun1 approved these changes

2024-01-26 14:44 UTC, merged