AI 챗봇 앱 [STEP3] 범, 도라
tasty-code/ios-chat-bot pull request #26
Opened 2024-01-23 08:20 UTC by snowy-summer

리뷰어  @protocorn93

버드  @KSK9820 @snowy-summer

안녕하세요. 콘!!

AI 챗봇 버드 범, 도라입니다.

[STEP3]에서 입력과 응답을 채팅방으로 구현했습니다.

읽어보시고 코멘트 남겨주시면 감사하겠습니다!! 🙏🙏

## 프로젝트 파일 구조

```
.
├── ChatBot
│   ├── ChatBot
│   │   ├── APIKeys.plist
│   │   ├── AppDelegate.swift
│   │   ├── ChattingViewController.swift
│   │   ├── DTO
│   │   │   ├── CommonModel.swift
│   │   │   ├── RequestModel.swift
│   │   │   └── ResponseModel.swift
│   │   ├── Enum
│   │   │   ├── ContentType.swift
│   │   │   ├── Direction.swift
│   │   │   ├── HttpMethod.swift
│   │   │   └── Path.swift
│   │   ├── Error
│   │   │   ├── JSONConvertError.swift
│   │   │   └── NetworkError.swift
│   │   ├── Extension
│   │   │   ├── Bundle+Extension.swift
│   │   │   └── UITextView+Extension.swift
│   │   ├── Info.plist
│   │   ├── Network
│   │   │   ├── NetworkManager.swift
│   │   │   └── NetworkManagerProtocol.swift
│   │   ├── SceneDelegate.swift
│   │   ├── URL
│   │   │   ├── APIBaseURLProtocol.swift
│   │   │   └── OpenAIURL.swift
│   │   ├── Utility
│   │   │   ├── ChatService.swift
│   │   │   ├── ChatServiceDelegate.swift
│   │   │   └── JSONConverter.swift
│   │   └── View
│   │       ├── ChatBalloon.swift
│   │       ├── ChatBalloonCell.swift
│   │       ├── ChatCollectionView.swift
│   │       ├── ChatCollectionViewDelegate.swift
│   │       ├── ChatTextInputView.swift
│   │       └── LoadingView.swift
```

## 프로젝트 설명

### 구현 내용

- [x]  Safe Area을 고려한 오토레이아웃 구현
- [x]  Collection View의 활용
- [x]  Modern Collection View 활용
- [x]  Core Graphics와 Core Animation의 활용

### 각 역할 설명

**ViewController**

- ChattingViewController
    - STEP2에서 구현한 네트워킹 기능을 통해 실제로 대화 화면을 구현함

**View**

- ChatCollectionView
    - `DiffableDataSource`를 사용해서 CollectionView를 구성함
- ChatCollectionViewDelegate
    - 대화를 `DiffableDataSource`의 `snapshot`에 저장하고 적용함
- ChatBalloonCell
    - cell 내부에 보여질 ChatBalloon의 레이아웃 제약을 설정함
- ChatBalloon
    - 말풍선을 그리고, 메세지의 위치에 따른 레이아웃 제약을 설정함
- ChatTextInputView
    - 사용자의 입력을 받는 textView와 button이 들어간 Stack View
- LoadingView
    - 사용자가 보낸 응답이 화면에 표시하기 전에 대기 중이라는 표시를 보여주는 애니메이션을 포함한 View

**Utility**

- ChatService && ChatServiceDelegate
    - 범용을 목적으로 구현한 `NetworkManager`를 사용해서, 채팅용 네트워크 기능과 `JSONConverter`의 기능을 합침

**Extension**

- UITextView+Extension
    - 입력한 텍스트에 맞춰 `UITextView`의 크기를 유동적으로 조절함

## 실행 결과
![AI챗봇STEP3](https://github.com/tasty-code/ios-chat-bot/assets/118453865/ef5a1122-9952-40ac-a87a-198c48dee489)

## 질문 드리고 싶은 부분
![ㅂㅂㅂㅂㅂㅂㅂ](https://github.com/tasty-code/ios-chat-bot/assets/118453865/4302e5ff-0e95-428b-a225-b1b9d1d59c75)

 
- cell을 생성할 때, 재사용 cell도 사용하고 새로운 cell도 생성해서 화면을 구성합니다.
    - 이런 경우에는 재사용 cell을 사용할 때(= `prepareForReuse`)에도 초기 설정을 해줘야하고, 새로운 cell을 생성하는 경우(= configuration 메서드)에도 초기 설정도 해주고 있습니다.
    - 현재는 같은 cell에 응답과 입력을 모두 보여주고 있습니다. 이 때 재사용 cell이던, 새로운 cell이던 cell에서 말풍선이 표시될 방향을 지정하면서 설정을 함께 잡아주고 있습니다.
    - 하지만 가끔씩 사진과 같이 색상이 화면에 표시되고 난 후에 원래 보여줘야하는 색상으로 변경되는 문제가 있습니다.
    - cell이 보여줄 화면을 통일성 있게, 어디에서 설정을 해줘야하는건지 잘 모르겠습니다. 혹은 custom cell을 2개(= 입력, 응답)을 따로 만들어서 사용을 해줘야 할까요?

|문제1|문제2|   
|:--:|:--:|
|![image](https://github.com/tasty-code/ios-chat-bot/assets/118453865/66868fae-78d1-4997-8468-9b09743b3b7d) |![image](https://github.com/tasty-code/ios-chat-bot/assets/118453865/e5a2a43e-7e35-4d0e-9d5f-c4e8d1df95f3) |

- 또한 위와 같이 스크롤이 짤리거나, 셀의 높이가 설정대로 변경되지 않는 경우도 있었습니다. 이 또한 재사용과 관련된 문제로 추측하지만 어떻게 수정할 수 있을지 잘 모르겠습니다.

2024-01-25 05:07 UTC, protocorn93 requested changes
두 분 쉽지 않은 스탭인데 고생 많으셨어요. 

전체적으로 델리게이트를 통해 역할을 위임하는 것에 대한 고민이 좀 더 필요해보여요. 또한 UI는 최대한 비즈니스 로직에 관해선 모르도록 작성해주시는 연습이 필요해보여요. 

## 질문에 대한 저의 생각 

1. Cell의 재사용 이슈 

코드로 보았을 때 prepareForReuse에서 배경색이나 텍스트를 초기화 해주는 코드는 보이지 않던데, 이곳에서 두 설정을 초기화 해보셨을까요?

2. 로딩 뷰 레이아웃 이슈

코드로 보았을 때 loadingView의 제약을 보면 height, top, leading만 주어져 있는데, top, leading, trailing, bottom을 주고 width, height를 준다면 셀도 그 크기에 맞춰질 것 같은데 이렇게 수정해보셨을까요?

2024-01-25 05:07 UTC, protocorn93 commented on ChatBot/ChatBot/ChattingViewController.swift
> +    }
`chatStackView`가 필요한가요? `view`에 `collectionView`와 `chatTextInputView`를 바로 붙여도 무방하지 않나요?

2024-01-25 05:07 UTC, protocorn93 commented on ChatBot/ChatBot/DTO/CommonModel.swift
> +    var content: String?
`var`로 선언한 이유가 있을까요?

2024-01-25 05:07 UTC, protocorn93 commented on ChatBot/ChatBot/ChattingViewController.swift
> +        let collectionView = ChatCollectionView(frame: .zero, collectionViewLayout: layout)
`ChatCollectionView`에 `collectionViewLayout`은 외부에서 주입해서 사용하도록 구현하신 이유가 궁금해요

2024-01-25 05:07 UTC, protocorn93 commented on ChatBot/ChatBot/Utility/ChatService.swift
> +        }
개인적으론 Encode, Decode도 네트워크 매니저의 역할로 가져가면 좋겠네요. 

코어 객체인 NetworkManager를 사용하는 특정 도메인 API 객체는 RequestDTO만 전달하고 결과는 ResponseDTO로 변환만하는 작업만 담당 좋은 것 같아요.

2024-01-25 05:07 UTC, protocorn93 commented on ChatBot/ChatBot/Utility/ChatService.swift
> +}
코어 네트워크 객체를 갖는 도메인 API 네트워크 객체는 구현은 숨기고 명확한 인터페이스를 제공해요. 이 ChatService로 모든 API 호출을 담당하도록 구현되는 것은 변경에 취약한 것 같아요. 

```swift 
protocol OpenAPIChatRepository { 
  func foo(request: FooRequestDTO)
  func boo(request: BooRequestDTO)
}

final class OpenAPIChatRepositoryImpl: OpenAPIChatRepository { 
  private let networkManager: NetworkManager 

  func foo(request: FooRequestDTO) { 

  }
  
  func boo(request: BooRequestDTO) { 

  }
}
```

2024-01-25 05:07 UTC, protocorn93 commented on ChatBot/ChatBot/View/ChatTextInputView.swift
> +    weak var delegate: ChatCollectionViewDelegate?
`ChatCollectionViewDelegate`는 네이밍만 보면 `ChatCollectionView`의 역할을 위임하는 친구 같아요. 실제로 사용처를 보면 `ChatTextInputView`의 역할을 위임하고 있는데 말이죠. 

여기선 `ChatTextInputViewDelegate`가 더 적절해보여요.

2024-01-25 05:07 UTC, protocorn93 commented on ChatBot/ChatBot/View/ChatTextInputView.swift
> +        delegate?.addChatRecord(text: textView.text)
UI에서 발생한 이벤트를 전달하는 인터페이스에요. `delegate?.buttonDidTapped`와 같이 버튼이 눌렸어! 라는 이벤트만 전달하는게 UI 컴포넌트 델리게이트 메서드의 역할이라고 생각해요.

2024-01-25 05:07 UTC, protocorn93 commented on ChatBot/ChatBot/View/ChatTextInputView.swift
> +        }
마찬가지로 `updateCollectionViewFromResponse`는 UI가 알아야 할 것이 아니에요. UI는 단순히 행위에 대한 것만 전달해주면 위로 위로 되어요. 이런 이벤트는 비즈니스 로직을 담당하는 객체까지 올라가 비즈니스 객체의 판단하에 비즈니스 로직이 수행되어야 해요. (ex api call)

그리고 다시 위에서 아래로 결과를 내려주고 이에 따라 UI는 다시 그려주기만 하면되구요.

2024-01-25 05:07 UTC, protocorn93 commented on ChatBot/ChatBot/View/ChatBalloonCell.swift
> +        chatBalloonView.commonLabelConstraintIsActive(bool: false)
여기서 `chatBallonView`의 텍스트나 배경색도 초기화를 해주어야 하지 않을까요?

2024-01-25 05:07 UTC, protocorn93 commented on ChatBot/ChatBot/View/ChatBalloonCell.swift
> +final class ChatBalloonCell: UICollectionViewListCell {
전 ChatBalloonCell은 역할에 따라 분리해내는게 좋을 것 같아요. 채팅 메시지에도 정말 다양한 속성이 존재할 수 있는데 이에 따라 하나의 ChatBalloonCell안에서 분긱 들어가면 너무 복잡해질 것 같아요. 

채팅 메시지의 속성에 따라 발생할 수 있는 UI 이벤트도 다를 수 있구요. (클릭에 따른 복사, 답장 등)

2024-01-25 05:07 UTC, protocorn93 commented on ChatBot/ChatBot/View/ChatCollectionView.swift
> +    weak var chatServiceDelegate: ChatServiceDelegate?
UI 컴포넌트의 델리게이트에 있어 그 역할에 대해 좀 더 고민해보시면 좋을 것 같아요. 관련한 코멘트는 아래에 남겨두었어요.

2024-01-25 05:07 UTC, protocorn93 commented on ChatBot/ChatBot/View/ChatCollectionView.swift
> +        diffableDataSource = UICollectionViewDiffableDataSource<Section, UUID>(collectionView: self, cellProvider: { collectionView, indexPath, uuid in
전 보통 복잡한 타입은 객체 상단에 정의해두곤해요. 

```swift 
typealias CellRegistration = UIColletionView.CellRegistration<ChatBalloonCell, UUID>
typealias DiffableDataSource = UICollectionViewDiffableDataSource<Section, UUID>
```

2024-01-25 05:07 UTC, protocorn93 commented on ChatBot/ChatBot/View/ChatCollectionView.swift
> +    }
UI가 비즈니스 로직을 수행하도록 두지 마세요. UI는 이벤트를 전달하고 데이터를 받아 UI를 갱신하도록만 해보세요.

2024-01-25 05:07 UTC, protocorn93 commented on ChatBot/ChatBot/View/ChatCollectionView.swift
> +                              animated: false)
이 동안 UI가 멈춰있지는 않을까요?

2024-01-25 05:07 UTC, protocorn93 commented on ChatBot/ChatBot/View/ChatTextInputView.swift
> +        }
이 영역을 블록으로 감싼 이유가 있으실까요?

2024-01-25 05:07 UTC, protocorn93 commented on ChatBot/ChatBot/View/ChatTextInputView.swift
> +final class ChatTextInputView: UIStackView {
`ChatTextInputView`가 `UIStackView`를 상속받아서 얻을 수 있는 장점은 무엇이 있나요?

2024-01-25 05:07 UTC, protocorn93 commented on ChatBot/ChatBot/View/ChatBalloonCell.swift
> +        ]
로딩뷰도 superview에 꽉 맞춰주어야 영역을 잘 잡을 수 있지 않을까요?

2024-01-25 05:34 UTC, KSK9820 commented on ChatBot/ChatBot/ChattingViewController.swift
> +    }
처음에는 TextView의 높이가 커지는 만큼 CollectionView가 자동으로 줄어드는 것을 기대하고 StackView에 넣었는데, 해당 기능이 구현되지 않아서 StackView를 제거하고 View에 바로 CollectionView와 ChatTextInputView를 붙였습니다!

2024-01-25 05:37 UTC, KSK9820 commented on ChatBot/ChatBot/DTO/CommonModel.swift
> +    var content: String?
var로 선언한 이유는 API의 응답을 받기전 Message가 ""으로 저장되어 있고, 응답을 받으면 Message 전체를 통으로 바꾸지 않고, 이미 생성된 UUID를 유지하면서 contents만 변경하도록 하기 위해서 입니다.

2024-01-25 05:48 UTC, snowy-summer commented on ChatBot/ChatBot/ChattingViewController.swift
> +        let collectionView = ChatCollectionView(frame: .zero, collectionViewLayout: layout)
override init을 사용하려고 그렇게 했습니다. 다시 생각해보니 밖에서 layout을 생성해 인자로 받아오는 것 보다 init단계에서 내부적으로 layout을 생성해 super.init에 넣어 주는 방식으로 변경을 했습니다.

2024-01-25 07:28 UTC, KSK9820 commented on ChatBot/ChatBot/Utility/ChatService.swift
> +}
OpenAIServiceProtocol를 만들어 chatService를 제외한 다른 api를 이용해 다른 서비스를 제공하도록 변경하였습니다.

2024-01-26 11:11 UTC, KSK9820 commented on ChatBot/ChatBot/Utility/ChatService.swift
> +        }
ChatService에서 encoded를 하고, decoded된 결과를 가공하여 최종 ChatRecord를 ViewController에게 전달하는 방식으로 변경하였습니다.

2024-01-26 11:12 UTC, snowy-summer commented on ChatBot/ChatBot/View/ChatTextInputView.swift
> +    weak var delegate: ChatCollectionViewDelegate?
ChatTextInputViewButtonDelegate로 변경을 하였습니다.

2024-01-26 11:13 UTC, KSK9820 commented on ChatBot/ChatBot/View/ChatTextInputView.swift
> +        delegate?.addChatRecord(text: textView.text)
ChatTextInputView에서 새로운 Message를 추가해서 통신이 시작되게 하지 않고, 버튼이 눌렸어!를 ViewController에게 전달해서 ViewController가 request를 보내도록 수정하였습니다.

2024-01-26 11:15 UTC, KSK9820 commented on ChatBot/ChatBot/View/ChatTextInputView.swift
> +        }
ChatService에서 응답을 보내고 받는 과정을 모두 처리한 후에 결과만을 ViewController에 전달하여 ViewController가 UI 업데이트를 시키도록 변경하였습니다.

2024-01-26 11:17 UTC, KSK9820 commented on ChatBot/ChatBot/View/ChatBalloonCell.swift
> +        chatBalloonView.commonLabelConstraintIsActive(bool: false)
chatBalloonView를 입력과 응답이 함께 사용하지 않고 leftBalloonCell와 rightBalloonCell로 나누어서 각각의 초기화를 진행하는 방식으로 변경하면서 색상에 대한 재사용 문제는 발생하지 않게끔 변경하였습니다.

2024-01-26 11:18 UTC, KSK9820 commented on ChatBot/ChatBot/View/ChatBalloonCell.swift
> +final class ChatBalloonCell: UICollectionViewListCell {
chatBalloonView를 입력과 응답이 함께 사용하지 않고 leftBalloonCell와 rightBalloonCell로 나누어서 서로 다른 제약을 각각의 view에서 (right의 경우 한 번만, left의 경우 해당 메세지의 내용에 따라 분기처리만 함) 설정하도록 변경하였습니다.

2024-01-26 11:19 UTC, KSK9820 commented on ChatBot/ChatBot/View/ChatCollectionView.swift
> +        diffableDataSource = UICollectionViewDiffableDataSource<Section, UUID>(collectionView: self, cellProvider: { collectionView, indexPath, uuid in
해당 부분 반영하였습니다! 감사합니다:)

2024-01-26 11:20 UTC, snowy-summer commented on ChatBot/ChatBot/View/ChatCollectionView.swift
> +        diffableDataSource = UICollectionViewDiffableDataSource<Section, UUID>(collectionView: self, cellProvider: { collectionView, indexPath, uuid in
extension으로 추가를 해서 diffableDatasource를 사용하는 부분의 위쪽에 typealias를 사용하여 정의를 해두었습니다.

2024-01-26 11:22 UTC, KSK9820 commented on ChatBot/ChatBot/View/ChatCollectionView.swift
> +    }
ViewController, View, Service로 분리하였습니다.
View에서 이벤트가 입력되면 CollectionView가 그 이벤트를 받아서 Service에게 이벤트를 처리하도록 지시하고
이벤트를 수행을 완료한 Service가 그 처리를 CollectionView에게 알리면 CollectionView가 View에게 UI갱신을 지시하게 변경하였습니다.

혹시 이런 역할의 분리가 MVC가 맞을까요?

2024-01-26 11:23 UTC, KSK9820 commented on ChatBot/ChatBot/View/ChatBalloonCell.swift
> +        ]
lodingView의 경우에는 생성시에 frame의 크기를 지정하기 때문에 top과 leading의 위치만을 잡아주게끔 constraint를 잡았습니다.

2024-01-26 11:31 UTC, KSK9820 commented on ChatBot/ChatBot/View/ChatTextInputView.swift
> +final class ChatTextInputView: UIStackView {
UIStackView를 상속받지 않고 UIView를 상속받으면 내부에서 stackview를 생성해야하는 번거로움이 있어서 UIStackView를 상속받도록 하였습니다. 혹시 다른 장점이 또 있을까요??

2024-01-26 11:39 UTC, snowy-summer commented on ChatBot/ChatBot/View/ChatTextInputView.swift
> +        }
감싸지 않으면 버튼이 원이 아닌 사각형으로 나오기 때문에  main.async로 감싸주었습니다. 혹시 다른 방법도 있을까요?
<img width="356" alt="image" src="https://github.com/tasty-code/ios-chat-bot/assets/118453865/7d5a7bda-c8fa-4de5-8658-6cfbe8cd25a6">

2024-01-26 11:42 UTC, snowy-summer commented on ChatBot/ChatBot/View/ChatCollectionView.swift
> +                              animated: false)
받아온 데이터를 사용해야 하기 때문에 멈춰있어도 문제가 없다고 생각합니다.

2024-01-29 05:19 UTC, protocorn93 commented on ChatBot/ChatBot/View/ChatCollectionView.swift
> +    }
네네 다만 MVC로 접근하기보단 객체의 역할을 나눈 것으로 이해하시면 좋을 것 같아요! MVC도 결국 이러한 객체의 역할 나누기의 패턴화이기 때문에 아키텍처에 집중하기보단 역할을 나누었다에 집중해주시면 좋을 것 같아요!

2024-01-29 05:20 UTC, protocorn93 commented on ChatBot/ChatBot/View/ChatTextInputView.swift
> +final class ChatTextInputView: UIStackView {
아뇨. 단순히 의도가 궁금했어요! 이해했어요!

2024-01-29 05:21 UTC, protocorn93 approved these changes

2024-01-29 05:21 UTC, merged