AI 챗봇 앱 [STEP3] Comdori, 요한
tasty-code/ios-chat-bot pull request #27
Opened 2024-01-23 08:42 UTC by comdori-wj

리뷰어: @zdodev

안녕하세요 소대! 이번 스텝은 요구사항도 많았고, 어려워 가지고 오래 걸렸습니다.. 😂
STEP3 PR 보냅니다. 잘 부탁드립니다~

<br/> 

### 구현 사항
- [x] Safe Area을 고려한 오토레이아웃 구현
- [x] Collection View List의 활용
- [x] Modern Collection View 활용
- [x] Core Graphics와 Core Animation의 활용
- [x] 채팅 대화의 연속성
- [x] 빈공간을 누르거나, 컬렉션뷰를 탭 또는 하단 방향으로 드래그 할때 키보드가 내려감
- [x] 키보드가 올라가고 내려갈 떄, 입력칸이 키보드를 따라다닐수 있도록 구현
- [x] 네트워크 문제등, 채팅 메시지가 전송 안되었을 때 사용자에게 알림 구현 

<br/> 

### 스크린샷

|구현 내용 | 이미지 |
| --- | --- |
|채팅창, 대화 연속성 테스트|![채팅창, 대화 연속성](https://github.com/tasty-code/ios-chat-bot/assets/22284092/dd2e06cc-79a9-4625-91f1-959980d1719b)|
|긴 대화 내용 및 마지막 대화 내용 자동 스크롤|![긴 대화 내용 및 마지막 대화 내용 자동 스크롤](https://github.com/tasty-code/ios-chat-bot/assets/22284092/19284e7d-5e9e-494e-a4ab-0fbf6b97e3ce)|
|채팅 동적 입력 테스트|![채팅 동적 입력 테스트](https://github.com/tasty-code/ios-chat-bot/assets/22284092/a8d1da1d-2c00-40bc-875b-634c869fc196)|
|아이폰 키보드 테스트|![아이폰 키보드 테스트](https://github.com/tasty-code/ios-chat-bot/assets/22284092/9288deae-a82e-4497-9fb6-057631697e49)|
|사용자 오류 알림|![사용자 오류 알림](https://github.com/tasty-code/ios-chat-bot/assets/22284092/e18cfd91-fceb-4264-b45f-9c36600cea47)|

<br/> 

## 핵심 클래스 설명

| 이름 | 타입 | 구현내용 |
| --- | --- | --- |
| ChatContentView | Class | configure이 바뀔 때마다(=cell의 content가 변경될 경우) sender에 따라 설정을 해주는 클래스 |
| ChatCollectionViewCell | Class | configure에 변화가 있을 때 content, sender를 수정 후 configure을 업데이트하는 셀을 커스텀 한 클래스 |
| BubbleView | Class | sender에 따라 말풍선을 그려주는 클래스 |

<br/>

## 궁금한 점 
- 대화 내용이 길거나 컬렉션뷰를 스크롤 했을때 말풍선이 깨지는 현상이 발생 하였습니다. 그 이유가 셀이 재사용 될 때 오토레이아웃과 제약조건이 다시 안그려져서 발생하는 이유를 알았습니다. 이 현상을 해결하고자 메시지 주체자(sender)에 따라서 분기처리 하였으며, 말풍선이 그려지기 전에 `setNeedsDisplay()` 를 호출하여 말풍선이 깨지지 않게는 하였으나, 여전히 콘솔 로그창에는 오류가 발생하고 있습니다. 이 문제를 어떻게 하면 해결 할 수 있을지 궁금합니다. 오류 로그를 첨부 합니다.

```
Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
	(Note: If you're seeing NSAutoresizingMaskLayoutConstraints that you don't understand, refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints) 
(
    "<NSAutoresizingMaskLayoutConstraint:0x60000216f0c0 h=--& v=--& ChatBot.ChatContentView:0x106235ae0.width == 361   (active)>",
    "<NSLayoutConstraint:0x60000216f700 ChatBot.BubbleView:0x106219b10.width <= 300   (active)>",
    "<NSLayoutConstraint:0x60000216efd0 ChatBot.BubbleView:0x106219b10.trailing == UILayoutGuide:0x600003b00c40'UIViewSafeAreaLayoutGuide'.trailing - 10   (active)>",
    "<NSLayoutConstraint:0x60000216def0 ChatBot.BubbleView:0x106219b10.leading == UILayoutGuide:0x600003b00c40'UIViewSafeAreaLayoutGuide'.leading - 3   (active)>",
    "<NSLayoutConstraint:0x60000216f610 'UIViewSafeAreaLayoutGuide-left' H:|-(0)-[UILayoutGuide:0x600003b00c40'UIViewSafeAreaLayoutGuide'](LTR)   (active, names: '|':ChatBot.ChatContentView:0x106235ae0 )>",
    "<NSLayoutConstraint:0x60000216d540 'UIViewSafeAreaLayoutGuide-right' H:[UILayoutGuide:0x600003b00c40'UIViewSafeAreaLayoutGuide']-(0)-|(LTR)   (active, names: '|':ChatBot.ChatContentView:0x106235ae0 )>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x60000216f700 ChatBot.BubbleView:0x106219b10.width <= 300   (active)>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.
```
- 또한 Warning으로 deadlock 문제가 발생할 수도 있다는 로그가 뜨는데, 로그 메세지를 봐도 어느 부분이 문제를 초래하는지 잘 모르겠습니다.
```
Warning: applying updates in a non-thread confined manner is dangerous and can lead to deadlocks. Please always submit updates either always on the main queue or always off the main queue - view=<UICollectionView: 0x111017800; frame = (16 59; 361 719); clipsToBounds = YES; autoresize = W+H; gestureRecognizers = <NSArray: 0x600000c939c0>; backgroundColor = <UIDynamicSystemColor: 0x600001747e00; name = systemBackgroundColor>; layer = <CALayer: 0x600000248f80>; contentOffset: {0, 1882}; contentSize: {361, 2601}; adjustedContentInset: {0, 0, 0, 0}; layout: <UICollectionViewCompositionalLayout: 0x112028ee0>; dataSource: <_TtGC5UIKit34UICollectionViewDiffableDataSourceSiV7ChatBot4Chat_: 0x600000014530>>
```

2024-01-24 02:27 UTC, comdori-wj commented
마지막 리팩터 후 궁금한 점으로 질문한 deadlock을 유도할 수 있는 warning이 발생하지 않고 있습니다. 정확한 이유와 해결된 이유는 잘 모르겠으나 알려드려야 할 것 같아 남깁니다!

2024-01-24 12:52 UTC, zdodev requested changes
안녕하세요. @comdori-wj , @dpwns1234 !

Step3 잘 구현해보셨네요.👍👍
GPT와 대화를 잘 해볼 수 있었어요!
컬렉션뷰+채팅이 쉽지 않았을텐데 커스텀뷰, Configuration, DiffableDataSource 를 잘 사용해주셨어요😁

몇 가지 코멘트를 남겨보았습니다! 
같이 의견 나눠보면 좋을 것 같습니다.

2024-01-24 12:52 UTC, zdodev commented on ChatBot/ChatBot/Views/ChatContentView.swift
> +    private lazy var bubble: BubbleView = {
`bubbleView` 이름은 어떨까요?🙂

2024-01-24 12:52 UTC, zdodev commented on ChatBot/ChatBot/Views/ChatContentView.swift
> +    private var loadingConstraints: [NSLayoutConstraint]!
현재는 `init` 메서드에서 모든 프로퍼티에 값을 할당하고 있어서 에러가 발생하지 않지만,
지금과 같은 경우 강제 언래핑 프로퍼티를 초기화하는 구문을 추가하거나 수정하게 된다면 런타임 에러가 발생할 수 있을 것 같습니다.
꼭 강제 언래핑을 사용해야 하는지, 강제 언래핑을 사용하더라도 안전하게 사용할 수 있는 장치가 없는지 고민해보면 좋을 것 같습니다!

2024-01-24 12:52 UTC, zdodev commented on ChatBot/ChatBot/Views/ChatContentView.swift
> +    private func setConstraints() {
오토레이아웃 경고에 대한 질문에 대해서 오토레이아웃의 `priority`에 대한 내용을 더 파악해보면 좋을 것 같습니다~
오토레이아웃의 경우 해결방법이 다양하지만, `priority` 개념을 통해 해결할 수 있을 것 같습니다!

2024-01-24 12:52 UTC, zdodev commented on ChatBot/ChatBot/Views/ChatContentConfiguration.swift
> +struct ChatContentConfiguration: UIContentConfiguration, Hashable {
`UIContentConfiguration` 을 사용해보셨네요.👍

2024-01-24 12:52 UTC, zdodev commented on ChatBot/ChatBot/Views/DotsView.swift
> +    lazy var dotSpacing: CGFloat = 25
아래 프로퍼티와 다르게 해당 프로퍼티들은 `private`을 따로 사용하지 않은 이유가 있을까요?

2024-01-24 12:52 UTC, zdodev commented on ChatBot/ChatBot/ChatViewController.swift
> +
다른 프로퍼티 정의와 다르게 공백을 삽입한 이유가 있을까요?

2024-01-24 12:52 UTC, zdodev commented on ChatBot/ChatBot/ChatViewController.swift
> +    typealias ChatDataSource = UICollectionViewDiffableDataSource<Int, Chat>
`DiffableDataSource`를 사용해보셨네요.👍

2024-01-24 12:52 UTC, zdodev commented on ChatBot/ChatBot/ChatViewController.swift
> +        configureCellRegistration()
각 역할별로 메서드를 분리해서 구현해보셨네요.👍

2024-01-25 01:11 UTC, comdori-wj commented on ChatBot/ChatBot/Views/ChatContentView.swift
> +    private lazy var bubble: BubbleView = {
네 좋은것 같습니다. 수정할께요 😎

2024-01-25 01:38 UTC, dpwns1234 commented on ChatBot/ChatBot/Views/ChatContentView.swift
> +    private var loadingConstraints: [NSLayoutConstraint]!
초기화 구문을 새로 추가하거나 수정할 경우를 생각하지 못해서 강제 언래핑을 사용했었습니다.
특정 init에서 값을 할당하지 않고, lazy 키워드를 사용해 선언과 동시에 같이 정의하도록 코드를 수정하였습니다!

2024-01-25 01:46 UTC, dpwns1234 commented on ChatBot/ChatBot/ChatViewController.swift
> +
다른 프로퍼티의 경우 컴도리가 구현하고 해당 프로퍼티는 제가 구현하여 서로 다른 코드 스타일로 발생하게 되었습니다. 통일성을 위해 수정하겠습니다!

2024-01-25 01:50 UTC, dpwns1234 commented on ChatBot/ChatBot/Views/DotsView.swift
> +    lazy var dotSpacing: CGFloat = 25
놓친 부분입니다. 수정하겠습니다!

2024-01-25 06:15 UTC, comdori-wj commented on ChatBot/ChatBot/Views/ChatContentView.swift
> +    private func setConstraints() {
각각 constraint의 우선순위를 낮음으로 지정하여 해결하였습니다. 
덕분에 오토레이아웃의 개념을 다시 한번 확인 할 수 있었습니다.

2024-01-25 14:16 UTC, zdodev approved these changes
안녕하세요. @comdori-wj , @dpwns1234 !

코멘트에 대해서 잘 개선해보셨습니다!
코멘트에 대해서 의견을 잘 남겨주시고, 개선 단위별로 커밋을 나누신 점도 좋았습니다👍

Step 3는 여기서 마무리하도록 하겠습니다.🎉

2024-01-25 14:16 UTC, zdodev commented on ChatBot/ChatBot/Views/DotsView.swift
> +    private lazy var dotSpacing: CGFloat = 25
좋습니다👍

2024-01-25 14:16 UTC, zdodev commented on ChatBot/ChatBot/Views/ChatContentView.swift
> +        }
오토레이아웃에서 많이 다루는 부분입니다! 좋습니다👍

2024-01-25 14:16 UTC, zdodev commented on ChatBot/ChatBot/Views/ChatContentView.swift
> +    ]
보다 안전한 코드가 되었네요👍

2024-01-25 14:17 UTC, merged