Feat/step1
tasty-code/ios-chat-bot pull request #34
Opened 2024-03-28 11:39 UTC by hemil0102

안녕하세요 July(@July911), 진 해리입니다. 
AI Chatbot app 과제 STEP1 PR을 드립니다. 
잘 부탁드리겠습니다. 😉

# 🔍 What is this PR?

- OpenAI API reference 문서의 데이터 형식을 고려하여 모델 타입을 구현합니다.

**핵심경험**
- Request 및 Response를 위한 데이터 모델 설계
- CodingKeys 프로토콜의 활용

</br>

# 🗂️ 프로젝트 구조

- STEP1은 명세서에서 요구한 모델 위주로만 구현되어 있습니다. 

</br>

# 📝 PR 고민 Point

### 1. Request, Response DTO 개체의 구현
https://platform.openai.com/docs/api-reference/chat
문서에 따라 DTO를 구현하려고 생각 했습니다.
예제에서 요구하는건 개체중 일부만 사용하는데, DTO가 모든 개체를 요구, 응답 받을 수 있는 형태로 구현하는 방법에 대해서 고민했습니다.

### 2. DTO Codable, Encodable, Decodable에 대한 설정
이번 과제는 지난 박스오피스와 달리 POST를 수행하며, 해당 과정에서 Encoding을 수행합니다. 
이에 일부 DTO 모델은 Codable로 설정해주었습니다. (예: GPTMessageDTO 참고)

### 3. GPTBody
gpt의 model과 role은 특정 case를 다루므로 enum으로 설정 값을 만들어주었습니다. 

### 4. Serializer
POP를 활용하고 싶어서 Serializer의 Decoder, Encoder를 프로토콜로 추상화하여 설계하였습니다. 

Decoder는 ViewController를 통해 loadData() 메서드를 통해 만들어진 json 파일의 값을 설계한 DTO로 Decode 해줍니다.

Encoder는 ViewController에 makeHTTPBody() 메서드를 통해 설계한 DTO를 Encode 해줍니다. loadEncodingData()를 통해서 해당 데이터를 다시 decode하여 확인합니다. 

# ❓ 질문 Point
1. Request Body의 Messages를 모델 설계할 때 내부의 각각의 System, User, Assitant, Tool, Function을 모두 대응 하려고 하였는데, 어떻게 설계를 해주는 것이 좋을지 궁금합니다. 시도를 해본 것은 프로토콜을 통해 추상화하여 설계를 하고자 하였는데 Messages가 프로토콜을 타입으로 지정 해 줄 경우 codable을 준수하지 않는다는 에러로 해결 방법을 찾지 못해서 안되었고 Message에 필요한 모든 개체를 만들어서 옵셔널 처리로 구현을 하려 했지만 좋은 방법은 아니라고 판단하여 예제에서만 사용하는 개체만 만들어 주었습니다. 모든 개체를 다 대응 할 수 있게 만드려면 어떻게 구현해야 할까요. 그리고 근본적으로 이렇게 요청, 응답을 다 대응 해주는게 올바른 고민인지 궁금합니다.

2. OpenAI 라이브러리? 
과제를 수행하다가 OpenAI 라이브러리가 있다는 것을 알게 되었고, 해당 라이브러리에서 모델을 살펴보면 보다 세세하게 구현된 모델이 있습니다. 현업에서는 모델을 직접 구현하시는지 OpenAI 라이브러리를 가져와서 사용하시는지 궁금합니다. 

3. 모델 확장성? 
현재는 과제에 필요한 부분만 모델 설계를 하였는데, 추후 확장성을 고려하게 된다면 어떤 부분들이 고려되면 좋을까요? 

📸 Screenshot
main 콘솔 확인 화면
![image](https://github.com/tasty-code/ios-chat-bot/assets/83139316/ae78703b-9978-41d6-9d1b-937612beeed6)

2024-03-31 01:28 UTC, July911 requested changes

2024-03-31 01:28 UTC, July911 commented on ChatBot/ChatBot/DTO/GPTBody.swift
> +import Foundation
위에 날짜와 파일이름을 삭제하신 이유가 있나요 ?

2024-03-31 01:28 UTC, July911 commented on ChatBot/ChatBot/DTO/GPTMessageDTO.swift
> +    enum CodingKeys: String, CodingKey {
외부에서 접근이 필요할까요 ?

2024-03-31 01:28 UTC, July911 commented on ChatBot/ChatBot/DTO/GPTMessageDTO.swift
> +            case content, role
인덴트가 안맞는 것 같습니다.

2024-03-31 01:28 UTC, July911 commented on ChatBot/ChatBot/Serializer/JsonDecodeable.swift
> +    private let jsonDecoder: JSONDecoder
JsonDecoder 안에 jsonDecoder 가 있는건 어색한거 같습니다.

2024-04-01 01:46 UTC, July911 requested changes

2024-04-01 01:46 UTC, July911 commented on ChatBot/ChatBot/Serializer/JsonEncoder.swift
> +class JsonEncoder: JsonEncodableProtocol {
따로 빼신 이유가 있을까요 ? 있다면 설명해주세요 !

2024-04-01 07:04 UTC, hemil0102 commented on ChatBot/ChatBot/DTO/GPTBody.swift
> +import Foundation
작성한 코드를 확인할 때 위에서 부터 읽어 내려가는데, 바로 바로 빠르게 코드를 확인하고 싶어서 삭제해주었습니다!

2024-04-01 07:09 UTC, hemil0102 commented on ChatBot/ChatBot/DTO/GPTMessageDTO.swift
> +    enum CodingKeys: String, CodingKey {
아~ 이 부분은 지난번 과제에서도 리뷰 받았던 부분인데 모델 설계가 익숙치 않아서 누락되었네요. 
기본기 챙겨주셔서 감사합니다. 

수정 사항 반영: ba35e7a196f50df1d971d71c7133652225a65a33

2024-04-01 07:19 UTC, wlsdud-dev commented on ChatBot/ChatBot/DTO/GPTMessageDTO.swift
> +            case content, role
수정 했습니다.

2024-04-01 07:20 UTC, wlsdud-dev commented on ChatBot/ChatBot/Serializer/JsonDecodeable.swift
> +    private let jsonDecoder: JSONDecoder
JsonDecoder.decoder 형식으로 수정 해줬습니다.
인코더도 마찬가지로 수정 했습니다.

2024-04-01 07:24 UTC, hemil0102 commented on ChatBot/ChatBot/Serializer/JsonEncoder.swift
> +class JsonEncoder: JsonEncodableProtocol {
프로토콜로 설계하고 주입식으로 설계한 이유는 encoder의 설정값을 변경하여 주입하여 사용하기 위해서 빼주었고, 
decoder랑 쌍으로 뭔가 대칭 구조로 설계해놓는게 저에게는 가독성이 좋아보여서 따로 빼준 것도 있습니다. 
한줄로 작성되는 코드여서 굳이 따로 뺄 필요가 있을까 싶기는 한데요. 
보통 따로 빼서 사용하지 않는지? 어떤 식으로 사용하는지 알려주시면 감사드리겠습니다! 😄

2024-04-02 02:18 UTC, merged