AI 챗봇 앱 [Step 1] Hoi, Andy
tasty-code/ios-chat-bot pull request #35
Opened 2024-03-28 15:22 UTC by happykwon

안녕하세요 그린 @GREENOVER , 만나서 반갑습니다! 😆
AI챗봇애 STEP1 PR 드립니다.

조언 및 미흡한 부분에 대한 건의 언제나 환영하며,
솔직하게 리뷰를 해주시면 어떤 부분이든 달게 고찰해보고 반영하려고 노력해보겠습니다.
PR이 읽기 어렵거나 보충 설명이 필요한 부분도 언제든 DM 부탁드립니다.
감사합니다! 🔥

## 🔍 What is this PR?

### STEP1 , STPE2 
**구현 요구사항** 
-  Request 및 Response를 위한 데이터 모델 설계
-  CodingKeys 프로토콜의 활용
- 네트워크 통신을 담당할 타입을 설계하고 구현합니다.
- 메세지를 보내고, 그에 대한 응답 메세지를 받아서 출력하기
- API에 Request할 때 파라미터 중 stream을 false로 하여 통신하도록 구현해봅니다.

챗봇을 위한 모델을 구현했습니다.
.

## 📝 PR Point

### **Model 설계**
저희가 구현하고 자했던 DataFlow는 아래와 같습니다.
`[사용자가 채팅 입력 ->  Request -> OpenAI -> 데이터 가공 -> UI 화면에 보여짐]`  반복
실시간 채팅이고 API문서를 읽어보니 이전 대화 내용의 모든 부분을 계속 같이 보내줘하기 하기 때문에 첫 `Request`부터 모든 메세지 내용의 데이터를
관리해줄  객체에 대한 필요성을 느꼈습니다. 
`MVVM` 패턴에 데이터를 관리하는`Repository`객체를 추가해서 크게 `/ 데이터 관리 / 통신 / View에 전달 / ` 이렇게 세 부분으로 정리했습니다.

### **구현사항**
### **Repository**
`MessageRepository`는 대화의 메시지들을 관리합니다.

### **Model**
`OpenAICheatResponseDTO`:  OpenAI API의 응답 DTO 모델입니다.
`OpenAICheatResponseDTO`: API 응답의 최상위 구조를 나타냅니다. 내부에는 응답과 관련된 메타데이터와 함께 Choice 배열이 포함됩니다.
`RequestMessageModel`:  요청을 보낼때 데이터 형태를 정의합니다.
`ResponseMessageModel`: `OpenAICheatResponseDTO`로 받은 데이터를 변환합니다.

### **ViewModel**
`ChatViewModel`: 뷰와 모델 사이의 상호작용을 처리합니다. 사용자의 메시지를 처리하고, API 서비스를 통해 메시지를 전송한 후 응답을 관리합니다.

### **Network**
`OpenAIService`: API통신을 담당합니다.
`OpenAIEndPoint`: API 요청을 위한 엔드포인트와 HTTP 메서드를 정의합니다.

## ❓질문
### 1. DataFlow
지금 프로젝트처럼 요청보낸 전체의 사항을 관리할 필요가 있을 때 현업에서는 보통 어떤식으로 처리할 수 있는지 궁금합니다. 

### 2. MVVM 모델 설계
MVVM 모델 설계는 처음이라서 모두가 알고 있는 설계로 나올지는 잘 모르겠습니다. 저희가 생각한 각 파트별 역할은 다음과 같습니다.
Model : 데이터 모델 그 자체 
View : ViewModel에서 데이터를 받아 UI를 그리는 역할
ViewModel:  Model에서 데이터를 받아 바인딩 및 관리하는 역할
ViewController : ... 어떤역을 하는지 감이 잘 오지 않습니다..
블로그들을 보면 MVC 모델의 ViewController에서 비즈니스 모델을 viewModel에 주고 난 형태라고 하는데 .. 이게 무엇을 뜻하는 건가요? 

### 3. 폴더링
이전 프로젝트에서도  폴더링에 있어 신경을 썼지만 파일이 많아지니 찾기가 힘들고 헷갈렸습니다.
혹시 그린만의 폴더링 팁이나 노하우 혹은 참고할만한 블로그나 자료등이 있다면 부탁드립니다 ! 

### 4. combine 사용 시기
UIKit에서 combine을 사용하는 대표적인 경우는 API통신을 할 때라고 알고있습니다. 
통신이 아닌 다른 부분에서도 combine을 사용하면 좋은 경우가 있는지 궁금합니다. 
또 UIKit에서는 did set / wil set  / notification 변화를 알려주고 감지 할 수 있는 reactive한 경험을 제공해 줄 수 있는 요소들이 많은데 
채용 공고를 보면 combine 혹은 RX의 경험을 요구하는 경우가 많이 있는데, 왜 이런 요구사항을 중요하게 써 놓는지 combine을 실제로 현업에서 많이 사용 하는지 궁금합니다.

2024-03-29 00:47 UTC, GREENOVER requested changes
@happykwon @andyanappdev 
스텝 1,2 수고 많으셨습니다!
처음부터 설계를 꼼꼼히 하시면서 나아가셔서 아주 기반이 탄탄하네요ㅎㅎ
리뷰 코멘트가 좀 많긴한데, 구조 자체가 잘못된건 전혀 없고 전체적으로 한번 생각해볼 포인트들에 대해서 남겨봤습니다 🙋🏻
***
### 칭찬 드리고 싶은  부분
- 전체적으로 코드 기반 구성을 아주 잘하셨네요 💯
- 코드 네이밍과 폴더화가 적절해서 파악하기 편했습니다 💯
***
### 궁금하신 부분에 대한 저의 의견 
- DataFlow
  - 말씀하신 전체의 사항이라는것의 의미를 명확히 이해하지 못했지만, 네트워킹을 통한 데이터와 그걸 VM단에 가져오기까지의 흐름을 말씀하시는거라면 지금 잘해주셨다고 생각합니다 😃
  지금과 같은 흐름으로 현업에서도 사용한다고 생각해도 좋을것 같아요!
-  MVVM 모델 설계
  - 다른건 잘 이해하신것같고, VC는 MVVM 구조속에서 뷰를 얹고 사용자의 인터랙션과 상호작용할 수 있는 창구라고 보면 좋을것 같습니다.
  즉, VC를 통해서 뷰의 인터랙션이 발생하면 VM을 통해 로직을 호출하고 적절한 수행을 해 뷰의 상태를 변경시키는 흐름에서 생각해보면 좋을것 같아요!
  그렇기에 뷰와 모호할 순 있지만, 사용자 인터페이스를 관리하는 역할이 주라고 보면 될것 같습니다.
  또한, VC가 있어야지 뷰라이프사이클이나 네비게이션 등의 관리가 이뤄지니까요 😃
- 폴더링
  - 이건 정말 스타일과 소속된 곳에서의 컨벤션 차이겠지만, 저는 주로 하나의 화면 단위 (예를들어, 홈, 마이, 설정 등)를 하나의 폴더로 구성하고 그 안에서 View, VM들을 관리합니다.
  모델은 지금 하신것처럼 모델 폴더로 별도 관리하는데 그 안에서도 폴더를 두어 마이에 대한 모델들을 응집시키는 형태로 구성합니다.
  네트워크 객체 등은 공통적인 부분으로 보아 Core라는 폴더를 두고 그 안에서 
각 화면 단에 대한것이 아닌 전체적으로 작용하는 녀석들을 또 폴더화 하여 관리합니다.
도움이 될만한 블로그나 레퍼는 저는 따로 기억나는건 없지만...
제가 예전에 관련하여 프로젝트 파일 구조에 대해 글을 써본것이 있는데 한번 공유드려 볼께요!
아키텍쳐나 설계에서 조금 차이는 있겠지만, 전체적인 기조를 보시면 좋을것 같습니다ㅎㅎ
![스크린샷 2024-03-29 오전 9 37 12](https://github.com/tasty-code/ios-chat-bot/assets/72292617/10535c3a-68c2-4ac6-83ce-074a0cc1b483)
https://green1229.tistory.com/273
- combine 사용 시기
  - 꼭 통신이 아니더라도 사용자 인터랙션 (입력과 같은~?) 이벤트 처리 시에도 충분히 사용될 수 있습니다.
  왜 그런데 말씀처럼 리액티브하게 구현할 수 있는데 왜 써야하냐~ 라고 한다면 꼭 써야하는 이유는 없습니다ㅋㅋ
  그런데 하시다보면 알겠지만, rx나 combine과 같은 프레임워크를 사용함으로써 작업자마다도 일관되고 수월하게 이벤트 처리를 위한 코드를 작성할 수 있다는것도 장점입니다.
  또한, 제공되는 여러 기능들이 많기에 굳이 다 일일히 만들어서 복잡하게 코드를 구현하는것보다 심플하고 사용성이 좋고 메모리 관리를 잘해놓은 이런 프레임워크를 채택하는것이 이득이라고 생각해서 사용하지 않을까 싶어요.
  예를들어 여러 데이터 이벤트 스트림을 합치고 필터링 시키고 하는 등등 복잡한 구현들을 쌩으로 구현하기보다 컴바인을 쓰면 여러 메서드가 제공되니 편리한 이점도 있습니다.
  그런 의미에서도 동료간의 협업이나 통일성을 위해서도 사용할 수 있구요!
  물론 이런 컴바인도 당연히 내부는 기초적인것들로 이뤄져있기 때문에 이건 중요하다기보다는 편리하다는 부분에서 인지하는것이 더 좋을것 같네요ㅎㅎ
  그렇기에 컴바인을 꼭 써야돼!라는것에 얽매이지 않으셨으면 좋겠어요.
  기업에서도 신입에게 중요한건 컴바인이나 알엑스를 써본 사람 보다 기초를 잘 알고 그걸 와서 공부해서 쓸 수 있는 사람을 원하기에 이걸 원하니까 써봐야지보다 직접 쌩으로 구현해보시면서 불편함을 느껴서 써봐야겠다! 이런 니즈를 가져가시는게 더 도움이 될것 같습니다.
  (컴바인도 이제 어떻게 보면 swift concurreny가 나온시점에서 점점 레거시긴해서...)
***
고생 많으셨습니다!
요구사항은 충분히 잘 만족하지만, 한번 더 점검차 Request Changes로 해놓겠습니다!
언제든지 재리뷰 요청해주세요~😃

2024-03-29 00:47 UTC, GREENOVER commented on ChatBot/ChatBot/App/SceneDelegate.swift
> +        self.window?.makeKeyAndVisible()     }
코드 종료 블럭이 같은 라인에 들어간것 같은데 한 라인 띄워도 좋을것 같아요~!

2024-03-29 00:47 UTC, GREENOVER commented on ChatBot/ChatBot/ViewModel/ChatViewModel.swift
> +class ChatViewModel {
더이상 상속하지 않는 클래스라면 final 키워드로 성능 이점을 가져가도 좋을것 같습니다 🙋🏻

2024-03-29 00:47 UTC, GREENOVER commented on ChatBot/ChatBot/ViewModel/ChatViewModel.swift
> +    }
적절한 라인 개행 처리를 해주는건 어떻게 생각하시나요?
가독성이 더 향상될것 같아서요 🤔

2024-03-29 00:47 UTC, GREENOVER commented on ChatBot/ChatBot/ViewModel/ChatViewModel.swift
> +    private let repository: MessageRepository
혹시나 추후 해당 VM에서 다른 레퍼지토리도 추가되면 해당 네이밍은 살아남기 힘든것 같은데 조금 더 구체적으로 네이밍을 해보면 어떨까요?

2024-03-29 00:47 UTC, GREENOVER commented on ChatBot/ChatBot/Model/OpenAICheatResponseDTO.swift
> +struct OpenAICheatResponseDTO: Codable {
response에 대한 DTO이기에 Encoding 할일이 있을까요~?

2024-03-29 00:47 UTC, GREENOVER commented on ChatBot/ChatBot/Model/ResponseMessageModel.swift
> +struct ResponseMessageModel: Codable {
실제로 OpenAICheatResponseDTO에 응답받아 디코딩된 값을 가지고 해당 모델을 거쳐 가공하여 연관된 VM에 데이터를 넣어주려고 만드신 객체로 이해했는데, 그렇다면 별도 통신 객체처럼 만들 필요가 있을지 궁금하고 어떤 의도로 구현하신건지 궁금합니다 🙋🏻
잘못되었다는것은 전혀아니고 흐름상 여러분들의 생각이 궁금해요ㅎㅎ

2024-03-29 00:47 UTC, GREENOVER commented on ChatBot/ChatBot/Model/RequestMessageModel.swift
> +struct RequestMessageModel: Codable {
Request 객체이기에 디코딩할 일이 있을까요~?

2024-03-29 00:47 UTC, GREENOVER commented on ChatBot/ChatBot/Network/APIKeyManager.swift
> +struct APIKeyManager {
enum과 struct 모두로 관리할 수 있을것 같은데 struct로 관리하신 이유가 궁금합니다 🙋🏻

2024-03-29 00:47 UTC, GREENOVER commented on ChatBot/ChatBot/Network/OpenAIEndPoint.swift
> +            preconditionFailure("URL Error: \(components)")
실제로 해당 에러방식을 사용하면 개발단에서는 유용하겠지만, 실제 상용되는 앱은 크래쉬가 나기에 조금 더 안전한 방식으로 에러 처리를 고안해보면 좋을것 같아요 🙋🏻
에러 부분에 있어 사용자에게 앱이 종료되지 않고 얼럿을 노출해준다던가 하는 등의 경험을 주면 어떨까요?

2024-03-29 00:47 UTC, GREENOVER commented on ChatBot/ChatBot/Network/OpenAIService.swift
> +class OpenAIService {
코드 사이 적절한 개행이 있으면 좋을것 같습니다!

2024-03-29 00:47 UTC, GREENOVER commented on ChatBot/ChatBot/Network/OpenAIService.swift
> +class OpenAIService {
서비스 객체를 class로 하신 이유가 궁금합니다 🙋🏻

2024-03-29 00:47 UTC, GREENOVER commented on ChatBot/ChatBot/Network/OpenAIService.swift
> +            "model": "gpt-3.5-turbo",
해당 model필드도 추후 환경마다 변경될 수도 있지 않을까요?
그렇기에 model과 messages를 묶은 RequestDTO를 두어 관리해도 좋지 않을까 싶긴합니다 🤔

2024-03-29 00:47 UTC, GREENOVER commented on ChatBot/ChatBot/Network/OpenAIService.swift
> +        let task = URLSession.shared.dataTask(with: request) { data, response, error in
response status code를 통해 에러를 체크하는 검증도 추가되면 어떨까요?

2024-03-29 00:47 UTC, GREENOVER commented on ChatBot/ChatBot/Network/OpenAIService.swift
> +    func sendRequestToOpenAI(_ messages: [RequestMessageModel], completion: @escaping (Result<[Message], Error>) -> Void) {
코드의 확장성 및 재사용성을 위해 URL Request를 구성하는 로직들을 별도 메서드나 객체로 분리해봐도 좋을것 같아요!

2024-03-29 00:47 UTC, GREENOVER commented on ChatBot/ChatBot/Network/OpenAIService.swift
> +                completion(.failure(error))
현재 통신시 요기에 떨어지고 있고 KeyNotFound 즉, 디코딩 에러가 나고 있습니다 🥲
이유를 살펴보면 상단에서 429 에러가 나고있는데 여러분들의 잘못이 아닌 해당 키를 다른 분들과 공용으로 사용하기에 너무 많은 요청을 보내서 나오고 있네요ㅠㅠ
그래서 정상적인 네트워킹까지는 테스트를 못해봤어요 😭

2024-03-29 00:47 UTC, GREENOVER commented on ChatBot/ChatBot/Network/OpenAIService.swift
> +                completion(.failure(error))
결론은 이런 429 HTTP 응답 에러에 대해서 위에 말한것처럼 response를 가지고 statusCode를 체크하여 자체 디버깅을 한다면 개발단에서도 더 좋을것 같네요!

2024-03-29 00:47 UTC, GREENOVER commented on ChatBot/ChatBot/OpenAIResponseDTO.swift
> +struct OpenAIResponseDTO: Codable {
음 실제로 파일 그룹화전에 상위에 있던 동일한 파일이 기록에 남아있는것 같네요ㅠ
실제 main 브랜치의 플젝에는 들어있지 않고 파일 폴더 내에 들어있는데, 제거해도 될것 같습니다 🙋🏻

2024-03-29 00:47 UTC, GREENOVER commented on ChatBot/ChatBot/Repository/MessageRepository.swift
> +    var messagesStorage: [Message] = []
외부에서 해당 프로퍼티를 메서드를 통한게 아니라 직접 접근할 일이 있을까요~?

2024-03-29 00:47 UTC, GREENOVER commented on ChatBot/ChatBot/Repository/MessageRepository.swift
> +    }
현재 messageStorage 배열에 접근할때 여러 스레드에서 동시에 접근하여 수정하는 등 동시성 문제가 발생할 수 있습니다.
그렇기에 적절히 DispatchQueue를 이용해 안전한 동시성을 구축해보면 어떨까요?
아래 메서드들도 마찬가지일것 같아요ㅎㅎ

2024-03-29 00:47 UTC, GREENOVER commented on ChatBot/ChatBot/ViewController.swift
> +    private let apiService = OpenAIService()
해당 인스턴스들을 VC를 생성하는 윗 단계에서 의존성으로 주입받아 생성하는것이 더 안전하고 관리에 이로울것 같습니다!

2024-03-29 00:47 UTC, GREENOVER commented on ChatBot/ChatBot/ViewController.swift
>  class ViewController: UIViewController {
조금 더 명확한 VC 네이밍이면 어떨까요?
추후 VC가 늘어난다면, 아시겠지만 구분하기 힘들것 같네요ㅠㅠ

2024-03-29 00:47 UTC, GREENOVER commented on ChatBot/ChatBot/ViewModel/ChatViewModel.swift
> +                    print("Error: \(error.localizedDescription)")
실제로 사용자에게는 보이지 않기에, 실패 시 얼럿이나 토스트를 띄울 수 있도록 VM에서 관리하는것도 좋을것 같아요 🙋🏻

2024-04-01 05:22 UTC, andyanappdev commented on ChatBot/ChatBot/App/SceneDelegate.swift
> +        self.window?.makeKeyAndVisible()     }
수정 커밋 하였습니다.

2024-04-01 05:22 UTC, andyanappdev commented on ChatBot/ChatBot/ViewModel/ChatViewModel.swift
> +class ChatViewModel {
넵. final 키워드 붙여서 수정 커밋 하였습니다.

2024-04-01 05:22 UTC, andyanappdev commented on ChatBot/ChatBot/ViewModel/ChatViewModel.swift
> +    }
코드 묶음 별로 개행 하여 수정 커밋 하였습니다.

2024-04-01 05:22 UTC, andyanappdev commented on ChatBot/ChatBot/ViewModel/ChatViewModel.swift
> +    private let repository: MessageRepository
상수명을 messageRepository로 수정 커밋 하였습니다.

2024-04-01 05:22 UTC, andyanappdev commented on ChatBot/ChatBot/Model/OpenAICheatResponseDTO.swift
> +struct OpenAICheatResponseDTO: Codable {
DTO의 역할이 통신하여 받아온 json 데이터를 사용하고자 하는 model로 변환시켜 주기 위한 중간 단계 이기 때문에 Codabel 보다는 그 역할에 맞게 Decodable 프로토콜 채택으로 수정하였습니다.

2024-04-01 06:28 UTC, happykwon commented on ChatBot/ChatBot/Model/RequestMessageModel.swift
> +struct RequestMessageModel: Codable {
없을것같습니다 Encodabel을 채택해 명확하게 수정 완료했습니다.

2024-04-01 06:28 UTC, happykwon commented on ChatBot/ChatBot/Model/ResponseMessageModel.swift
> +struct ResponseMessageModel: Codable {
ResponseDTO에서 한번더 데이터를 받는 값을 지정해줘야 편할 것 같아 구현했었는데 다시 생각해보니 제가 착각해서 한번 더 모델이 필요하다고 생각했습니다. 불필요해보여 삭제했습니다.

2024-04-01 06:31 UTC, happykwon commented on ChatBot/ChatBot/Network/APIKeyManager.swift
> +struct APIKeyManager {
enum은 어떤 case별로 다루기 편한 타입이라고 생각하면, 현 프로젝트에서는 openAI의 키값외에는 다른 API 키값이 필요한 case가 없을 것 같아 struct로 관리하려했습니다.

2024-04-01 08:00 UTC, happykwon commented on ChatBot/ChatBot/Network/OpenAIService.swift
> +class OpenAIService {
어디서든 API를 사용할 것 같아 Calss로 설계를 했는데, grenn얘기를 듣고 생각해보니 전역으로 사용될까? 라는 의문이 들긴합니다. 
Struct로 변경을 하더라도 참조가 필요하지 않는 프로젝트라면은 Class가 아닌 Struct로 사용해도 될 것 같습니다 ! Green의 생각은 어떠신가요 ?

2024-04-04 04:42 UTC, happykwon commented on ChatBot/ChatBot/Network/OpenAIEndPoint.swift
> +            preconditionFailure("URL Error: \(components)")
콜백 함수를 활용해 View단에서 Alert이 노출이 될 수 있도록 했습니다

2024-04-04 04:42 UTC, happykwon commented on ChatBot/ChatBot/Network/OpenAIService.swift
> +            "model": "gpt-3.5-turbo",
수정 완료했습니다 :)

2024-04-04 04:42 UTC, happykwon commented on ChatBot/ChatBot/Network/OpenAIService.swift
> +        let task = URLSession.shared.dataTask(with: request) { data, response, error in
HTTPStatus코드가 나오게 하여 요청시 적절한 대처를 할 수 있게 해주었습니다. 
현재 방식이 아닌 그냥 Enum타입으로 정의를 해서 해주는게 더 좋을지 고민하다가 코드만 알면 대처 방안을 알 수 있기 때문에 현 코드로 적용하였는데 Green의 생각은 어떠신가요 ?

2024-04-04 04:42 UTC, happykwon commented on ChatBot/ChatBot/Network/OpenAIService.swift
> +    func sendRequestToOpenAI(_ messages: [RequestMessageModel], completion: @escaping (Result<[Message], Error>) -> Void) {
별도의 객체로 분류했습니다

2024-04-04 04:42 UTC, happykwon commented on ChatBot/ChatBot/OpenAIResponseDTO.swift
> +struct OpenAIResponseDTO: Codable {
제거 완료했습니다 !

2024-04-04 04:42 UTC, happykwon commented on ChatBot/ChatBot/Repository/MessageRepository.swift
> +    var messagesStorage: [Message] = []
`private`로 변경했고 필요한 곳에는 내부 메서드로 값을 전달받도록 했습니다.
이렇게 하니, 실제 값을 들고있는 변수에는 접근이 차단되어 안전성이 올라갈 것 같습니다.

2024-04-04 04:43 UTC, happykwon commented on ChatBot/ChatBot/Repository/MessageRepository.swift
> +    }
구현 완료했습니다 구현을 하기 위해 생각을 해보니 한가지 궁금한 점이 생겼습니다 
`clearStorage()`메서드는 배열에 있는 메세지를 전부 삭제하는 기능을 하는데, 제가 생각했을 때는get이 전부 완료되고 clear를 해야 한다고 생각해서 sync로 해주었는데 이렇게 되면 데드락의 위험이 있다고 생각이 됩니다 `getMessages`를 실행 한 후에 `clearStorage`가 실행 될 수 있도록 보장 할 수 있는 더 좋은 방법이 있을까요 ?

2024-04-04 04:43 UTC, happykwon commented on ChatBot/ChatBot/ViewController.swift
> +    private let apiService = OpenAIService()
`SceneDelegate`쪽에서 의존성을 주입을 수 있게 재설계 했습니다 !

2024-04-04 04:45 UTC, happykwon commented on ChatBot/ChatBot/ViewController.swift
>  class ViewController: UIViewController {
수정완료했습니다 :)

2024-04-04 04:50 UTC, happykwon commented
추가적인 질문이 있습니다.. 실행시 아무 문제없이 통신을 하고 의도한 대로 작동을 하는 것 같은데 ..

![image](https://github.com/tasty-code/ios-chat-bot/assets/149054154/e27c61a3-df88-4fd1-b598-1fdc2525b7d5)

위 사진처럼 로그가 찍힙니다. 원일을 찾아보려 했지만 어떤 지점이 잘못되어서 이렇게 나오는지 감이 오지 않습니다 😭
이유를 찾아보니 
1. 네트워크 연결 상태
2. 서버 문제
3. 요청 설정
4. 앱의 네트워크 구성 오류
이렇게 네가지 정도로 추려지는 것 같은데 통신도 200번으로 잘 작동 되는 것 같은데 원인을 잘 모르겠습니다..
그린이 보기에 어떤 부분이 문제 인 것 같은지 알려주시면 깊게 파보도록 하겠습니다 !

2024-04-04 05:32 UTC, GREENOVER commented on ChatBot/ChatBot/Network/OpenAIService.swift
> +class OpenAIService {
네 물론 어떤게 답이다 요런걸로 여쭤봤던건 아닙니다ㅎㅎ
저는 주로 Struct로 가져가면서 의존성 주입을 통해 위에서 내려주는 방식으로 사용해요!

2024-04-04 05:33 UTC, GREENOVER commented on ChatBot/ChatBot/Network/OpenAIService.swift
> +        let task = URLSession.shared.dataTask(with: request) { data, response, error in
네네 그래도 좋습니다~
핵심은 status에 따라 검증되면 좋을것 같아서 말씀드렸어요!

2024-04-04 05:35 UTC, GREENOVER commented on ChatBot/ChatBot/Repository/MessageRepository.swift
> +    }
세마포어나를 이용해봐도 좋을것 같습니다 🙋🏻

2024-04-04 07:11 UTC, happykwon commented on ChatBot/ChatBot/ViewModel/ChatViewModel.swift
> +                    print("Error: \(error.localizedDescription)")
수정완료했습니다 :)

2024-04-04 07:28 UTC, GREENOVER approved these changes
스텝 1,2 리팩토링 하시느라, 고생 많으셨어요!
말씀하신 에러 메시지는 저는 현재 실행시키고 있는데, 나타나지 않고 있습니다.
제가 추측하기엔 이러한 메시지는 Firebase나 카카오SDK 사용 시에도 종종 나타나는거긴한데, 현재 작성하신 코드상에서 잘못된 부분은 아니라 보입니다.
현 상황에서 추측할 수 있는 이유로는 OpenAI 키를 여러 사람들이 같이 사용하고 있어, 429 에러가 뜨는 그런것처럼 실제 통신이 타임아웃 발생하거나 겹쳐서 종종 그럴 수 있을것 같아요.
즉, OpenAI 서버 내부에서 이슈가 있을것 같습니다~
현재로 혹시 발생하시는지 확인해보셔도 좋을것 같아요 😃
아니라면, 네트워크 응답 시간에 대해 타임아웃이 발생하면 리트라이를 해볼수도 있고, 아니면 응답 처리하는걸 시간을 조금 지연시켜서 테스트 해봐도 어떠한 문제였는지 확인해볼수도 있을것 같습니다!
OpenAI API에서의 문제로 보이긴합니다 🥲

다시 한번 리팩토링 수고 많으셨고, 스텝 3도 화이팅입니다 👍

2024-04-04 07:29 UTC, merged