AI 챗봇 앱 [Step 1] 이안, 홍
tasty-code/ios-chat-bot pull request #36
Opened 2024-03-28 16:08 UTC by ujhong7

리뷰어:
@junbangg

버드:
@ujhong7
@ianK0909

안녕하세요! AI 챗봇 앱 프로젝트를 함께하게된 홍, 이안입니다.
잘부탁드립니다😊

## 🔍 What is this PR?
Step 1 : 모델 타입 구현

<구현 사항>
- Request 및 Response를 위한 데이터 모델 설계

2024-03-29 15:17 UTC, junbangg requested changes

2024-03-29 15:17 UTC, junbangg commented on ChatBot/ChatBot/Model/ChatRequest.swift
> +    let stream: Bool
Bool 값은 타입 없이도 Bool 값인게 보이면 좋을것 같아요..!
[Swift API 가이드라인 참고요!](https://www.swift.org/documentation/api-design-guidelines/#naming:~:text=Uses%20of%20Boolean%20methods%20and%20properties%20should%20read%20as%20assertions%20about%20the%20receiver)

2024-03-29 15:17 UTC, junbangg commented on ChatBot/ChatBot/Model/ChatResponse.swift
> +    let totalTokens: Int
요건 무슨 값인가요?🤔
Int 값인데 s 로 끝나는거보니까 count 인가..? 를 추측하게 되네요!

2024-03-29 15:17 UTC, junbangg commented on ChatBot/ChatBot/Model/ChatResponse.swift
> +    let created: Int
요건 무슨 값인가요?

2024-03-29 15:17 UTC, junbangg commented on ChatBot/ChatBot/SceneDelegate.swift
> +        self.window = window
여기는 이후 스텝에서 수정될 여지가 있어보이는데
저는 개인적으로 요럴때 mark 주석으로 TODO 를 남겨놓으면
개발하는 사람/리뷰하는 사람 다 조금씩 행복해지더라고요!😊

2024-03-29 15:17 UTC, junbangg commented on ChatBot/ChatBot/Model/ChatResponse.swift
> +    let model: String
여기는 model 값이 String이고, 위에 ChatRequest는 GPTModel 이던데 혹시 어떤 차이인가요~?

2024-04-01 06:34 UTC, ianK0909 commented on ChatBot/ChatBot/Model/ChatRequest.swift
> +    let stream: Bool
Bool 타입 기본값 설정하겠습니다.

2024-04-01 06:35 UTC, ianK0909 commented on ChatBot/ChatBot/SceneDelegate.swift
> +        self.window = window
mark주석을 통해 TODO를 남겨놓겠습니다.

2024-04-01 07:18 UTC, ianK0909 commented on ChatBot/ChatBot/Model/ChatResponse.swift
> +    let created: Int
반환된 채팅 응답 객체입니다.
id : 채팅완료를위한 고유식별자 입니다.
object :  객체유형은 항상 chat.completion 입니다.
created :  채팅완료 시점에 타임스태프 입니다.

2024-04-01 07:19 UTC, ianK0909 commented on ChatBot/ChatBot/Model/ChatResponse.swift
> +    let totalTokens: Int
사용통계

2024-04-01 09:00 UTC, ianK0909 commented on ChatBot/ChatBot/Model/ChatResponse.swift
> +    let model: String
chatResponse의 모델은 채팅완료에 사용된 모델입니다.
GPTModel은 사용할 모델 입니다. chat API와 작동하는 모델을 정해줍니다.
String으로 바꾸겠습니다

2024-04-04 12:12 UTC, junbangg commented on ChatBot/ChatBot/Model/ChatResponse.swift
> +    let totalTokens: Int
오호 그렇군요 그럼 명시적으로 count 라는 이름을 붙여주는 네이밍은 어떨까요?

2024-04-04 12:12 UTC, junbangg commented on ChatBot/ChatBot/Model/ChatResponse.swift
> +    let totalTokens: Int
```
promptTokens
completionTokens
```
이 친구들은 토큰이 들어있는 배열 타입일것 같은 네이밍 같아요 개인적으로!

2024-04-04 12:12 UTC, junbangg commented on ChatBot/ChatBot/Model/ChatRequest.swift
> +    let stream: Bool
아 기본값이 설정되어야 한다는 이야기는 아니고요..! 
스위프트 API 가이드라인에 따르면 Bool 값은 이름만 봐서도 Bool 타입인 네이밍을 가져야한다..! 라는걸 이야기 드리고 싶었습니다
예를 들어 `is`, `did`, `has` 등의 prefix를 갖고 있는 이름들이요,,!

2024-04-04 12:13 UTC, merged