AI 챗봇 앱 [STEP 2] 댄, Jane
tasty-code/ios-chat-bot pull request #39
Opened 2024-04-02 07:22 UTC by jane1choi

리뷰어:
@songda515

버드:
@jane1choi
@eensungkim

안녕하세요 다나! STEP 2 마무리 후 PR 올립니다!!
이번 PR에서는 `Rx+Alamofire`를 이용한 네트워크 레이어 세팅을 진행했습니다.
네트워크 레이어 구성 완료 후, 요청 테스트까지 완료한 상태이고, 채팅 뷰 구현에 따라 요청 메서드의 파라미터 타입 등만 조금씩 달라질 것 같아요.
그리고, 이 후 작업에서 MVVM 아키텍처를 구성하면서 네트워크 요청 코드는 `ViewModel` 혹은 `Repository` 로 옮길 예정입니다.
이 점 참고해서 리뷰해주시면 감사하겠습니다😊😊

**⭐️ 조언, 제안, 논의 언제나 환영합니다 ⭐️**

## 🔍 What is this PR?
AI 챗봇 앱 프로젝트 STEP 2 기능을 구현했습니다.

<구현 사항>
- `Rx+Alamofire`를 이용한 네트워크 레이어 세팅
- create chat completion API 호출 테스트 완료

## ✏️ PR Point
### 폴더링 진행
프로젝트 파일 전체 폴더링을 진행했습니다.
```
- App
- Utils
- Scenes
- Network
- Resources
- Supports
```
프로젝트 규모가 크지 않아 위와 같은 구조로 크게 한번 나누었고,
하위 폴더 구조는 아래 이미지 참고해주시면 감사하겠습니다!
다음 스텝에서 MVVM 아키텍처 구조로 코드를 구성할 예정이라, 추후 `Scene` 폴더 하위를 세부적으로 좀 더 나눌 것 같습니다!

<img width="200" alt="스크린샷 2024-04-02 오후 3 46 56" src="https://github.com/tasty-code/ios-chat-bot/assets/63277563/a5469983-34f8-4f69-aa57-cc310c55fa04">

### Alamofire를 모듈화하여 네트워크 레이어 세팅
프로토콜, 제네릭을 활용한 추상화, 상속을 이용한 일반화를 통해 모든 네트워크 통신에서 사용되는 공통적인 부분을 하나로 묶어 효율적인 통신이 될 수 있도록 네트워크 레이어를 구성하였습니다.

주요 사항
**1. `TargetType` 프로토콜 정의**
`TargetType`은 API들의 공통 Endpoint를 가지고 있는 프로토콜입니다. `TargetType` 프로토콜에서는 모든 request에 필요한 endpoint를 프로퍼티로 정의해두어 해당 준수하는 곳에서 endpoint를 필수로 구현하도록 해주었으며, 해당 프로토콜 extension에서 모든 request에 필요한 메서드들을 구현하여 해당 프로토콜을 준수하는 곳에서는 request마다 달라지는 endpoint 값들만 정의해주면 최종적인 urlRequest를 만들어 요청을 보낼 수 있도록 하였습니다.

```Swift
protocol TargetType: URLRequestConvertible {
    var baseURL: String { get }
    var method: HTTPMethod { get }
    var path: String { get }
    var parameters: RequestParameter { get }
    var header: HeaderType { get }
}
```
```Swift
/// Alamofire 내부 URLRequestConvertible 프로토콜 메서드 구현
func asURLRequest() throws -> URLRequest {
        let url = try baseURL.asURL()
        var urlRequest = try URLRequest(url: url.appendingPathComponent(path), method: method)
        
        urlRequest = self.makeHeaderForRequest(to: urlRequest)
        
        return try self.makeParameterForRequest(to: urlRequest, with: url)
    }

/*
...
*/
```

**2. TargetType 준수하는 API 정의**
TargetType 을 준수하여 API별로 request에 필요한 것들을 쉽게 지정할 수 있도록 했습니다. 
enum 을 이용해 각 API 별 endpoint 에 대한 설정을 한 곳에서 할 수 있도록 하여 유지보수 면에서의 장점을 살렸습니다.
TargetType을 준수하는 곳에서 enum으로 요청 목록을 작성하고, 각 케이스에 맞는 Endpoint를 정의하여 최종적인 `URLRequest`를 만들기 때문에 읽기 쉬운 코드가 되고, 같은 종류의 요청을 하나의 enum으로 묶어 각각 다른 파일로 관리할 수 있기 때문에 서버 측 변경사항에 대응에도 쉽게 수정(API 파일만 확인하면 됨)할 수 있는 구조로 코드를 구성했습니다.

**3. BaseAPI를 이용한 반복되는 코드 삭제**
모든 API가 채택하는 `BaseAPI` 프로토콜을 두어 모든 요청에서 공통적인 부분(`baseURL`, `header`) 을 기본 구현 해두었습니다. 

**4. request 메서드의 return 타입을 Single trait로 wrapping**
`RxAlamofire` 의존성을 추가해 return 타입을 `Observable<DataRequest>` 로 받을 수 있는 request 메서드를 사용하였고,
모든 요청에 대한 응답은 항상 하나이기 때문에 RxSwift의 `Single` (항상 단일 요소 또는 오류를 방출하는 것을 보장) 타입으로 받을 수 있도록 request 메서드를 한번 더 wrapping 하였습니다.

### Config 파일을 이용한 APIKey 및 BaseURL 숨기기
외부에 노출되지 않아야 하는 APIKey와 BaseURL을 `Config.xcconfig` 파일에 정의해두고
key를 이용해 접근해서 사용할 수 있도록 하였습니다.
BaseURL까지 숨긴 이유는,, 만약 내부 서버를 사용한다면 서버 url 이 공개되는 것만으로도 위험할 수 있다고 생각했기 때문입니다.
(지금처럼 openAPI를 사용하는 경우는 굳이 숨기지 않아도 된다고 생각하긴 합니다!)

## 📮 고민되는 부분
request 에서도 requestModel을 사용해서 요청을 보내고 싶은데,,,
모델을 사용한다면 request body를 dictionary 타입으로 변환해서 보내는 방법을 모르겠어서,, (requestbody의 타입을 Encodable로 지정해도 안되더라구요..🥲) 지금은 아래 코드와 같이 raw하게 body를 보내고 있습니다..!
만들어 놓은 requestModel을 사용해주지 못한 상태입니다! 이 부분 한번 확인해봐주시면 감사하겠습니다!!
```Swift
// ChatAPI.swift
var parameters: RequestParameter {
        switch self {
        case .createChat(let systemContent, let userContent):
            let body: [String: Any] = ["model": GPTModelFamilies.main.rawValue,
                                       "messages": [["role": "system",
                                                    "content": "\(systemContent)"],
                                       ["role": "user",
                                        "content": "\(userContent)"]]]
            return .requestBody(body)
        }
    }
```

2024-04-03 13:47 UTC, songda515 requested changes
댄, Jane 고생많으셨습니다! 
RxSwift 와 Alamofire 이용해서 네트워크 구현 너무 깔끔하게 잘해주셨어요! 🫢
네트워크를 수행하는 구조를 만들어보는 경험 자체가 좋을 것 같네요 🙌

질문주신 부분은 개별 코멘트 남겨뒀어요! 시도하시다가 어려움 있으면 남겨주세요~

2024-04-03 13:47 UTC, songda515 commented on ChatBot/ChatBot/Network/APIs/BaseAPI.swift
> +    }
BaseAPI 코드에 baseURL 정의되어 있어서 얘기주신대로 중복 코드가 많이 줄고 휴먼에러 발생도 적어지겠네요! 👍

2024-04-03 13:47 UTC, songda515 commented on ChatBot/ChatBot/Network/APIs/ChatAPI.swift
> +}
사용되는 API 들 enum 으로 관리되니 깔끔하고 좋네요!

2024-04-03 13:47 UTC, songda515 commented on ChatBot/ChatBot/Network/Foundation/TargetType.swift
> +            request.httpBody = try JSONSerialization.data(withJSONObject: body, options: [])
Encodable 채택한 모델 사용하신다면 아래처럼 먼저 모델을 인코딩해주고 나면 httpBody 에 넣어줄 수 있을것 같은데요!
혹시 시도해보시고 안되셨던 코드 첨부해주시면 파악하기 더 쉬울것 같아요 🙏
```
case .requestModel(let model):
    let body = try JSONEncoder().encode(model)
    request.httpBody = body
```

2024-04-03 13:47 UTC, songda515 commented on ChatBot/ChatBot/Network/Foundation/NetworkConstants.swift
> +}
필요한 부분들에 enum 활용이 너무 좋은것 같아요!! 🙌
이렇게 모아보니 네트워크에 필요한 기능들이 잘 정리되어있는것 같아 보이네요

2024-04-03 13:47 UTC, songda515 commented on ChatBot/ChatBot/Supports/Info.plist
> +	<string>${BASE_URL}</string>
URL 이나 API Key 관리하는 방식도 코드에 포함되지 않게 해주신점 좋네요~

2024-04-03 13:47 UTC, songda515 commented on ChatBot/ChatBot/Network/Services/ChatAPIService.swift
> +                    return Disposables.create()
네트워크 구현 너무 잘해주셔서 코멘트 드리기가 조심스럽지만..! 
NetworkProvider.request 에서 Decodable 타입으로 변환, Disposable 로 반환해주면
나중에 `createChat` 같은 메소드 여럿 만들었을때 중복 코드 더 줄일 수 있어보여요~
개인적인 의견이고 랩핑을 또 하는거긴해서, 선택해서 반영해주세요 🙌

2024-04-03 13:47 UTC, songda515 commented on ChatBot/ChatBot/Scenes/ViewController.swift
> +            })
사용하는 곳에서 코드 너무 깔끔해요 👍

2024-04-04 03:07 UTC, jane1choi commented on ChatBot/ChatBot/Network/Foundation/TargetType.swift
> +            request.httpBody = try JSONSerialization.data(withJSONObject: body, options: [])
제가 TargetType 부분에서 JSONEncoder로 인코딩 작업 해주는 것을 빠뜨려서 생긴 문제였네요..🥲
해당 부분 수정해주었더니 바로 해결되었어요! 코멘트 감사합니다🔥🔥

요청 url 뒤에 붙는 쿼리는 보통 간단한 값(ex. 유저 아이디..)이 붙어서 모델을 따로 만들기보다 raw하게 직접 넣어주는 것이 더 좋을 것 같아서 dictionary 타입 그대로 유지했고, `requestBody` 부분만 `Encodable` 타입으로 수정해서 `requestModel`에 매핑해서 넣어줄 수 있도록 코드 수정했습니다!!!

만약 body에도 raw한 값을 넣어주고 싶은 경우가 있다면 코멘트의 코드 처럼 enum case를 추가하는 것도 좋을 것 같아요!!😊 조언 감사합니다~!!!

반영 커밋:  [e6377bd](https://github.com/tasty-code/ios-chat-bot/pull/39/commits/e6377bd703fc1d517fc5fe4a935b19cd92a915b1)

2024-04-04 03:08 UTC, jane1choi commented on ChatBot/ChatBot/Network/Services/ChatAPIService.swift
> +                    return Disposables.create()
오,, 요청 메서드가 많아질텐데 반복되는 코드를 줄일 수 있을 것 같아서 바로 반영했습니다!!!
조언 너무 감사해요🔥🔥

반영 커밋: [a9ca30b](https://github.com/tasty-code/ios-chat-bot/pull/39/commits/a9ca30b5c8ce6bd8922d93911257302b40f215f7)

2024-04-05 10:14 UTC, songda515 approved these changes
추가 커밋 확인했습니다~! 고생많으셨어요!! 🙌

2024-04-05 10:15 UTC, songda515 commented on ChatBot/ChatBot/Network/Foundation/TargetType.swift
> +            request.httpBody = try JSONSerialization.data(withJSONObject: body, options: [])
오 다행이네요~! 네네 쿼리는 그대로 유지해도 좋습니다!! 🙏

2024-04-05 10:15 UTC, merged