AI 챗봇 앱 [Step2] Jin, Harry
tasty-code/ios-chat-bot pull request #41
Opened 2024-04-03 04:02 UTC by wlsdud-dev

안녕하세요 July(@July911), 진 해리입니다.
추운 겨울이 가고 벚꽃이 피어 봄내음이 나는 시기가 왔습니다.
당장이라도 꽃구경 가고 싶은 마음이 들지만 끝내 이겨내고
AI Chatbot App 과제 STEP2 PR을 드립니다.

잘 부탁드리겠습니다. 😉

# 🔍 What is this PR?

- 네트워크 통신을 담당할 타입을 설계하고 구현합니다.
- OpenAI API reference 문서의 데이터 형식을 고려하여 서버와 실제로 데이터를 주고 받도록 구현합니다.

**핵심경험**

- URL Session을 활용한 서버와의 통신
- CodingKeys 프로토콜의 활용

</br>

# 🗂️ 프로젝트 구조

- Combine을 사용해 네트워크 구현을 했습니다.

</br>

# 📝 PR 고민 Point

**1. Combine 활용 네트워크 구현**
`NetworkManager`는 Combine을 사용해 서버에 요청하고 응답받는 기능을 구현 했습니다. Combine을 구현하면서 publisher와 subscriber의 위치의 고민이 많았습니다. 고민 끝에 subscriber에서는 값을 가져와서 활용하기에 로직 처리보다는 View에 가까운 영역이라 생각되어 viewController에 배치를 해주었습니다. publisher는 URLSession에서 Decode까지의 처리를 NetworkManager의 책임으로 구현해주었습니다. 

**2. URL생성** 
URL생성은 `EndpointProvider`를 통해서 만들어주며, 사용하는 입장에서 enum에 정의된 case를 선택하면 해당 case와 연관된 값들을 활용해 주소가 만들어지게 하려는 의도로 설계하였습니다. 

`URLInformation`에서 설정 값들을 정해주게 되며 ChatGPT는 Query가 없으므로 [URLQueryItem] 은 default nil로 설정해주며 URLQueryItem 부분은 현재 틀만 설계되어 있습니다. 

**3. URLRequest생성**
URLRequest생성도 URL생성과 같은 구조로 `RequestProvider`를 통해서 enum에 정의된 case를 선택하면 해당 case와 연관된 값들을 활용해 URLRequest가 생성되도록 하였습니다. 

`RequestInformation`에서 설정 값들을 정해주게 됩니다. 

**4. APIKey생성**
`KeyEnviromentHandler`를 통해서 전체적인 앱에서 접근이 가능하도록 static 설계를 해주었습니다. 다만 static은 한번 호출되면 메모리에 계속 남아있기에, 해제가 될 수 있게 설계하는 편이 나을 것도 같은데, 이 부분은 의견 부탁드립니다. 

# ❓ 질문 Point
**1. 객체지향 패러다임 Vs 선언형 패러다임**
객체지향과 달리 함수형 즉 선언형 패러다임에서는 SOLID나 객체지향 미용 체조처럼 지켜면 가독성이 좋아지는 원칙이나 가이드가 있을까요? 선언형은 SwiftUI처럼 .으로 연결된 구조를 갖는데, 이 연결이 많아지면 가독성이 안좋아지는 것도 같은데, 함수화를 통해 적당히 분리해서 .을 연결해야하는 것인지, 어떤식으로 코드를 작성해야 가독성이 올라가는지 궁금해요!

**2. 책임(역할) 분리**
SRP의 원칙을 지키려 고민을 하며 구현을 해 주었는데 저희가 보지 못한 부분이 있는지 조언을 받고 싶습니다. 그리고 역할이 제대로 주어진 건지 궁금합니다. 예를 들어 viewController가 DTO를 받아 Entity에 넣어주는 처리가 맞는지 하위에서 이루어지고 Entity를 받는게 맞는지 궁금합니다.

**3. 아키텍처**
저희는 MVC구조를 최대한 연습하기 위해서 MVC로 설계를 할 예정입니다만, 이전 과제에서 클린 아키텍처를 미미하게 접한 경험이 있어서 만들다보니 MVC의 Model이 클린 아키텍처의 Data가 된 느낌이 듭니다. Combine은 MVVM과 활용을 자주하는 모습을 자주보게 되는데, 예제가 많지 않아서 왜 그런건지 MVVM을 적용해보지 않은 입장에서는 생소합니다. 아키텍처를 어떤 방향으로 잡고 가는 것이 현재 저희 수준에서 도움이 될지 의견을 구하고 싶습니다.

**4. URL생성과, URLRequest생성**
현재 설계된 구조가 가져다 쓰기에는 좋지만, 새로운 case나 API가 추가될 경우에는 enum에 각각의 항목을 다 추가해줘야해서, 명확함 대비 OCP위배라는 약점이 있는 것 같습니다. 인터넷에서 다른 예제들을 찾아봤을 때, 어떤 장점만을 갖고 있는 구조를 잘 찾지 못해서 비교적 편한 방식을 선택했는데, 조금 더 괜찮은 방식으로 설계를 해줄 수 있을지? 생각나시는게 있다면 가이드를 부탁드립니다. 

**5. Combine**
Combine을 처음 사용해보는데, 애플 예제를 참고해서 만들었습니다. 행여나 STEP3 이후 진행할 때 고려되어야할 요소가 있다면 학습자가 스스로 깨닫는 경험을 해치지 않는 선에서 생각해볼만한 부분을 리뷰에 남겨주시거나 참고해주시면 감사드리겠습니다. 예를 들어서 현재 구현을 하면서 고민 중인 사항은 `"대화 기록을 어떻게 관리하지?", "질문1을 요청해서 답변1이 오기 전에, 유저가 질문2를 요청해서 답변2가 먼저 왔을 경우, 이런 문제들을 Combine에서는 어떻게 순차적으로 처리할 수 있지?"` 등이 있습니다.  

📸 Screenshot

main 콘솔 확인 화면

![image](https://github.com/tasty-code/ios-chat-bot/assets/87616297/b99c780c-039e-4d7e-8b6b-2005e1850ea9)

2024-04-04 00:19 UTC, July911 requested changes

2024-04-04 00:19 UTC, July911 commented on ChatBot/ChatBot/Controller/ChatGPTViewController.swift
> +                switch result {
.sink(receiveCompletion 
블럭이 추후에 순환참조가 발생할까요 ? 발생한다면 왜 그럴까요?

2024-04-04 00:19 UTC, July911 commented on ChatBot/ChatBot/Controller/ChatGPTViewController.swift
> +        networkManager.fetchChatGPTCompletionData(with: messages, type: GPTResponseDTO.self)
type: GPTResponseDTO.self) 를 받는게 조금 어색하네요.

2024-04-04 00:19 UTC, July911 commented on ChatBot/ChatBot/Controller/ChatGPTViewController.swift
> +            .store(in: &cancellables)
.store(in: &cancellables) 이건 왜 해주는걸까요 ?

2024-04-04 00:19 UTC, July911 commented on ChatBot/ChatBot/Controller/ChatGPTViewController.swift
> +            }, receiveValue: { print("ChatGPT: \(String(describing: $0.choices[0].message.content))") })
receiveValue 와 receiveCompletion 의 차이는 무엇이고 어느 상황에서 쓰면 좋을까요 ?

2024-04-04 00:19 UTC, July911 commented on ChatBot/ChatBot/Model/Constant/KeyEnviromentHandler.swift
> +struct DebugEnvironment: APIKey {
DebugEnvironment 보다는 Utils가 나아보이네요 ~

2024-04-04 00:19 UTC, July911 commented on ChatBot/ChatBot/Model/Constant/KeyEnviromentHandler.swift
> +        return plist.object(forKey: "API_KEY") as? String ?? ""
좋은 접근입니다.

2024-04-04 00:19 UTC, July911 commented on ChatBot/ChatBot/Model/NetworkService/NetworkManger/Fetchable.swift
> +    func fetchChatGPTCompletionData<T: Decodable>(with messages: [Message], type: T.Type) -> AnyPublisher<T, Error>
AnyPublisher 는 무엇인가요 ?

2024-04-05 04:16 UTC, wlsdud-dev commented on ChatBot/ChatBot/Controller/ChatGPTViewController.swift
> +                switch result {
```swift
func sink(
    receiveCompletion: @escaping ((Subscribers.Completion<Self.Failure>) -> Void),
    receiveValue: @escaping ((Self.Output) -> Void)
) -> AnyCancellable
```

sink의 `receiveCompletion` 파라미터는 클로저로 받기 때문에 클로저를 받을때 주변의 상수, 변수 등을 함수가 끝나더라도 사용하기 위해 참조타입으로 캡처합니다. 참조타입으로 값을 가져오기 때문에 참조카운트를 내려주지 않으면 메모리에서 해제가 되지 않아 메모리 릭이 발생합니다.

2024-04-05 04:17 UTC, wlsdud-dev commented on ChatBot/ChatBot/Controller/ChatGPTViewController.swift
> +            .store(in: &cancellables)
.store(in:) 은 subscriber를 set 컬렉션 타입으로 저장하여 취소를 관리해주기 위해 사용합니다.

2024-04-05 04:18 UTC, wlsdud-dev commented on ChatBot/ChatBot/Controller/ChatGPTViewController.swift
> +            }, receiveValue: { print("ChatGPT: \(String(describing: $0.choices[0].message.content))") })
receiveValue는 값을 가져왔을때 실행되는 클로저이고 receiveCompletion는 요청이 완료 되었을때 실행되는 클로저 입니다.

예를들어 요청은 완료되었지만 값을 못가져 왔을때 receiveCompletion에는 `failure(_:)` 가 반환됩니다. 반대로 값을 제대로 가져왔을 경우에는 `finished` 가 반환됩니다.

2024-04-05 04:22 UTC, wlsdud-dev commented on ChatBot/ChatBot/Model/NetworkService/NetworkManger/Fetchable.swift
> +    func fetchChatGPTCompletionData<T: Decodable>(with messages: [Message], type: T.Type) -> AnyPublisher<T, Error>
operator를 사용하다 보면 여러 publisher 타입이 생성되는데 이런 타입들을 `.eraseToAnyPublisher()`를 사용해 타입을 지워서 AnyPublisher로 쉽게 받아서 사용할 수 있습니다.

2024-04-05 06:39 UTC, hemil0102 commented on ChatBot/ChatBot/Controller/ChatGPTViewController.swift
> +        networkManager.fetchChatGPTCompletionData(with: messages, type: GPTResponseDTO.self)
타입을 감추기 위해 Mapper를 설계하였고, NetworkManaer의 역할을 분리해주었습니다. 
혹시라도 추가로 다듬으면 좋을 부분이 있다면 언제든 추가 코멘트 부탁드리겠습니다. 

수정사항: 57f48c5151d3025ed76b49fd59165b72a8408b9f

2024-04-05 06:40 UTC, hemil0102 commented on ChatBot/ChatBot/Model/Constant/KeyEnviromentHandler.swift
> +struct DebugEnvironment: APIKey {
넵, 뭔가 Utils로 통합되서 관리될 뭔가의 이름이 더 좋아보이네요! 

수정사항: 8e498f2c4c33c9cc3760da2c8644c1b64ba5c40d

2024-04-08 06:55 UTC, hemil0102 commented on ChatBot/ChatBot/Model/NetworkService/NetworkManger/Fetchable.swift
> +    func fetchChatGPTCompletionData<T: Decodable>(with messages: [Message], type: T.Type) -> AnyPublisher<T, Error>
publisher 프로토콜은 시간에 따라 변화하는 데이터를 생성해줄 수 있는 타입을 의미합니다. 여기서 시간에 따라 변화한다는 의미는 데이터가 비동기적으로 시간에 따라 들어올 수도 아닐 수도 있습니다. 이 프로토콜을 채택한 데이터를 생성하는 publisher 구현체는 Just(), Future() 등이 있습니다. 그리고 AnyPublisher는 역시 Publisher 프로토콜을 채택하지만 데이터를 생성하기 보다는 래핑한다는 개념으로, 어떤 Publisher가 생성해준 데이터와 error를 래핑하는 통로같은 역할입니다. 

AnyPublisher is a concrete implementation of Publisher that has no significant properties of its own, and passes through elements and completion values from its upstream publisher.

공식 문서에서 has no significant properties of its own 부분이 자체적으로 속성이 없다고 얘기하고, 이 부분이 데이터를 자체 생성하기 보다는 다른 publisher에서 생성된 데이터를 통과시켜준다는 맥락으로 설명되고 있습니다. 

따라서 래핑을 통해서 Subscriber가 Publisher의 인터페이스와만 상호작용하고 구현된 세부 정보는 숨겨지도록 할 수 있습니다. 이에 위에 언급된 .eraseToAnyPublisher()은 타입을 감춰주어 Subscriber는 추상화된 데이터와 에러를 받게 됩니다. 

참고자료: 
https://developer.apple.com/documentation/combine/anypublisher
https://jcsoohwancho.github.io/2020-01-18-Combine-시작하기(1)-Overview/
https://medium.com/@viveksehrawat36/understanding-publisher-and-anypublisher-in-swift-7a716c6474fb

2024-04-08 06:57 UTC, merged