AI 챗봇 앱 [STEP 2] Paul & Kyle
tasty-code/ios-chat-bot pull request #43
Opened 2024-04-04 05:11 UTC by Changhyun-Kyle

# AI 챗봇 앱 [STEP 2] Paul & Kyle

멤버 : [@earths-voluble](https://github.com/earths-voluble) [@Changhyun-Kyle](https://github.com/Changhyun-Kyle)

리뷰어 : [@Mino777](https://github.com/Mino777)

AI 챗봇 앱 두번째 Step입니다!

정리하여 PR 드립니다. 감사합니다!

---

# 🤔 고민한 점

## MVVM

- 현 `STEP` 시작 전 `MVVM` 디자인 패턴을 적용하기로 했습니다.
따라서, 다음 `STEP`을 고려하여 `Input`에 메세지 보내기 버튼이 눌렸을 때를 `case`로 구현하고,  `Output`에 데이터 요청이 성공/실패했을 때와 사용자가 같은 요청을 여러번 보내지 못하게 하기 위해 응답이 오기 전까지 버튼을 `disable`하는 `case`로 구현했습니다.
    
    ```swift
        enum Input {
            case sendButtonTapped(message: Message)
        }
    
        enum Output {
            case fetchChatResponseDidFail(error: NetworkError)
            case fetchChatResponseDidSucceed(response: ResponseModel)
            case toggleSendButton(isEnable: Bool)
        }
    ```
    

## Combine

- `ChatViewModel`의 `Input`을 `ChatViewController`에서 구독하여 해당 `Input`을 보내기 위해 `PassthroughSubject`로 구현했습니다. 따라서, `Input` 이벤트가 발생 시 `ChatViewModel`의 `Output`으로 방출할 수 있습니다.
- `URLSession.DataTaskPublisher`의 구현에는 기본 `Error` 타입이라 해당 에러에 대한 상세내용을 알기 어려웠습니다. 따라서, `httpResponse`의 상태 코드에 따라 에러 핸들링할 수 있는 함수를 구현했고 해당 에러를 호출부에서  `mapError`를 통해 `NetworkError` 타입으로 맵핑해주었습니다.
    
    ```swift
    extension URLSessionProtocol {
        func handleHTTPResponse(data: Data,httpResponse: URLResponse) throws -> Data {
            guard let httpResponse = httpResponse as? HTTPURLResponse else {
                throw NetworkError.unknownError
            }
            switch httpResponse.statusCode {
            case 300..<400:
                throw NetworkError.redirectionError
            case 400..<500:
                throw NetworkError.clientError
            case 500..<600:
                throw NetworkError.serverError
            default:
                return data
            }
        }
    }
    
    extension URLSession: URLSessionProtocol {
        func dataTaskPublisher(
            for request: URLRequest
        ) -> AnyPublisher<Data, NetworkError> {
            return self.dataTaskPublisher(for: request)
                .tryMap { (data: Data, response: URLResponse) in
                    try self.handleHTTPResponse(data: data, httpResponse: response)
                }
                .mapError { error in
                    error as? NetworkError ?? NetworkError.networkError(error)
                }
                .eraseToAnyPublisher()
        }
    }
    ```
    

## Test

- `STEP`을 진행하면서 너무 많은 요청이 일어나 `http` 상태 코드가 `429번(too many request)`으로 받아와지는 이슈가 발생했습니다. 따라서, `MockData`와 `MockURLSession`을 생성하여 `Unit Test`를 통해 로직을 검증하고 이후 있을 `STEP`에서도 필요한 상황이 아니면 `MockData`로 개발할 수 있게 구현했습니다.
    
    ```swift
    final class MockURLSession: URLSessionProtocol {
        typealias Response = AnyPublisher<(Data, URLResponse), NetworkError>
        
        private let response: Response
        
        init(response: Response) {
            self.response = response
        }
        
        func dataTaskPublisher(for request: URLRequest) -> AnyPublisher<Data, NetworkError> {
            return response
                .tryMap { (data: Data, response: URLResponse) in
                    try self.handleHTTPResponse(data: data, httpResponse: response)
                }
                .mapError { error in
                    error as? NetworkError ?? NetworkError.networkError(error)
                }
                .eraseToAnyPublisher()
        }
    }
    ```
    

## makeBody(message:)

- 대화를 시작했을 때, 일관된 맥락을 유지하며 요청을 보내기 위해선 서버와 주고 받은 모든 `message` 모델을 포함해야했습니다. 하지만, 현재 `STEP`에서 `system`에 대한 설정을 할 수 있는 방법이 없기 때문에 가장 처음 요청을 보낼 때는 하나의 지정된 `Message` 모델이 필요했습니다.
- 따라서, `requestModel`을 옵셔널로 선언하여 처음 요청인지 아닌지 구분하고 처음 요청이 아니라면 `messages`에 `append`할 수 있게 구현했습니다.
    
    ```swift
        func makeBody(message: Message) -> RequestModel? {
            guard
                requestModel != nil
            else {
                requestModel = RequestModel(
                    messages: [
                        Message(role: "system", content: "You are a poetic assistant, skilled in explaining complex programming concepts with creative flair."),
                        message
                    ]
                )
                return requestModel
            }
            requestModel?.messages.append(message)
            return requestModel
        }
    ```
    

# 🧐 궁금한 점

## Bundle 예외처리

- 현재 `.xcconfig` 파일에서 `API Key`를 생성 후 `Bundle Extension`에서 가져올 수 있게 구현했습니다. 해당 `Bundle`에 접근하기 위해선 `func object(forInfoDictionaryKey key: String) -> Any?` 로 가져오게 됩니다. 이때, 옵셔널 언래핑 시 `API KEY`가 잘못된 경우  별도의 에러처리를 해주는 것이 나을 지 `fatalError`로 처리하는 것이 나을 지 마이노의 의견이 궁금합니다.
    
    ```swift
    extension Bundle {
        var chatBotAPIKey: String {
            guard 
                let key = self.object(forInfoDictionaryKey: "ChatBot_API_KEY") as? String
            else {
                return ""
            }
            return key
        }
    ```
    

## Combine Test

- 아래 테스트 로직은 `ViewModel`의 로직을 검증하기 위해 구현한 테스트 코드입니다. `BDD`에 맞게 구현하려고 했는데 `output.sink()` 부분이 애매했습니다. 하나의 테스트 로직에 `given/when/then`을 담아야하는데  `setup`으로 분리한다면 `then`에 해당하는 결과가 전체로 이어지게 됩니다. 이렇게 `Reactive`한 로직을 테스트할 때는 어떤 방법으로 구현해야하는 지 궁금합니다.
    
    ```swift
    func test_sendButtonTapped_input을_send했을_때_output은_nil이_아니다() {
            // given
            let output = sut.transform(input: input.eraseToAnyPublisher())
            
            output.sink { event in
                switch event {
                case .fetchChatResponseDidFail(_):
                    // then
                    XCTFail()
                case .fetchChatResponseDidSucceed(let response):
                    // then
                    XCTAssertNotNil(response)
                    print(response)
                case .toggleSendButton(let isEnable):
                    // then
                    XCTAssertNotNil(isEnable, "\(isEnable)")
                }
            }
            .store(in: &cancellables)
            
            // when
            input.send(
                .sendButtonTapped(
                    message: Message(
                        role: "user",
                        content: "Compose a poem that explains the concept of recursion in programming."
                    )
                )
            )
        }
    ```
    

## ViewController의 역할

- `MVVM` 디자인 패턴을 구현하다보니 `ViewController`의 역할이 모호해진 것 같습니다. 현재 `PR`에는 `Controller`로 분리하여 폴더링 했지만, `ViewController`의 역할은 `View`의 `input` 이벤트 발생 및 이후 `STEP`에서 구현될 `View`가 담긴 사실 상 `View`들의 총 집합인 `mainView(?)`라고 생각합니다. 따라서, 폴더링을 `Controller`로 해야할 지 `View`에 넣어야할 지 궁금합니다!

2024-04-05 05:29 UTC, Mino777 requested changes
안녕하세요!! 카일, 폴!

STEP 2 진행하시느라 정말 수고 많으셨습니다!!🥳

Combine, MVVM 패턴 모두 잘 사용해주셨네요! 좋습니다👍
네트워킹 레이어 구조나 단위테스트에 대해서도 많이 고민하신 흔적이 보여서 너무 좋습니다👍
구조의 경우 깃헙에 있는 유명한 샘플 아키텍처 레포지토리들을 쭉 보시면서 장점만 쏙쏙 골라서 자기것으로 만드는 경험을 해보시면 많은 도움이 되실꺼에요!

질문 주신 부분들중에 메세지로 답변이 없는 부분은 코드 코멘트에 달아놓았으니, 참고 하시면 좋을 것 같습니다~!

## 고민 및 질문

> Bundle 예외처리, Combine Test

해당 질문에 대한 답변은 코드코멘트에 달아놓았습니다!

> ViewController의 역할

사실 폴더링은 팀 컨벤션의 영역이라 볼 수 있어서 팀원과 협의된 폴더링은 아무 문제가 없습니다ㅎㅎ

저같은 경우엔 MVVM 패턴을 사용할 때 ViewController의 경우 View로 폴더링합니다.

- Scene or Presentation
  - View
    - AnyView
    - AnyViewController
  - ViewModel
    - AnyViewModel 

요런식으로 묶는 편입니다! 깃헙에 있는 여러 MVVM패턴 샘플들을 보면서 제일 맘에드는 폴더링 구조를 선택하시는 것도 방법입니다ㅎㅎ

2024-04-05 05:29 UTC, Mino777 commented on ChatBot/ChatBot/Controller/ChatBotViewController.swift
> +
View와 ViewModel의 역할을 잘 나누어주셨네요! 좋습니다👍

2024-04-05 05:29 UTC, Mino777 commented on ChatBot/ChatBot/Controller/ChatBotViewController.swift
> +    private var cancellable = Set<AnyCancellable>()
AnyCancellable에 대해 설명해주세요!

2024-04-05 05:29 UTC, Mino777 commented on ChatBot/ChatBot/Controller/ChatBotViewController.swift
> +    private let input: PassthroughSubject<ChatViewModel.Input, Never> = .init()
적절한 Subject로 정의해주셨네요! 좋습니다👍
여러분들의 Subject의 선택 기준과 Subject에 대해서 설명해주세요!

2024-04-05 05:29 UTC, Mino777 commented on ChatBot/ChatBot/Controller/ChatBotViewController.swift
> +            input: input.eraseToAnyPublisher()
eraseToAnyPublisher에 대해 설명해주세요!

2024-04-05 05:29 UTC, Mino777 commented on ChatBot/ChatBot/Controller/ChatBotViewController.swift
> +        .store(in: &cancellable)
store에 대해 설명해주세요!

2024-04-05 05:29 UTC, Mino777 commented on ChatBot/ChatBot/Extensions/Bundle+.swift
> +}
Info.plist 파일로 API Key를 관리하는 부분 좋습니다!

PR 메세지에 대한 답변을 드리자면, 정말 불가피한 상황이거나 절대 해당 코드를 호출할일이 없는게 아니라면 fatalError는 사용하지 않는것이 좋습니다!
위와 같은 케이스의 경우 충분히 네트워크 통신에서 에러 핸들링을 할 수 있기 때문에 이대로 가시는게 좋을 것 같습니다👍

2024-04-05 05:29 UTC, Mino777 commented on ChatBot/ChatBot/Extensions/URLSession+.swift
> +
Mock을 위한 URLSessionProtocol 너무 좋습니다👍

네트워크 단위 테스트를 진행할 때 Mock을 사용해서 얻을 수 있는 이점은 무엇이 있을까요?!

2024-04-05 05:29 UTC, Mino777 commented on ChatBot/ChatBot/Extensions/URLSession+.swift
> +        }
default에서 성공 케이스를 처리해주는 것 보다는, 200..<300 을 명시해주는게 더 명확할 것 같습니다!

2024-04-05 05:29 UTC, Mino777 commented on ChatBot/ChatBot/Model/Network/APIType.swift
> +
enum으로 깔끔하게 구조화 하셨군요 좋습니다👍

2024-04-05 05:29 UTC, Mino777 commented on ChatBot/ChatBot/Model/Network/HttpMethod.swift
> +}
Tuple보단 구조체를 사용하는게 좋을 것 같고, 안에 직접적인 String값을 넣기 보단 enum 타입으로 해당 String 값들을 관리해주는게 좋을 것 같습니다. Tuple은 정말 필요한 상황이 아니면 분리해서 코드 가독성을 위해 지양하는게 좋더라구요!

```swift
enum HTTPMethodType: String {
    case get = "GET"
...
}

struct HttpMethodConfiguration<T: Encodable> {
    let method: HTTPMethodType
    let body: T?
}

enum HttpMethod<T: Encodable> {
    case get
...
    
    var configuration: HttpMethodConfiguration<T> {
        switch self {
        case .get:
            return HttpMethodConfiguration(method: .get, body: nil)
...
        }
    }
}
```

요런 느낌으로 작성해보시면 좋을 것 같습니다ㅎㅎ

2024-04-05 05:29 UTC, Mino777 commented on ChatBot/ChatBot/Model/Network/JSON/JSONHandler.swift
> +    }
do - catch 구문 없이 try만 해주셔도 될 것 같은데 do - catch 구문을 사용하신 이유가 있을까요?!

2024-04-05 05:29 UTC, Mino777 commented on ChatBot/ChatBot/Model/Network/Mock/MockURLSession.swift
> +}
MockURLSession 좋습니다👍👍

2024-04-05 05:29 UTC, Mino777 commented on ChatBot/ChatBot/Model/Network/NetworkService.swift
> +    }
의존성 주입 좋습니다👍👍

2024-04-05 05:29 UTC, Mino777 commented on ChatBot/ChatBot/Model/Network/NetworkService.swift
> +    }
tryMap, mapError 로직이 계속 중복될 것 같아요! 

해당 에러 처리 로직들은 dataTaskPublisher 메서드 안에만 녹여서

```swift
func fetchChatBotResponse<T: Encodable>(
        type: APIType,
        httpMethod: HttpMethod<T>
    ) -> AnyPublisher<ResponseModel, NetworkError> {
        guard let urlRequest = makeURLRequest(type: type, httpMethod: httpMethod) else {
            return Fail(error: NetworkError.requestFailError).eraseToAnyPublisher()
        }
        return session.dataTaskPublisher(for: urlRequest)
            .decode(type: ResponseModel.self, decoder: JSONDecoder())
            .eraseToAnyPublisher()
    }
```

요런식으로 처리할 수 있을 것 같아요!

2024-04-05 05:29 UTC, Mino777 commented on ChatBot/ChatBot/Model/Network/NetworkURL.swift
> +        return urlRequest
가독성이 많이 떨어지는 것 같아요! 가독성을 한번 올려볼까요?! (단순하게 줄바꿈 정도만 해주셔도 좋습니다!)

2024-04-05 05:29 UTC, Mino777 commented on ChatBot/ChatBot/Supportings/Info.plist
> +	<string>$(ChatBot_API_KEY)</string>
좋습니다👍👍

2024-04-05 05:29 UTC, Mino777 commented on ChatBot/ChatBot/ViewModel/ChatViewModel.swift
> +    }
의존성 주입 좋습니다👍

2024-04-05 05:29 UTC, Mino777 commented on ChatBot/ChatBotTests/ChatBotTests.swift
> +    }
질문주셨던 Reactive한 테스트에서 then이 애매해질땐 XCTestExpectation 을 사용해서 비동기 스트림의 완료를 기다리게 해주면 해결할 수 있습니다.

```swift
func test_sendButtonTapped_input을_send했을_때_output은_nil이_아니다() {
    // given
    let expectation = XCTestExpectation(description: )
    let output = sut.transform(input: input.eraseToAnyPublisher())
    
    output.sink { event in
        // then
        defer { expectation.fulfill() }
        switch event {
        case .fetchChatResponseDidFail(_):
            XCTFail()
        case .fetchChatResponseDidSucceed(let response):
            XCTAssertNotNil(response, )
        case .toggleSendButton(let isEnable):
            XCTAssertTrue(isEnable, )
        }
    }
    .store(in: &cancellables)
    
    // when
    input.send(.sendButtonTapped(message: Message(role: "user", content: "Test message")))
    
    wait(for: [expectation], timeout: 5.0)
}
```

이런 느낌으로 테스트를 진행하시면, 비동기 테스트에도 BDD를 적용시킬 수 있습니다!

2024-04-06 11:22 UTC, Changhyun-Kyle commented on ChatBot/ChatBot/Controller/ChatBotViewController.swift
> +    private var cancellable = Set<AnyCancellable>()
`AnyCancellable`은 `Cancellable` 프로토콜을 채택하고 있어 `Combine`의 작업을 취소할 수 있습니다. 특히, `.sink()`를 활용할 때 `AnyCancellable`을 반환하는데요. `.sink()`를 통해 데이터를 받아온 후 해당 스트림의 구독을 취소할 때 `.store(in:)`과 함께 사용하여 메모리를 관리할 수 있습니다.!

2024-04-06 11:22 UTC, earths-voluble commented on ChatBot/ChatBot/Controller/ChatBotViewController.swift
> +        .store(in: &cancellable)
`Set`에 `AnyCancellable`을 모아 두었다가, 한 번에 `cancel()`할 수 있도록 합니다.

2024-04-06 11:27 UTC, earths-voluble commented on ChatBot/ChatBot/Extensions/URLSession+.swift
> +
입출력 / 에러 상황 등을 자유롭게 제어하며 네트워크 지연 시간에 구애받지 않고 빠른 테스트를 할 수 있습니다.
특히 이번 프로젝트의 경우, 사용되는 API가 유료 요금제인 만큼, 불필요한 API 호출을 줄이는 데에 유용했습니다.

2024-04-06 11:36 UTC, Changhyun-Kyle commented on ChatBot/ChatBot/Controller/ChatBotViewController.swift
> +    private let input: PassthroughSubject<ChatViewModel.Input, Never> = .init()
`Subject`는 `Publisher` 프로토콜을 채택하고 있지만, `Publisher`와 다른 점은 `.send()`를 통해 값을 주입할 수 있습니다. `Subject`에는 `PassthroughSubject`와 `CurrentValueSubject`가 있는데요. 
- `PassthroughSubject`는 구독한 `downstream`에 값을 보냅니다. 또한, 완료 이벤트를 받을 수 있어 해당 이벤트 수신 시 더 이상 다른 완료 이벤트 혹은 값을 받지 않습니다. 
- `CurrentValueSubject`는 `PassthroughSubject`와 달리 초기값을 할당할 수 있고 최근 발행한 값을 발행합니다. 또한, 완료 이벤트를 받을 수 없으며, 값을 주입할 수만 있습니다.

2024-04-06 11:42 UTC, earths-voluble commented on ChatBot/ChatBot/Extensions/URLSession+.swift
> +        }
b63e46c에서 수정했습니다!

2024-04-06 11:43 UTC, Changhyun-Kyle commented on ChatBot/ChatBot/Controller/ChatBotViewController.swift
> +            input: input.eraseToAnyPublisher()
`eraseToAnyPublisher()`를 사용하면 해당 `publisher`의 실제 유형이 아닌 `AnyPublisher`의 인스턴스를 `downstream` 구독자에게 노출합니다. 이렇게 된다면, 각자 다른 유형의 `publisher`를 추상화 할 수 있어이 기존 클라이언트에 영향을 주지 않고 구현을 변경할 수 있습니다!

2024-04-06 11:52 UTC, earths-voluble commented on ChatBot/ChatBot/Model/Network/HttpMethod.swift
> +}
40e41fe 에서 수정했습니다!

2024-04-06 11:55 UTC, earths-voluble commented on ChatBot/ChatBot/Model/Network/JSON/JSONHandler.swift
> +    }
`NetworkError`로 `throw`하기 위해 `do - catch` 문을 사용했는데, 해당 에러 타입을 지정해주지 못했습니다. 😢 9354718 에서 수정 완료했습니다!

2024-04-06 12:00 UTC, Changhyun-Kyle commented on ChatBot/ChatBotTests/ChatBotTests.swift
> +    }
아, 저희도 `XCTestExpectation`을 활용해서 테스트를 하다가 `MockData`를 생성한 이후에는 제거하였는데요!
단지 `Unit test`를 진행할 때마다 `given, when, then`의 순서로 항상 흐름을 가져갔는데 `Combine`을 활용하다보니 `then` 부분을 `bind` 후 `when`에서 `send`를 하는 것이 조금 어색해서 여쭤봤습니다!

2024-04-06 12:12 UTC, Changhyun-Kyle commented on ChatBot/ChatBot/Model/Network/NetworkService.swift
> +    }
해당 부분은 저희가 커스텀한 에러 타입인 `NetworkError`로 핸들링을 하기 위해 `.decode()`를 사용하지 않고 `JSONCoder`의 `handleDecoder()` 메서드를 활용했습니다! 
Combine을 처음 공부하면서 에러핸들링 하는 게 조금 어려더라구요...혹시 이렇게 하나하나 모든 부분을 커스텀 에러로 처리하는 방법이 비효율적일까요?
또한, `JSONDecoder()`와 `JSONEncoder()`는 생성 비용이 비싸기 때문에 static으로 생성하여 재사용할 수 있게 구현했습니다.

2024-04-06 12:29 UTC, earths-voluble commented on ChatBot/ChatBot/Model/Network/NetworkURL.swift
> +        return urlRequest
45d46dc 에서 수정했습니다!

2024-04-07 13:49 UTC, Mino777 commented on ChatBot/ChatBot/Model/Network/NetworkService.swift
> +    }
아하..! 그런데 .decode를 사용해도 충분히 커스텀 에러타입으로 핸들링하실 수 있어요!
지금이야 메서드가 적어서 상관은 없겠지만, 나중엔 수백개, 수천개의 API 호출 메서드가 생겼을 때를 생각하면 엄청 비효율적이겠죠?

.decode를 dataTaskPublisher 메서드에 녹여서 해당 메서드에서 모든 에러 핸들링이 되고 나서 API 호출 부에서는 AnyPublisher<ResponseModel, NetworkError>를 리턴해주는 로직만 남기도록 수정해보시면 좋을 것 같습니다!

https://github.com/ihsanakbay/GenericNetworkLayerWithCombine/tree/main

해당 구조가 제가 말씀드리는 구조와 비슷하네요! 한번 참고 해보시면 좋을 것 같습니다💪

2024-04-07 13:51 UTC, Mino777 commented on ChatBot/ChatBotTests/ChatBotTests.swift
> +    }
아 그런의미셨군요! 저는 코드 라인 순서로 given, when ,then 을 의식하기 보단, 실제 수행 순서로 의식을 하다보니 어색한걸 못느꼈었던 것 같아요ㅎㅎ

2024-04-07 13:55 UTC, Mino777 approved these changes
수정 및 코멘트 답변 너무 잘해주셨네용👍👍

dataTaskPublisher 메서드 부분 코멘트만 수정해주시면 머지하도록 하겠습니다!
수정하시고 꼭 DM 부탁드립니당~!

고생하셨어요!!💪💪

2024-04-08 05:14 UTC, Changhyun-Kyle commented on ChatBot/ChatBot/Model/Network/NetworkService.swift
> +    }
마이노 말씀처럼 `dataTaskPublisher` 메서드에 .`decode`를 추가해서 구현하니 코드가 훨씬 간결해졌네요! 
남겨주신 링크도 정말 많이 도움 됐습니다! 감사합니다😊
```swift
// 구현부: URLSession+
extension URLSession: URLSessionProtocol {
  func dataTaskPublisher<T: Decodable>(
    for request: URLRequest
  ) -> AnyPublisher<T, NetworkError> {
    return self.dataTaskPublisher(for: request)
      .tryMap { (data: Data, response: URLResponse) in
        try self.handleHTTPResponse(data: data, httpResponse: response)
      }
      .mapError { error in
        error as? NetworkError ?? NetworkError.networkError(error)
      }
      .decode(type: T.self, decoder: JSONHandler.decoder)
      .mapError { error in
        error as? NetworkError ?? NetworkError.decodingError
      }
      .eraseToAnyPublisher()
  }
}

// 호출부: NetworkService
  func fetchChatBotResponse<T:Encodable>(
    type: APIType,
    httpMethod: HttpMethod<T>
  ) -> AnyPublisher<ResponseModel, NetworkError> {
    guard
      let urlRequest = try? NetworkURL.makeURLRequest(type: type, httpMethod: httpMethod)
    else {
      return Fail(error: NetworkError.requestFailError).eraseToAnyPublisher()
    }
    return session.dataTaskPublisher(for: urlRequest)
      .eraseToAnyPublisher()
  }
```

2024-04-08 05:38 UTC, merged