AI 챗봇 앱 [Step 3] 댄, Jane
tasty-code/ios-chat-bot pull request #46
Opened 2024-04-09 06:23 UTC by eensungkim

리뷰어:
@songda515

버드:

@jane1choi
@eensungkim

다나 안녕하세요! STEP 3 를 마무리해서 PR 보내드립니다!!

이번 PR에서는 챗봇 채팅방 화면을 구현했습니다. Modern Collection Views 를 활용한 화면 구현 및 그 외 요구사항을 반영했습니다.

참고로 이번 PR에서는 대화 내용을 기억하고 이를 반영하는 부분이 제외되었습니다. 이 부분은 다음 스텝에서 적용을 해보려고 합니다.

첫 작업을 연습 브랜치에서 진행하다가 그대로 연습 브랜치에서 마무리까지 하게 되었습니다. 이 점 참고를 부탁드리겠습니다. 감사합니다!! :bow: 

⭐️ 조언, 제안, 논의 언제나 환영합니다 ⭐️

## 🔍 What is this PR?
AI 챗봇 앱 프로젝트 STEP 3 기능을 구현했습니다.
</br>

**<구현 사항>**
- `Modern Collection View` 를 활용한 채팅 화면 구현
- `Core Graphics` 활용한 말풍선 구현
- `Core Animations` 활용한 응답 메시지 로딩 인디케이터 구현
- 네트워크 에러 발생 시 리프레쉬 버튼 팝업 및 로직 구현

</br>

## ✏️ PR Point

**주요 사항**
- `DiffableDataSource` 의 활용
- `SnapshotUpdateStrategy` 전략패턴 적용
- `MVVM` 아키텍처 구현

## 📮 고민되는 부분
**유저인지 아닌지에 관한 상태 관리 관련**

메시지의 주체가 '유저인지 또는 AI인지' 를 구분하는 상태가 현재 모델로부터 `ChatCollectionViewCell`, `ChatBubbleView` 까지 전달이 되는 상황입니다. 해당 상태는 말풍선의 위치, 말꼬리의 위치, 말풍선 배경 색상 및 글씨 색상 등 다양한 뷰의 속성에 관여하고 있는데요. 이 불리언 값 상태가 서로 다른 두 개의 뷰로 전달되다 보니, 이 상태에 대한 의존성이 높다는 생각을 하게 되었습니다.

실제로 리팩토링을 통해 별도의 열거형으로 관리하고자 했으나, switch 문이 여기저기에 나뉘게 되어 도리어 유지보수에 어려움이 생기는 것은 아닌가 싶어 현재는 이대로 구현을 완료했는데요.

혹시 이러한 경우에 어떤 식으로 접근하고 고민해보면 좋을까요?

---

**콜렉션뷰 자동 스크롤 관련**

새로운 말풍선이 추가될 때 현재 아래와 같은 로직으로 자동으로 최신 말풍선으로 스크롤되도록 기능을 구현했는데요.

네트워크 에러가 발생하는 경우 간혹 스크롤이 튀는 문제가 발생하고 있는데 현재 원인이 무엇인지를 찾지 못한 상황입니다.

혹시 자동 스크롤(?) 에 관련해서 나눠주실 수 있는 경험이 있으실까요? :crying_cat_face: 

```swift=
private func repositionCollectionView(animated: Bool) {
    let index = chatCollectionView.numberOfItems(inSection: 0)
    let indexPath = IndexPath(item: index - 1, section: 0)
    chatCollectionView.scrollToItem(at: indexPath, at: .bottom, animated: animated)
}
```

---

**네트워크 에러 발생 시 말풍선 배경색 변경되는 이슈**

위와 마찬가지로 이 문제 또한 에러의 재현이 쉽지 않아 문제의 원인을 발견하지 못하는 상황입니다.

네트워크 에러가 발생한 뒤 리프레쉬 버튼을 클릭해서 메시지를 재발송할 때, 간혹 AI 답변 말풍선의 배경 색상이 파란색으로 바뀌는 경우가 있었습니다. 글씨 색상은 바뀌지 않고 배경 색상만 바뀌는 케이스였고, 그마저도 스크롤을 해서 재사용하게 되면 다시 원래대로 돌아오는 경우였는데요.

혹시 추론 가능한 원인에 대해 아는 바가 있으실까요..? :crying_cat_face:

---
**MVVM 및 RxSwift**

`MVVM` 을 처음 공부하고 적용해보는 과정 중인데요. 현재의 구현에서 관련해서 혹시 잘못된 접근이 있거나 더 고민해보면 좋을만한 키워드가 있다면 공유해 주시면 감사하겠습니다. :pray:

마찬가지로 `RxSwift` 에 대해서 공부를 이어나가는 중인데요. `DiffableDataSource` 를 활용하다보니 `Rx` 를 특별히 활용할 기회가 많이 없었습니다.

그나마 하나 적용해 본 지점이 아래의 코드입니다. 스냅샷을 새로 적용한 뒤에 `itemIdentifiers` 를 발행하고, 뷰컨트롤러에서는 이를 구독하여 자동 스크롤이 되도록 하고 있습니다.

원래 생각했던 구현은, 구독을 통해 새롭게 추가된 말풍선 item 을 넘겨받아, 이를 바탕으로 콜렉션뷰를 스크롤하는 것이었는데요. 콜렉션뷰에서 제공하는 [`scrollToItem(at:at:animated:)` 메서드](https://developer.apple.com/documentation/uikit/uicollectionview/1618046-scrolltoitem)가 `IndexPath` 를 기반으로 동작하다보니 별도로 `IndexPath` 를 아예 생성하여 활용하는 상황입니다. 구독을 통해서는 단지 이벤트의 발생만을 참고하는 상황입니다.

해당하는 접근이 잘못된 접근이거나, 혹 다른 방법의 접근 방법이 있다면 조언해 주시면 감사하겠습니다!! :pray: 

```swift=
// ChatViewModel.swift
final class ChatViewModel {
    // ...
    
    private(set) lazy var snapshotPublisher = PublishRelay<[ChatMessage]>()

    // ...
    
    private func applySnapShot(with chatMessage: ChatMessage, strategy: SnapshotUpdateStrategy) {
    var snapshot = snapshot
    strategy.apply(using: &snapshot, with: chatMessage, loadingMessage: loadingMessage)
        
    dataSource?.applySnapshotUsingReloadData(snapshot) { [weak self] in
        guard let items = self?.snapshot.itemIdentifiers else {
            return
        }
        // 여기에서 발행(?)
        self?.snapshotPublisher.accept(items)
    }
}
    
// ChatViewController.swift
extension ChatViewController {
    private func bindToModelForReposition() {
        // 여기에서 구독
        _ = chatViewModel.snapshotPublisher.bind(onNext: { [weak self] _ in
            self?.repositionCollectionView(animated: true)
        })
        .disposed(by: bag)
    }
}
    
```

2024-04-10 16:51 UTC, songda515 requested changes
STEP 2 고생 많으셨습니다!!
전체적인 기능 구현에 대해서는 정말 잘해주신것 같아요 🙌

저도 이슈에 대해 재현이 100%는 되지 않아서 코드를 확인해보면서 코멘트 남겨뒀습니다.
Diffable datasource 에 어려움이 또 있군요 😵

2024-04-10 16:51 UTC, songda515 commented on ChatBot/ChatBot.xcodeproj/project.pbxproj
> +				IPHONEOS_DEPLOYMENT_TARGET = 17.0;
타겟은 17로 올리신 이유가 있으신가요? 👀

2024-04-10 16:51 UTC, songda515 commented on ChatBot/ChatBot/Scenes/ChatBubbleView.swift
> +        switch isUser {
ChatBubbleView 가 ViewController 에 비해서는 작은 규모의 뷰이지만, 고민하신대로 지금은 분기가 들어가게 되어서 추후 수정하기 어려울 수 있어보여요😢 UI 구성되는 코드와 로직을 분리하는게 더 가독성 좋을 것 같습니다!

isUser 의 true , false 인지 따라 값이 정해져있는 경우가 많다면
enum 으로 user, ai 를 관리하되 isUser, bubbleViewColor, textColor, tailStartPoint, tailTipPoint 등등을 변수로 갖도록 하면 View 코드 내에서는 분기되는 코드를 줄일 수 있을 것 같아요~

2024-04-10 16:51 UTC, songda515 commented on ChatBot/ChatBot/Scenes/ChatBubbleView.swift
> +        $0.lineBreakMode = .byWordWrapping
word wrapping 을 사용하는 경우 line break strategy 설정에 한글의 단어 단위에서도 끊을 수 있으니 참고하시면 좋을것 같아요 ㅎㅎ
https://developer.apple.com/documentation/uikit/nsparagraphstyle/linebreakstrategy/3667458-hangulwordpriority

2024-04-10 16:51 UTC, songda515 commented on ChatBot/ChatBot/ViewModel/ChatViewModel.swift
> +                self?.applySnapShot(with: chatMessage, strategy: AssistantChatUpdateStrategy())
subscribe 내에서 바로 snapshot 을 적용하려면 메인스레드에서 동작할 수 있도록 
`.observe(on: MainScheduler.asyncInstance)` 을 추가해주는게 안전할 것 같아요

2024-04-10 16:51 UTC, songda515 commented on ChatBot/ChatBot/ViewModel/ChatViewModel.swift
> +        dataSource?.applySnapshotUsingReloadData(snapshot) { [weak self] in
Diffable data source 관련해서 스크롤이나 셀 재사용 관련해서 질문주신 부분에 대해 재현이 되지 않아 저도 정확한 해결법을 찾지는 못했는데요 😿

아래 문서에서는 main thread 혹은 background thread 중 하나에서 일관되게 호출하라고 적혀있는 부분이 있어서, 혹시 ViewController 에서와 ViewModel 에서 다른 스레드로 동작하기 때문에 순서상 이슈가 있을수도 있어보여요 .. !
추후에 발견한 내용 있으면 전달드리겠습니다!

https://developer.apple.com/documentation/uikit/uitableviewdiffabledatasource/3804475-applysnapshotusingreloaddata

> You can safely call this method from a background queue, but you must do so consistently in your app. Always call this method exclusively from the main queue or from a background queue.

2024-04-10 16:51 UTC, songda515 commented on ChatBot/ChatBot/ViewModel/ChatViewModel.swift
> +        applySnapShot(with: emptyMessage, strategy: LastChatRemoveStrategy())
질문입니다~! 🙋‍♀️ 마지막 채팅 셀을 지우기 위해서 emptyMessage 를 만든다음에 제거하는 이유가 있을까요?

2024-04-10 16:51 UTC, songda515 commented on ChatBot/ChatBot/ViewModel/ChatViewModel.swift
> +                return cell
> 네트워크 에러 발생 시 말풍선 배경색 변경되는 이슈

요 이슈에 대해서도 재현이 현재 되고있지는 않아서, 실제 이슈가 발생했을때 해당 코드를 타고 cell 을 설정해주는 곳에 연결되는지 디버깅해보시는게 가장 좋을 것 같아요 😿

2024-04-10 16:51 UTC, songda515 commented on ChatBot/ChatBot/ViewModel/ChatViewModel.swift
> +            self?.snapshotPublisher.accept(items)
apply 를 하는 코드를 view model 로 분리하셔서 스냅샷이 완료되었다는걸 알려주는 것도 괜찮은 방법인것 같아요!

2024-04-10 16:51 UTC, songda515 commented on ChatBot/ChatBot/ViewModel/ChatViewModel.swift
> +        dataSource?.applySnapshotUsingReloadData(snapshot) { [weak self] in
apply 가 아닌 applySnapshotUsingReloadData 를 선택하신 이유가 궁금해요~

2024-04-10 16:51 UTC, songda515 commented on ChatBot/ChatBot/ViewModel/ChatViewModel.swift
> +                }
cell 에 설정해주는 메소드들을 하나로 묶으면 더 보기 좋을것 같아요!

2024-04-10 16:51 UTC, songda515 commented on ChatBot/ChatBot/ViewModel/SnapshotUpdateStrategy/RefreshButtonToggleStrategy.swift
> +        snapshot.deleteItems([chatMessage])
여기서 insert 를 먼저하고 delete 해주는 이유가 있을까요?

2024-04-10 16:51 UTC, songda515 commented on ChatBot/ChatBot/Scenes/ChatViewController.swift
> +    }
Rx 이용하셔서 button tap 이랑 NotificationCenter 잘 활용해주셨네요 👍

2024-04-10 16:51 UTC, songda515 commented on ChatBot/ChatBot/ViewModel/ChatViewModel.swift
> +    private(set) var dataSource: UICollectionViewDiffableDataSource<Section, ChatMessage>?
Rx 를 다르게 또 활용하려면 아래처럼도 가능할것 같은데, 수정 범위가 클 것 같아서 추후 다른 프로젝트때 해보시고 어떤게 더 편한지 비교해보시면 좋을것 같아요 🙏
- view model 에서는 Section, Item 에 대한 배열을 가지고 있고,
- 해당 값이 바뀔때마다 view controller 에서 구독하고 datasource apply

2024-04-11 01:01 UTC, eensungkim commented on ChatBot/ChatBot.xcodeproj/project.pbxproj
> +				IPHONEOS_DEPLOYMENT_TARGET = 17.0;
연습 브랜치에서 빠르게 테스트하기 위해 잠시 변경했던 것을 까먹고 반영까지 한 것 같습니다. 😿 
수정하도록 하겠습니다.

2024-04-11 01:03 UTC, eensungkim commented on ChatBot/ChatBot/ViewModel/ChatViewModel.swift
> +        dataSource?.applySnapshotUsingReloadData(snapshot) { [weak self] in
넵 감사합니다!!
저도 확인해보고 더 공부해보도록 하겠습니다!

2024-04-11 01:06 UTC, eensungkim commented on ChatBot/ChatBot/ViewModel/ChatViewModel.swift
> +        applySnapShot(with: emptyMessage, strategy: LastChatRemoveStrategy())
applySnapShot 메서드 하나로 전체 로직을 관리하려다 보니 빈 메시지를 추가하게 되었습니다.
파라미터를 다르게 구성하여 다형성을 활용하는 편이 더 나을까요?

2024-04-11 01:07 UTC, eensungkim commented on ChatBot/ChatBot/ViewModel/ChatViewModel.swift
> +                return cell
넵 감사합니다!

2024-04-11 01:31 UTC, eensungkim commented on ChatBot/ChatBot/ViewModel/ChatViewModel.swift
> +        dataSource?.applySnapshotUsingReloadData(snapshot) { [weak self] in
질문을 주셔서 확인하는 과정에서 잘못 이해한 부분이 있었던 점을 확인했습니다.

초기 구현 과정에서 이미 있는 섹션에 스냅샷을 추가하는 경우 오류가 생기는 것을 확인했었는데요.
가장 처음 스냅샷을 apply 하는 로직과 스냅샷에 일부 데이터를 insert 하는 로직을 분리하는 과정에서, 섹션 데이터를 업데이트하는데 사용되는 엉뚱한 `apply(_:to:animatingDifferences:completion:)` 메서드를 활용하면서 오류가 발생했고, 이를 `apply(_:animatingDifferences:)` 메서드의 문제라고 잘못 추론했던 것 같습니다.
그래서 `applySnapshotUsingReloadData` 를 활용해야 하는 것으로 잘못 이해했고 이를 꾸준히 유지했었네요.

apply 가 더 맞는 구현으로 보여 수정하도록 하겠습니다! 🙇

2024-04-11 01:42 UTC, eensungkim commented on ChatBot/ChatBot/ViewModel/SnapshotUpdateStrategy/RefreshButtonToggleStrategy.swift
> +        snapshot.deleteItems([chatMessage])
리팩토링 하기 전의 로직은 delete 를 먼저 진행하고 insert 를 나중에 진행하는 방식이었는데요.

```swift
    func removeLastChat() {
        guard var snapshot = dataSource?.snapshot(),
              let last = snapshot.itemIdentifiers.last else {
            return
        }
        
        snapshot.deleteItems([last])
        dataSource?.applySnapshotUsingReloadData(snapshot)
    }
```

`insertItems` 메서드가 특정한 아이템의 앞, 또는 뒤에만 아이템을 삽입하도록 되어있다 보니 delete 를 먼저 하게 되면 위 코드에서처럼 제일 마지막 아이템을 별도로 찾아와야 하는 관계로,
insert 를 먼저 한 뒤에 delete 하는 로직으로 변경했습니다.

2024-04-11 01:42 UTC, eensungkim commented on ChatBot/ChatBot/ViewModel/ChatViewModel.swift
> +    private(set) var dataSource: UICollectionViewDiffableDataSource<Section, ChatMessage>?
넵 감사합니다!! 🙇

2024-04-11 01:47 UTC, eensungkim commented on ChatBot/ChatBot/ViewModel/ChatViewModel.swift
> +                self?.applySnapShot(with: chatMessage, strategy: AssistantChatUpdateStrategy())
넵 적용했습니다.
관련해서는 추가로 학습을 진행해 보겠습니다. 🙇

2024-04-11 02:11 UTC, eensungkim commented on ChatBot/ChatBot/Scenes/ChatBubbleView.swift
> +        $0.lineBreakMode = .byWordWrapping
오 넵넵 감사합니다!

2024-04-11 02:19 UTC, eensungkim commented on ChatBot/ChatBot/Scenes/ChatBubbleView.swift
> +        switch isUser {
tailStartPoint, tailTipPoint 등은 현재 draw 메서드의 rect 파라미터에 의존하고 있는데요.
이를 변수로 만들어 관리하기 위해서는 bounds 등의 프로퍼티 정보를 통해야 하니, enum 이 ChatBubbleView 의 중첩된 형태로 작성이 되어야 하지 않을까 싶습니다.

이 경우 ChatBubbleView 가 외부와 동일한 열거형을 다루지만 별도의 프로퍼티를 추가로 갖는 형태가 될 것 같은데, 열거형이 2개로 나뉘어 관리되는 편이 더 나은 것일까요??

```swift
// ChatCommonModel.swift 에서 관리하는 열거형
enum ChatRole: String, Codable {
    case system
    case user
    case assistant
}

// ChatBubbleView.swift 에서 관리하는 중첩된 열거형
final class ChatBubbleView: UIView {
    enum ChatRole {
        case system
        case user
        case assistant

        var bubbleViewColor: CGColor {
            switch self {
            case user:
                return UIColor.systemBlue.cgColor
            case system, assistant:
                UIColor.systemGray5.cgColor
            }
        }

        // 그외에 textColor, tailStartPoint 등
    }
}
```

2024-04-11 02:20 UTC, eensungkim commented on ChatBot/ChatBot/Scenes/ChatBubbleView.swift
> +        switch isUser {
일단은 위에 작성한 방향을 따라 수정해 보았습니다! 🙇

2024-04-11 08:35 UTC, eensungkim commented on ChatBot/ChatBot/Scenes/ChatBubbleView.swift
> +        switch isUser {
불리언 값을 활용하는 isUser 대신 ChatRole 열거형을 활용하도록 변경했고, 말풍선의 경우 UserChatBubbleView 와 AssistantChatBubbleView 를 나누는 것으로 처리해 보았습니다!

2024-04-11 09:47 UTC, eensungkim commented on ChatBot/ChatBot/ViewModel/ChatViewModel.swift
> +                }
`setChatBubbleView(_:with:delegate:)` 메소드로 묶어보았습니다!

2024-04-11 09:52 UTC, eensungkim commented on ChatBot/ChatBot/ViewModel/ChatViewModel.swift
> +            self?.snapshotPublisher.accept(items)
제가 아직 Rx 관련 내용이 익숙하지 않아서 말씀해주신 내용을 충분히 이해하지 못했습니다.

현재의 방법이 컴플리션 핸들러 안에서 별도의 퍼블리셔에 items 를 발행하는 형태라면,
snapshot 자체를 구독할 수 있는 별도의 방법이 말씀하시는 방법이라고 이해해 볼 수 있을까요?

2024-04-11 09:57 UTC, eensungkim commented on ChatBot/ChatBot.xcodeproj/project.pbxproj
> +				IPHONEOS_DEPLOYMENT_TARGET = 17.0;
https://github.com/tasty-code/ios-chat-bot/pull/46/commits/8396af90e7762dbb0e33e803ab3f8e7e7998a924

2024-04-11 09:58 UTC, eensungkim commented on ChatBot/ChatBot/Scenes/ChatBubbleView.swift
> +        switch isUser {
https://github.com/tasty-code/ios-chat-bot/pull/46/commits/c1a17929a3089dbc158ec0fc50ed1e452288612d
https://github.com/tasty-code/ios-chat-bot/pull/46/commits/bcac7c8df584edc973c065118c85b88843385e33

2024-04-11 09:58 UTC, eensungkim commented on ChatBot/ChatBot/ViewModel/ChatViewModel.swift
> +                self?.applySnapShot(with: chatMessage, strategy: AssistantChatUpdateStrategy())
https://github.com/tasty-code/ios-chat-bot/pull/46/commits/c297891852c9cfaf02c768aec6e36884dd882a3a

2024-04-11 09:59 UTC, eensungkim commented on ChatBot/ChatBot/ViewModel/ChatViewModel.swift
> +        dataSource?.applySnapshotUsingReloadData(snapshot) { [weak self] in
https://github.com/tasty-code/ios-chat-bot/pull/46/commits/c297891852c9cfaf02c768aec6e36884dd882a3a

2024-04-11 09:59 UTC, eensungkim commented on ChatBot/ChatBot/ViewModel/ChatViewModel.swift
> +                }
https://github.com/tasty-code/ios-chat-bot/pull/46/commits/c297891852c9cfaf02c768aec6e36884dd882a3a

2024-04-11 15:15 UTC, songda515 commented on ChatBot/ChatBot/Scenes/ChatBubbleView.swift
> +        switch isUser {
이전에 생성하셨던 ChatRole 활용하셨네요! 👍

2024-04-11 15:17 UTC, songda515 commented on ChatBot/ChatBot/ViewModel/ChatViewModel.swift
> +                self?.applySnapShot(with: chatMessage, strategy: AssistantChatUpdateStrategy())
subscribe(on:)와 observe(on:) 같이 공부해보시면 좋을것 같아요!

2024-04-11 15:19 UTC, songda515 commented on ChatBot/ChatBot/ViewModel/ChatViewModel.swift
> +            self?.snapshotPublisher.accept(items)
아~! 제가 얘기한건 지금 구현도 괜찮다고 얘기한거 였는데, 풀어서 작성하다 보니깐 문장이 어색해서 이해가 어려웠나봅니다 😅

2024-04-11 15:21 UTC, songda515 commented on ChatBot/ChatBot/ViewModel/ChatViewModel.swift
> +        applySnapShot(with: emptyMessage, strategy: LastChatRemoveStrategy())
지금도 동작에는 이슈가 없으니 괜찮을것 같은데, emptyMessage 가 새로 추가되는건가? 라고 생각이 드는 코드라서 추후에는 emptyMessage 를 추가하지 않고 동작하도록 개선되면 좋을것 같아요!

2024-04-11 15:29 UTC, songda515 approved these changes
추가 커밋 확인해서 approve & merge 진행하겠습니다! 😄
고생 많으셨어요!

2024-04-11 15:44 UTC, merged