AI 챗봇 앱 [STEP1] Comdori, 요한
tasty-code/ios-chat-bot pull request #7
Opened 2024-01-03 07:29 UTC by comdori-wj

# AI 챗봇 앱 [STEP1] Comdori, 요한
리뷰어: @zdodev

안녕하세요 소대! 
이번 챗봇 앱 프로젝트로 함께하게 된 컴도리, 요한입니다.
STEP1 PR 보냅니다. 잘 부탁드립니다!

<br/> 

### 구현 사항
- [x] Request 및 Response를 위한 데이터 모델 설계
- [x] CodingKeys 프로토콜의 활용

<br/> 

### 모델 테스트 출력 화면
<img src="https://hackmd.io/_uploads/H19f9YMda.png" width="700" height="300"/>

<br/> 

## 클래스 설명

| 이름 | 타입 | 구현내용 |
| --- | --- | --- |
| ChatRequestModel | Struct | 유저의 메세지를 담고 있는 request의 body에 들어가는 모델  |
| ChatResponseModel | Struct | 유저에게 보여주는 ai의 메세지를 담고 있는 response 모델 |
| ChatCommonModel | Struct | request와 response 모델에 공통적인 모델을 담고 있는 집합 |

<br/>

## 궁금한 점 
- 공통적으로 쓰이는 모델인 Message를 어떻게 분리를 해야할 지 고민했습니다. 현재 코드에서는 나중에 공통적으로 쓰이는 구조체가 있을 수 있다 생각하여 ChatCommonModel 파일을 만들었는데 잘 분리했는지는 확신이 들지 않습니다.

2024-01-03 15:13 UTC, zdodev requested changes
안녕하세요. @comdori-wj , @dpwns1234 !

Step 1 진행 잘해주셨습니다!
Request, Response 모델을 잘 정의해보셨네요!

먼저 질문에 대한 제 생각은
모델에서 공통적으로 쓰이는 부분을 분리할 것인지 분리하지 않을 것인지는 둘다 장단점이 있어 팀마다 다를 수 있지 않을까 싶습니다. 장단점에 대해서 한번 고민해보고 진행해도 될 것 같습니다. 지금 상태로 진행해도 무방합니다!

이외에 몇가지 궁금증을 남겨보았습니다.
같이 의견 나눠보면 좋을 것 같습니다!

2024-01-03 15:13 UTC, zdodev commented on ChatBot/ChatBot/Models/ChatCommonModel.swift
> +}
API 문서에서 Request body 내 하위 `messages` 설명란에 더 다양한 파라미터가 있습니다. API 문서에서 사용할 수 있는 파라미터를 더 추가해보는 것은 어떨까요?

2024-01-03 15:13 UTC, zdodev commented on ChatBot/ChatBot/Models/ChatResponseModel.swift
> +    let systemFingerprint: String?
`systemFingerprint` 프로퍼티를 옵셔널로 선언한 이유가 있을까요?

2024-01-03 15:13 UTC, zdodev commented on ChatBot/ChatBot/Models/ChatResponseModel.swift
> +    let message: Message
응답값으로 전달되는 `Message` 타입의 속성이 API 문서보다 적은 부분도 있고 타입이 맞지 않는 부분도 있습니다. 한번 확인해볼 수 있을까요?

2024-01-03 15:13 UTC, zdodev commented on ChatBot/ChatBot/Models/ChatResponseModel.swift
> +    let logProblems: Int?
`logProblems` 타입을 Int? 로 정의하신 이유가 있을까요?

2024-01-03 15:13 UTC, zdodev commented on ChatBot/ChatBot/Models/ChatResponseModel.swift
> +    let promptTokens: Int?
`promptTokens` 타입을 Int? 로 정의하신 이유가 있을까요?

2024-01-03 15:13 UTC, zdodev commented on ChatBot/ChatBot/Models/ChatResponseModel.swift
> +        case promptTokens = "prompt_okens"
오타가 있는 것 같습니다!

2024-01-04 02:52 UTC, comdori-wj commented on ChatBot/ChatBot/Models/ChatCommonModel.swift
> +}
찾아보았는데, `name` 파라미터가 있다는 것을 알았습니다. 이름을 사용해서 호칭을 부를 수 있도록 하겠습니다.

2024-01-04 06:20 UTC, dpwns1234 commented on ChatBot/ChatBot/Models/ChatResponseModel.swift
> +        case promptTokens = "prompt_okens"
수정하겠습니다!!

2024-01-04 06:28 UTC, dpwns1234 commented on ChatBot/ChatBot/Models/ChatResponseModel.swift
> +    let systemFingerprint: String?
예시로 작성된 Response 프로퍼티를 보니 `systemFingerprint`가 있어 String으로 선언하였는데, 직접 테스트를 해보니 값을 받아오지 못하는 에러를 발생하였습니다. 그래서 못 받아오는 예외 처리를 위해 옵셔널로 처리하였습니다.

2024-01-04 06:55 UTC, dpwns1234 commented on ChatBot/ChatBot/Models/ChatResponseModel.swift
> +    let logProblems: Int?
API Reference를 보며 타입을 정해주었는데, 지금 다시 보니 legacy에 있는 프로퍼티를 보고 잘못 정의하였습니다..
현재 log problem을 받을 이유가 없다고 생각되어 제거하였습니다.

2024-01-04 07:00 UTC, dpwns1234 commented on ChatBot/ChatBot/Models/ChatResponseModel.swift
> +    let promptTokens: Int?
오타로 nil값이 들어오고 있었습니다. 그래서 옵셔널 타입으로 착각해서 Int?로 정의하였었습니다. Int 타입으로 수정하였습니다.

2024-01-04 08:18 UTC, dpwns1234 commented on ChatBot/ChatBot/Models/ChatResponseModel.swift
> +    let message: Message
Message 타입의 여러 프로퍼티가 있는 걸 확인하였고 그 중 tool_calls 프로퍼티를 추가해주었고, response의 content type이 String 옵셔널이라 명시 되어 있는 것을 확인하지 못하였습니다. 현재 String 옵셔널로 변경하였습니다!

2024-01-04 16:23 UTC, zdodev commented on ChatBot/ChatBot/Models/ChatCommonModel.swift
> +}
OpenAI 모델에 사용자가 정의한 함수를 선택적으로 호출하는 기능이라 파악됩니다. 정확한 내용을 위해서 한번 더 확인해보면 좋을 것 같습니다!

2024-01-04 16:32 UTC, zdodev commented
수정이후 현재 에러가 발생하고 있습니다. 확인부탁드립니다!

2024-01-05 00:57 UTC, comdori-wj commented
> 수정이후 현재 에러가 발생하고 있습니다. 확인부탁드립니다!

파일명이 바뀐것을 반영안하여 Xcode상에서 못 읽는 상태였습니다. 다시 수정하였습니다.

2024-01-05 15:21 UTC, zdodev approved these changes
안녕하세요. @comdori-wj , @dpwns1234 

모델을 더 잘 개선해보셨네요! 문제되었던 이슈도 해결되었습니다.
Step1 진행하시느라 고생하셨습니다!

2024-01-05 15:21 UTC, merged