AI 챗봇 앱 [STEP 2-1] 벨로, 밤삭
tasty-code/ios-chat-bot pull request #9
Opened 2024-01-05 06:21 UTC by JinUng41

리뷰어: @forestjae

### 팀원
| 프로필 사진 | <img src="https://avatars.githubusercontent.com/u/114239407?v=4" width="90" height="90"></a> | <img src="https://avatars.githubusercontent.com/u/91656206?v=4" width=90></a> | 
| ---- | ---------- | --------- | 
| in Github | [@bamsak](https://github.com/bamsak) | [@JinUng41](https://github.com/JinUng41) 
| in SeSAC | 밤삭 | 벨로

안녕하세요, 숲재!!

[STEP 2-1]에서는 Network API 통신을 위한 모델들에 대해 정의해 보았습니다.

잘 부탁드립니다!! 🙇‍♂️🙇‍♂️

## 구현 내용

### 폴더 구조

```

.
├── Application
│   ├── AppDelegate.swift
│   └── SceneDelegate.swift
├── Controllers
│   └── ViewController.swift
├── Extensions
│   ├── Bundle+Extension.swift
│   └── URLRequest+Extension.swift
├── Models
│   ├── DTOs
│   │   ├── GPTMessageDTO.swift
│   │   ├── GPTRequestDTO.swift
│   │   └── GPTResponseDTO.swift
│   ├── Messages
│   │   ├── Implementation
│   │   │   ├── AssistantMessage.swift
│   │   │   ├── SystemMessage.swift
│   │   │   └── UserMessage.swift
│   │   ├── Interface
│   │   │   └── GPTMessageable.swift
│   │   └── MessageRole
│   │       └── MessageRole.swift
│   └── Network
│       ├── HTTPMethod.swift
│       └── Request
│           ├── Implementation
│           │   └── GPTRequest.swift
│           └── Interface
│               └── APIRequestable.swift
└── Resources
    ├── Assets.xcassets
    │   ├── AccentColor.colorset
    │   │   └── Contents.json
    │   ├── AppIcon.appiconset
    │   │   └── Contents.json
    │   └── Contents.json
    ├── Base.lproj
    │   └── LaunchScreen.storyboard
    └── Info.plist
```

### 변경 사항

- APIRequest
    - `protocol`
- GPTRequest
    - `struct`
- HTTPMethod
    - `enum`
- URLRequest + Extension
    - APIRequest를 이용하여 URLRequest를 생성할 수 있도록 구현함.

### APIRequestable & GPTRequest ⇒ URLRequest

추후 NetworkManager 객체에서 API 통신에 필요한 URLRequest를 위해 프로토콜인 APIRequestable와 구현체인 GPTRequest를 정의하였습니다.

```swift
struct GPTRequest: APIRequestable {
    let baseURL: URL? = URL(string: "https://api.openai.com/v1/chat/completions")
    let headerFeilds: [String : String]
    let httpBodyData: Data?
    
    init?(httpBodyData: Encodable) {
        guard let apiKey = Bundle.main.gptAPIKey
        else {
            return nil
        }
        
        headerFeilds = [
            "Authorization": "Bearer \(apiKey)",
            "Content-Type" : "application/json"
        ]
        
        guard let encodedData = try? JSONEncoder().encode(httpBodyData)
        else {
            self.httpBodyData = nil
            return
        }
        
        self.httpBodyData = encodedData
    }
}
```

또한 이렇게 만들어지는 APIRequestable을 이용하여 URLRequest를 생성할 수 있도록 구현해 보았습니다.

```swift
extension URLRequest {
    init?(apiRequest: APIRequestable) {
        guard let baseURL = apiRequest.baseURL
        else {
            return nil
        }
        self.init(url: baseURL)
        self.allHTTPHeaderFields = apiRequest.headerFeilds
        self.httpMethod = "\(apiRequest.httpMethod)"
        self.httpBody = apiRequest.httpBodyData
    }
}
```

- GPT Request와 URLRequest extension에 실패 가능한 생성자(`init?`)을 사용한 이유
    - GPT Request와 URLRequest 생성 시에 guard let 구문으로 에러 처리를 하기 위함입니다.

**다만 한 가지 고민이라면, 현재 GPT Request 이니셜 라이저 내부에서 encoding을 하는 것이 적합한 방식인지 의견을 구하고 싶습니다!**

2024-01-05 12:07 UTC, forestjae commented on ChatBot/ChatBot/Models/Network/Request/Implementation/GPTRequest.swift
> +    let httpBodyData: Data?
APIRequestable에는 네트워크 요청에 필요한 여러 명세가 담겨 있는 객체로 의도하신 걸로 보이는데요.
여기서 Data 타입을 직접 들고 있을 필요가 없어 보여요. 여기서 Encodable을 들고 있도록 변경하면 어떨까요?

또한 pr에도 작성해 주셨듯이, 여기서 encoding을 수행하는건 어색합니다.

네트워킹을 담당하는 객체에서 이루어져야 할 것 같아요.

2024-01-05 12:07 UTC, forestjae commented on ChatBot/ChatBot/Models/Network/Request/Implementation/GPTRequest.swift
> +    let headerFeilds: [String : String]
오타가 있습니다.

2024-01-05 12:12 UTC, forestjae requested changes
고생하셨습니다.

코멘트 남겨드렸으니 확인 부탁드려요~

2024-01-08 02:00 UTC, JinUng41 commented on ChatBot/ChatBot/Models/Network/Request/Implementation/GPTRequest.swift
> +    let headerFeilds: [String : String]
네 수정하였습니다!

2024-01-08 02:01 UTC, JinUng41 commented on ChatBot/ChatBot/Models/Network/Request/Implementation/GPTRequest.swift
> +    let httpBodyData: Data?
넵, 추가적으로 인코딩을 진행하는 URLRequestConverter 객체를 선언하여 구현해 보았습니다.

2024-01-09 00:44 UTC, forestjae approved these changes

2024-01-09 00:44 UTC, merged

2024-01-09 00:45 UTC, forestjae commented on ChatBot/ChatBot/Models/Network/URLRequestConverter/Implementation/URLRequestConverter.swift
> +struct URLRequestConverter: URLRequestConvertible {
👍